### ISSUE TITLE
Google Docs

### ISSUE THREAD

**Issue by arthax0r** [vimperator/vimperator-labs#1]
First, <3 vimperator long time.

Secondly, when using Google docs, if you hit escape you leave insert mode but you can't get back by clicking in the document.  You have to click one of the menus then click back in the doc.  Been a long time issue I just deal w/but I'm becoming more active on Github so I thought I'd toss it out there.

Thanks for being awesome!

**Comment by gkatsev** [comment]
I think that this has been fixed in the latest alpha release along with the facebook issue that has been plaguing vimperator recently.
