### ISSUE TITLE
Feature request: key combo for selecting all in an input field

### ISSUE THREAD

**Issue by jonhoo** [vimperator/vimperator-labs#101]
In many cases, I want to select the entirety of the text in an input field, either to clear it or to copy its contents. Normally, the Firefox shortcut for this is Ctrl+A (select all), but this is overridden by Vimperator to mean "go to the beginning of the line". I feel that a select all shortcut is useful enough that Vimperator should present an alternative to it given that it removes the native browser version. Personally, I'd propose Ctrl+V, as it is reminiscent of VISUAL-LINE mode, but the exact shortcut does not bother me too much.

As a side note: it appears the `C-a` shortcut is not documented anywhere? In fact, the only documented insert-mode features seem to be `C-i` (edit content in `EDITOR`) and `C-]` (expand abbreviation). Is there a reason other ones are not mentioned in the "Insert mode" section of `:helpall`?

**Comment by svermeulen** [comment]
Bash shortcuts seem good but IMO should be an option that's disabled by default, since it is very off-putting to new users who depend on CTRL+A to select all

**Comment by gkatsev** [comment]
Yeah, it makes sense to have read-line commands as an option and default to no. Either that, or provide an easy plugin that adds these back in.

Also, for those that don't know, there's `<c-t>` which enables textarea mode which allows you much more control a la vim.

**Comment by maxauthority** [comment]
Yeah, that sounds like a good approach, although I prefer the simple plugin
and a good info like
-------
Put
:inoremap <C-a> ...
:cnoremap <C-a> ...
...

in your ~/.vimperatorrc, if you prefer Emacs-like keybindings in textboxes.
------
(or in a wiki page).

--
Martin

**Comment by dolanor** [comment]
@gkatsev I didn't know for CTRL-T. Very good compromise !

Other than that, CTRL+SHIFT+A already does that select-all ! So it's good for me (just found out about it!)

**Comment by gkatsev** [comment]
Going to close this for now since there are work-arounds.

**Comment by cirosantilli** [comment]
+1 Confusing point for new users.

**Comment by MikeDacre** [comment]
I don't like necro-posting on a closed issue usually, but I feel like these bash-like shortcuts should be much better documented. The most frustrating thing for me as a new user of vimperator was not being able to select all. It is so hard-wired that I just do it automatically.

The work-arounds in this thread work well, and I am now using them, but it given how much of a change this is from normal, I think it makes sense having the behaviour and work-arounds well documented, or even having an easy command to disable the behaviour.

**Comment by kirkins** [comment]
Yes I'm also coming here from search looking for a work around to select all. Would prefer ctrl+a default to select all.

Most who come to vimperator are probably former power users of regular shortcuts such as this.

**Comment by Chinggis6** [comment]
Another way would be

`:inoremap <C-a> <Ins><C-a><Ins>`

Add in `.vimperatorrc`
