### ISSUE TITLE
Feature request: proxy (profile) switching commands

### ISSUE THREAD

**Issue by shouya** [vimperator/vimperator-labs#129]
I think some might need a command to quickly switching the proxy on and off. Probably as well as proxy setting. I expect a group of commands that can be used like:

```
:proxyadd -name noproxy direct
:proxyadd -name proxy1 socks5://username:password@host.name:1234
:proxydel -name proxy1
:proxyswitch noproxy
:proxyswitch proxy1
```

**Comment by gkatsev** [comment]
I'm going to close this as low priority. I think making this a plugin is best rather than integrating it into vimperator.
