### ISSUE TITLE
Can't type spaces in :tabopen or :open

### ISSUE THREAD

**Issue by hut** [vimperator/vimperator-labs#132]
I can't type any spaces as soon as I enter ":tabopen " or ":open ".  Only the one space immediately after the command works.  If I delete any characters, or even the whole command, I still can't type any spaces until I exit and re-enter the console.

I tried this in a fresh profile on firefox 34.0.5 with only the vimperator 3.8.3 addon, and also with my old profile with years of history/bookmarks.

**Comment by hut** [comment]
After continued usage, it works now. Strangely enough. Any idea what it could've been?

**Comment by hut** [comment]
It had to do with a broken sshfs mount in my home directory. Apparently vimperator tried to read my home dir to generate the tab completions. After properly unmounting the sshfs, it works again.

**Comment by maxauthority** [comment]
I changed the default 'complete' option to not include local files anymore
by default. So Vimperator 3.8.4 will work for your usecase with sshfs as
well.
