### ISSUE TITLE
My autocmd is not firing correctly on about:newtab

### ISSUE THREAD

**Issue by vaibhavsagar** [vimperator/vimperator-labs#133]
Hi, I am a recent switcher from Pentadactyl and I am trying the following `autocmd` so I can open new tabs from the tab bar as well as with `<C-t>`:

    au LocationChange about:newtab :normal! o

It doesn't seem to be working correctly, i.e. it is only firing on every other new tab load. Am I making a mistake and/or is there an easier way to accomplish this? I have the navigation bar turned off as well:

    set toolbars=nonavigation

**Comment by maxauthority** [comment]
You need to escape the : as it somehow interferes with the regular
expresstion.

Try:
:au LocationChange about\:newtab :normal! o

**Comment by vaibhavsagar** [comment]
Thank you for this suggestion. After I restart Firefox and open a new tab, this pops up the :open window, but subsequent new tab openings have no effect and the autocmd has the effect of inserting an 'o' into the most recently selected text field (e.g. this one) so it seems to be working but not having the desired effect. I just tried

    set focuscontent

as well but that did not seem to make a difference. My .vimperatorrc is [here](https://raw.githubusercontent.com/vaibhavsagar/dotfiles/master/.vimperatorrc) if you'd like to have a look at it.

**Comment by maxauthority** [comment]
That might be a timing issue. For such things the code which is executed
must be something like

:js liberator.sleep(500) && liberator.open("www.google.com");

but you need to replace the liberator.open() with something like
liberator.normal("o") to push a literal "o" to the input but I don't know
the right syntax by heart, but it might help to find the solution.

**Comment by vaibhavsagar** [comment]
I think I'll just do without the autocmd for now. Feel free to close the issue.
