### ISSUE TITLE
How to run js code from vimperator?

### ISSUE THREAD

**Issue by deterenkelt** [vimperator/vimperator-labs#135]
I know there’s `:js` but when I try to run

    js sessionStorage.clear();

It gives me an [error](http://images.netbynet.ru/imgs/6aa586275f99ae404296fc57e5e054f0.png). I’d also want to bind this to a hotkey in order to perform cleaning instead of restarting the browser.

**Comment by gkatsev** [comment]
When you run js by default it's run in vimperator's context. You want to run it from the page's content: `content`.
Try
```
:js content.sessionStorage.clear();
```
