### ISSUE TITLE
Firefox 37, styles are broken

### ISSUE THREAD

**Issue by gkatsev** [vimperator/vimperator-labs#139]
Or some similar message.
None of the vimperator styles were getting defined on-load.

**Comment by gkatsev** [comment]
Firefox 37 is the current (17 jan 15) aurora build.

**Comment by sukima** [comment]
Attempted to uninstall and reload. Still broken. Was using the developer addition of FireFox.  I'm giving up on the developer addition as the only reason I use FireFox is for vimperator.

**Comment by gkatsev** [comment]
Seems like this is fixed in master. I made another alpha release here: https://github.com/vimperator/vimperator-labs/releases/tag/3.8.3-a4

@sukima can you please try out that XPI and let me know if it fixes it for you as well?

**Comment by gkatsev** [comment]
Going to close this for now.

**Comment by sukima** [comment]
@gkatsev **confirmed** https://github.com/vimperator/vimperator-labs/releases/tag/3.8.3-a4 fixes the issue in FireFox Developer Addition.

**Comment by gkatsev** [comment]
Seems like the styles are broken again in: 37.0a2 (2015-02-01)
