### ISSUE TITLE
Textarea mode's `f` is off by one

### ISSUE THREAD

**Issue by robrechtdr** [vimperator/vimperator-labs#140]
Imagine I have the following text with my cursor on the first character:  `hi lady`.

In vim, when I do `fl` the cursor is now over the `l`. Then I go to *insert mode* and write `my` I end up with the following: `hi mylady`.

In vimperator when I do the same sequence of commands for the same text in a text field using textarea mode, I end up with the following: `hi lmyady'`.

**Comment by gkatsev** [comment]
I'm not certain there's anything we can do about this. This is because vim has the cursor *over* letters when not in insert mode. So, when you hit `i`, you start entering text before the current character and `a` starts you after the current character.
However, I'm still investigating.

**Comment by robrechtdr** [comment]
Thanks for the feedback.

**Comment by gkatsev** [comment]
Actually, I think I've got it to be more vim-like.

**Comment by gkatsev** [comment]
@robrechtdr can you test PR #142? I can make you an XPI, if you want.

**Comment by robrechtdr** [comment]
Could you make one (XPI)? I appreciate it.

**Comment by gkatsev** [comment]
@robrechtdr sure. Here you go: https://dl.dropboxusercontent.com/u/2362897/vimperator-3.8.3-a4.xpi

**Comment by robrechtdr** [comment]
Great, works like vim now. Even when you go to text-area mode the cursor jumps back like in vim. Thanks!

**Comment by gkatsev** [comment]
Awesome. In that case, I'll merge that PR in.

**Comment by robrechtdr** [comment]
After I installed the new plugin I've lost the ability to drag tabs.

**Comment by gkatsev** [comment]
That's... weird.
What version of firefox?

**Comment by gkatsev** [comment]
I have no issues with this in either firefox aurora or stable firefox.

**Comment by robrechtdr** [comment]
Firefox/34.0 . However, I restarted firefox and the problem is gone now.

**Comment by gkatsev** [comment]
Cool.
