### ISSUE TITLE
Vimperattor broken in firefox 37

### ISSUE THREAD

**Issue by crossroads1112** [vimperator/vimperator-labs#145]
This problem has existed since firefox 37 was in nightly. The background of the status line becomes transparent with white text. This problem persists on a blank profile. Sorry, I am ont able to describe it well. Here is a [screenshot](http://i.imgur.com/oFVragB.png) of what I mean.

**Comment by gkatsev** [comment]
Yep, that's fixed in the lastest code. Try grabbing [alpha 5](https://github.com/vimperator/vimperator-labs/releases/tag/3.8.3-a5).

**Comment by crossroads1112** [comment]
I apologize! I didn't know that existed

**Comment by gkatsev** [comment]
No worries. I had the same issue earlier today and realized that master fixed it. Made an alpha release with the fix :)
