### ISSUE TITLE
Vimperator on Tree Style Tab

### ISSUE THREAD

**Issue by jwvim** [vimperator/vimperator-labs#147]
Tree Style Tab is a very useful add-ons

Tree Style Tab :: Add-ons for Firefox
https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

I know a lot of vimperator user use it.

On the latest version of Tree Style Tab 0.15.2014120101, it seems not work properlyit.
When I set gui=none, it only hide tabs, but the tab bar is not hidden.
the tabs and the tab bar could all be hidden in the ealier versions of tree style tab.

Tree Style Tab 0.15.2014120101

Vimperator 3.8.3-a5
Vimperator 3.8.3

**Comment by timss** [comment]
Does not sound like a Vimperator bug. When the tab toolbar is hidden, Tree Style Tab should preferably respect that. 

Keep in mind this could be due to a technical limitation of Firefox, as Tree Style Tab isn't your average addon, but changes quite a lot.

**Comment by gkatsev** [comment]
It's possible that vimperator turns off toolbars it knows about (i.e., defaults) when `gui=none` and because TST has their own toolbar it doesn't get hidden. Either way, I'm not certain that it should be vimperator's job police custom toolbar hiding.

**Comment by jwvim** [comment]
the nightly version of TST works for me.
