### ISSUE TITLE
Problem with tree style tab

### ISSUE THREAD

**Issue by jwvim** [vimperator/vimperator-labs#148]
Tree Style Tab :: Add-ons for Firefox
https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

![problem - tree style tab on vimperator](https://cloud.githubusercontent.com/assets/7594650/5794634/dc02077e-9fb1-11e4-8a7b-5b127798097a.jpg)

when type in command line, a tab will be shown in the command list, pls check the picture I attached.
this problem seems to be exist in a long time and not fixed in vimp 3.8.3-a5 and latest tree style tab

**Comment by timss** [comment]
I'm able to reproduce this, but only with certain Tree Style Tab themes. This leads me to believe that it isn't necessarily vimperator which is misbehaving, but maybe a CSS rule for TST that overrides other elements it should not.

Using the theme "mixed" I do not get this error, but it happens with "flat". Do you see the same results?

**Comment by dkasak** [comment]
@timss I just ran into this bug and I get the same results as you.

**Comment by timss** [comment]
@dkasak Take a look at my pull request to Tree Style tab :-) 

With it all skins work fine. If you you want to test it yourself you can download a packaged `.xpi` from my site. Hopefully it'll get merged though. 

http://r.thevoid.no/tmp/treestyletab.xpi

**Comment by jwvim** [comment]
the nightly version of TST works for me.

**Comment by timss** [comment]
@jwvim Yeah, it was fixed a long time ago:

https://github.com/piroor/treestyletab/pull/843
