### ISSUE TITLE
Upload Beta Releases to AMO

### ISSUE THREAD

**Issue by kevincox** [vimperator/vimperator-labs#149]
it would be nice if the prereleases were uploaded to addons.mozilla.org in a beta channel so that it would be easier to test them, and it would also let some people get fixes quicker and easier.

**Comment by gkatsev** [comment]
I didn't even know that they had beta releases.

**Comment by kevincox** [comment]
Yeah, I was using AMO for a while before realizing too.  It is quite useful.  The beta channel is" hidden" from the general user but allows people who want to test to subscribe and get the latest versions.

Basically you just append something to your addon version and it automatically tags it as a prerelease.

https://addons.mozilla.org/en-US/developers/docs/policies/maintenance

**Comment by gkatsev** [comment]
Going to close this since we agree it's A Good Thing™. I'll try and make it happen but no promises.
