### ISSUE TITLE
Vimperator ESC key unusable when Mouseless-Browsing Firefox addon is installed

### ISSUE THREAD

**Issue by shivams** [vimperator/vimperator-labs#153]
ESC key stops working altogether when you are also using Mouseless-Browsing addon on Firefox. I used to use this addon before moving to Vimperator. When using Vimperator, unusbaility of ESC key made Vimperator completely unusable. I had no clue what was going wrong. Then I tried disabling various modules and found that mouseless-browsing was the culprit.

I am assuming this is not a serious issue which Vimperator developers should be looking forward to fixing, as having Vimperator makes Mouseless-Browser addon futile. But I have just mentioned this issue here in case anyone else is also facing this.

**Comment by gkatsev** [comment]
It probably has to do with the fact that both addons bind keyboard events strongly.

Since there's no action to be taken here yet, I'll close this issue. We could revisit it at some time in the future.
