### ISSUE TITLE
question installing alpha releases

### ISSUE THREAD

**Issue by protrolium** [vimperator/vimperator-labs#155]
I am running Alpha 5 by installing the .xpi in Firefox 35. Works great until I restart Firefox, as it seems I need to reinstall the .xpi. Is there another installation method which prevents me from having to reinstall each time I load the browser?

**Comment by gkatsev** [comment]
That's really weird. It *should* work just fine. Maybe if you try uninstalling and reinstalling?
I'll see if I can figure out why it might be happening. I think someone mentioned that in facebook comment issue also.

**Comment by gkatsev** [comment]
Huh, just had that happen to myself. I wonder if it's because we had it installed through AMO originally.

**Comment by krypt-n** [comment]
It happened to me too until I disabled auto updating of addons. Maybe firefox thinks that the version in the offical addon repository is newer than the alpha version and downgrades it?

**Comment by gkatsev** [comment]
Yeah, that might be it. Particularly if you installed the xpi over the AMO installed version.

**Comment by gkatsev** [comment]
Sounds like the issue is autoupdates. You should turn these off for vimperator. Though, hopefully, we'll get an official release soon.
