### ISSUE TITLE
How can I close the last tab by pressing "d"?

### ISSUE THREAD

**Issue by llinfeng** [vimperator/vimperator-labs#156]
I am new to vimperator (newly switched back here as Pentadactyl is almost dead.)

One difference I notice here is that, if I keep pressing the `d` key up till the last tab, another keystroke of `d` does not give close the window. Is there an option that I need to specify in `_vimperatorrc`?

Thank you.

**Comment by timss** [comment]
You could just map <kbd>d</kbd> to <kbd>Ctrl+w</kbd> which works just fine alongside vimperator.

    map d <C-w>

**Comment by gkatsev** [comment]
Vimperator should probably have an option for this or respect firefox's option for this (`browser.tabs.closeWindowWithLastTab`).

**Comment by timss** [comment]
@gkatsev The functionality for quiting on last tab is actually already there, but it seems to be unused in the `bd[elete]", "bw[ipeout]", "bun[load]", "tabc[lose]` commands. I wasn't able to find if <kbd>d</kbd> uses one of these commands or directly invokes `tab.remove()` though.

    // (tab, count, oirentation, quitOnLastTab, force)
    tabs.remove(tabs.getTab(), Math.max(count, 1), orientation, 0, special);

Relevant lines: \#[214](https://github.com/vimperator/vimperator-labs/blob/master/common/content/tabs.js#L214) and \#[611](https://github.com/vimperator/vimperator-labs/blob/master/common/content/tabs.js#L611)

I'm not well-versed in JavaScript, and don't know much about the Vimperator source code, but using `:js` I was able to quit on last tab:

    // don't quit on last tab
    :js tabs.remove(tabs.getTab(0), 1, 0, 0, false)

    // quit on last tab
    :js tabs.remove(tabs.getTab(0), 1, 0, 1, false)

With `quitOnLastTab=0` I'm seeing the exact same behavior as with <kbd>d</kbd>. 

If I'm understanding it correctly, what is missing is the actual check for `browser.tabs.closeWindowWithLastTab`, as upposed to hard-coding to never close on last tab in `:bd[elete]` etc. Maybe even remove the argument for `tabs.remove()` and let it decide for itself based upon the firefox config? 

How does this sound? I'm not sure if this is something I'd be able to do myself, but I could possibly give it a shot.

**Comment by gkatsev** [comment]
Yeah, I think we should be checking the firefox option. Not sure about the implementation.

**Comment by llinfeng** [comment]
@timss Thank you for pointing me to the mapping method. A safer option may be `nnoremap d <C-W>`, with the `nore` part.

@gkatsev Thank you for pointing to the firefox option, however, toggling the value for that does not help solve help the problem. While on, pressing `<C-W>` could close the last tab; when switching it to be "False", pressing `<C-W>` can no longer close the last tab. Not sure if this is only for me, or for everyone.

To rap up, conducting a map seems to be a easier way of handling the issue.

All the best, 

Linfeng

**Comment by gkatsev** [comment]
@llinfeng yep, the map is the current work around. We're saying that vimperator should respect that firefox option for `d`.

**Comment by llinfeng** [comment]
Great walk around!

**Comment by gkatsev** [comment]
Going to leave this open so we can track the change to vimperator to fix `d`.

**Comment by maxauthority** [comment]
"d" not closing the window on the last tab is actually a feature, since it cannot be undone by pressing "u". If you want to close your browser, you should just use Ctrl-q (or :quitall or something like that). But closing any app with a single key like "d" is even uncommon for Vim users ;)

**Comment by gkatsev** [comment]
@maxauthority yes, but there's a whole firefox setting for this feature. Why not have `d` respect that setting?

**Comment by llinfeng** [comment]
@maxauthority, would it be possible to implement the "undo" after closing a firefox session? Upon clean installation, I think <C-S-N> will recall the previous session however times firefox.exe had been terminated. This seems to be missing with Vimperator. (If this feature did not came with firefox, it must be from Pentadactyl).

Does this involve an internal firefox setting?
