### ISSUE TITLE
Allowing Google's Keyboard Navigation Features

### ISSUE THREAD

**Issue by shivams** [vimperator/vimperator-labs#158]
Before using vimperator, I used to use the Google's default keyboard navigation features. One feature was the small blue arrow which we could point at different search results using up/down arrow keys.

However, after installing vimperator that arrow does not appear anymore. 

Is their a fix for this thing? That arrow-based navigation was really good, and I wish that it works.

**Comment by timss** [comment]
Odd, but it does seem that Vimperator conflict with Google's navigation, even if you use `:ignorekeys` or the <kbd>Insert</kbd> key. 

As a workaround, can you use hints instead using <kbd>f</kbd> and <kbd>F</kbd>? See `:h hints` and `:h hints-tutorial` for more information.

**Comment by gkatsev** [comment]
You need to put vimperator into pass-through mode. Either directly or via ignorekeys or just with `i`. If it's not working with that, that's definitely a bug.
I generally have an autocommand that just turns on pass-through mode completely on google properties.

**Comment by timss** [comment]
@gkatsev Eh, sorry, nevermind that. I tested again on a different install, Firefox developer edition 37.0a2 with Vimperator 3.8.3.a5 (Windows). Worked as expected in pass-through-mode. I got the same setup on my Linux machine, although with a non-developer build of 37.0a2. Probably some other addon or firefox setting interfering.

**Comment by shivams** [comment]
Ok. Thank you guys. It's indeed working. Pressing `i` and then pressing `tab` key on Google does make that blue arrow show up. So, there is definitely no bug here. 

@timss: Thanks for the hints mode. But I am already using them on most web pages. Somehow, on google though, navigating with their blue arrow makes me feel at home. 

@gkatsev: Thanks for that autocommand tip. 

Issue is now closed.
