### ISSUE TITLE
macro speed / pause

### ISSUE THREAD

**Issue by thomasrebele** [vimperator/vimperator-labs#161]
recently I discovered vimperator, and it's awesome!
I wanted to use a macro on a page, but it gives an error message "Not too fast please!" (http://kanji.koohii.com/study)

Is there a function to pause x seconds (e.g. 0.5 seconds), in order to mimic human speed? Or to reduce the macro playback speed?
I haven't found anything useful in the documentation

**Comment by maxauthority** [comment]
Unfortunately no :( But yeah, I really see that such a delay would be
really helpful.

**Comment by leahim** [comment]
You could use '!' command to delay actions.. When you need to pause/delay execution of the next macro step, simply run something like '!sleep 1' in cmd mode. This runs shell sleep command, effectively giving you a delay before next macro step. Works well on *nix, windows should have something similar.. Cheers!

**Comment by thomasrebele** [comment]
@leahim : thank you very much, works like a charm :D vimperator is a really great tool!
