### ISSUE TITLE
One second freeze when trying to open or tabopen  - disk write?

### ISSUE THREAD

**Issue by shankargopal** [vimperator/vimperator-labs#164]
I use a Debian Linux (jessie) system that runs off a flash drive.  This makes disk writes very expensive in terms of latency.  I found Firefox almost unusable due to frequent long pauses and freezes, but the tweaks [here](https://wiki.archlinux.org/index.php/firefox_tweaks) - particularly the change to `browser.sessionstore` and disabling the disk cache - have helped considerably.

However, whenever I press 't' to open a new tab, the browser pauses for about a second.  Why does this occur?  Is there any way I can remove this delay?

**Comment by timss** [comment]
It might be because of the autocomplete functionality with open prompts. Can you try disabling some of the options set in `set complete=`? See `:h complete` for more information. 

For example it searches through your bookmarks by default (option `l`). If these are not cached it would require reading from disk.

**Comment by shankargopal** [comment]
That seems to help a lot, thanks.  I'll try it on some of the slower
machines tomorrow and see if it continues to be a problem.  

Thanks for all the work that you all do!

**Comment by maxauthority** [comment]
The "complete" option has been changed to exclude local files in the
development version, so from 3.8.4 on you shouldn't have any problems out
of the box (we should really release that soon, and probably even call it
3.9).

**Comment by timss** [comment]
@shankargopal I'm not a part of the Vimperator team, but happy to help! Seems like this issue could be closed due to the `complete` changes in the next version.

**Comment by maxauthority** [comment]
Fixed by changing the "complete" option.
