### ISSUE TITLE
completion hints don't go away when pasting text

### ISSUE THREAD

**Issue by sam113101** [vimperator/vimperator-labs#166]
When you type text in the vimperator bar, it gives you hints (for example, if you type ":tabopen", it will insert the first search keyboard in light gray (a lighter shade than normal text). You can't interact with that text unless you tab complete it. However, if you paste some text, the hint gets printed for real and you need to remove it.

**Comment by timss** [comment]
Is this not the behavior you're seeing?

http://a.pomf.se/ahtikv.webm

As you can see 'aw' is the search keyword my setup defaults to when I do `:tabopen`, but it isn't visable or used when pasting anything. Not sure if I understand what is wrong.

Have you changed 'complete' or any other related setting?

**Comment by sam113101** [comment]
This is what I'm seeing: http://a.pomf.se/rvmmgz.ogv
I'm using shift+insert, ctrl+v seems to be working properly.

**Comment by timss** [comment]
Ah, ok. Yeah, I'm seeing the same if I use <kbd>shift</kbd>+<kbd>insert</kbd>. 
Not sure how this could happen though.

**Comment by gkatsev** [comment]
Unfortunately, this is a known issue. See #65.
