### ISSUE TITLE
Changing `insert` mode language

### ISSUE THREAD

**Issue by c0ffeeartc** [vimperator/vimperator-labs#170]
I use Ubuntu 14.04 and it has a bug where non-latin keyboard layout breaks all hotkeys. So after each language switch I have to switch back to en_us to make vimperator respond.
Vim allows changing only `insert` mode language by `set keymap=russian_jcukenwin` and switching language in insert mode through `<c-^>`. This way system language is always en_us while `insert` gets different layout input.
Is there something similar for vimperator? May be calling a local script to change system language when entering/exiting `insert` mode?

Currently I made simple remap for letters, like:

    map д l
    map Д L

but multi combinations still require additional remaps with this method:
   
    <c-ц>р <c-w>h

**Comment by gkatsev** [comment]
Yeah, not sure there's much we can do about this other than having someone create the full-set of mappings.

**Comment by jwvim** [comment]
Try to write in your vimperatorrc file:
style -name commandline-ime chrome://* #liberator-commandline-command input {ime-mode: inactive;}

**Comment by c0ffeeartc** [comment]
Thanks, jwvim.
It has no effect.
Mapping hotkeys will do for now.

**Comment by c0ffeeartc** [comment]
Btw, vim has `InsertEnter`, `InsertLeave` autocommand-events.

If there were such events in vimperator it would be easy to run script on the user side and keep expected language.
