### ISSUE TITLE
Feature request: change statusbar text align

### ISSUE THREAD

**Issue by neg-serg** [vimperator/vimperator-labs#171]
Is there any way to align statubar text to the left like in vimperator2/pentadactyl? I've already tried showstatuslinks=2 but it's not exactly what I want. I want to see current url in the left side(after current mode indicator). How to implement this?

**Comment by neg-serg** [comment]
Changing "liberatorPosition" field in [common/content/liberator.xul] from -1 to 1 solved my problem:

<toolbaritem id="liberator-status" flex="10000000" liberator:highlight="StatusLine">
<spacer liberatorPosition="1" flex="10000000"/>

**Comment by lvii** [comment]
@neg-serg Is there a way to change url align to left by configration ?

**Comment by neg-serg** [comment]
>@neg-serg Is there a way to change url align to left by configration ?
No, as far as I know you should change xul files. I've tried to do it without any success

**Comment by c6parmak** [comment]
@lvii You can set width of the spacer in userChrome.css

    #liberator-status > spacer { max-width: 0px; }
