### ISSUE TITLE
Text entered into input fields appear as underlined

### ISSUE THREAD

**Issue by secondplanet** [vimperator/vimperator-labs#173]
Recently, when I have been typing things using Vimperator in Firefox, the text is underlined - is there any way to disable this feature?

**Comment by jamalis** [comment]
Gee thanks a lot, with the post above I became rather well-informed about the discussions.
http://fotorumahmewah.com

**Comment by gkatsev** [comment]
I've never experiences this myself nor do I think vimperator underlines text. Closing.
If you feel like this is still an issue can you try with the latest vimperator and firefox and report back exact versions and platforms used and also specific steps for reproduction? Thanks.

**Comment by secondplanet** [comment]
This actually turned out to be a problem on my system (happens in all applications in text input fields) that I mistook to be a part of vimperator. I was mistaken when I opened an issue here.

**Comment by gkatsev** [comment]
Ah, cool. No worries and glad you figured it out.
