### ISSUE TITLE
Ends up in ignore-all-keys mode

### ISSUE THREAD

**Issue by phlundblom** [vimperator/vimperator-labs#175]
Recently I end up in ignore-all-keys mode when switching between tabs. I get the impression the behavior starts after doing a search at google.com. After that, I usually always get ignore-keys mode when switching tabs even though the tab with the google seach tab is closed.

This is with Firefox 35.0.1, latest Vimperator plugin running on Windows 8.1.

**Comment by timss** [comment]
Do you have anything in `:ignorekeys list`?

**Comment by phlundblom** [comment]
I tried to add www.google.com to the list when experimenting without any success. Now I have a clean list.

**Comment by gkatsev** [comment]
Also, maybe some autocommand that goes into ignore-all-keys mode?

**Comment by philipp-classen** [comment]
I just had the same issue for several days. Each time I opened a tab, it switched to "ignore-all-keys" mode.

In my case, it turned out that I accidently added "st" to ignorekeys.
":ignorekeys list" showed "st" as an entry.
After ":ignorekeys remove st", the problem is gone.

**Comment by phlundblom** [comment]
I didn't have anything in set for ignorekeys. I was messing around a lot with different settings and in the end the problem was gone. I'm pretty sure it was a user fault caused by myself...

**Comment by fakedrake** [comment]
I had the same issue. `:ignorekeys list` gave `A` which presumably meant simething along the lines of *ignore everything*. `:ignorekeys remove A` fixed it, so far at least.

**Comment by Stebalien** [comment]
I'm hitting this bug on github and `:ignorekeys list` returns nothing. Unfortunately, I can't reliably reproduce. I just randomly end up in ignore all keys mode.

**Comment by Stebalien** [comment]
Nevermind... I've mapped the capslock key to escape and sometimes hit capslock while shifting.
