### ISSUE TITLE
winopen/tabopen/open does not work properly to navigate '//~~' url

### ISSUE THREAD

**Issue by nyaong** [vimperator/vimperator-labs#179]
```open //www.google.co.kr/robots.txt```

i just typed this command. the browser has been stopped.

in browser's location bar, '//www.google.co.kr/robots.txt' works perfectly.

**Comment by gkatsev** [comment]
For me, trying to navigate to `//google.com` ends up trying to open `file:///google.com` regardless of whether through vimperator or the awesome bar.

**Comment by gkatsev** [comment]
This is not a vimperator issue but a browser issue.
