### ISSUE TITLE
AMO is moving to a signed extensions

### ISSUE THREAD

**Issue by gkatsev** [vimperator/vimperator-labs#180]
Probably nothing to be done for us right now as more details have not come out yet. I believe the only real thing that we might need to do for this is figure out how to enable the alpha/beta XPIs (that aren't hosted on AMO) to work. But that will be in a future announcement.
https://blog.mozilla.org/addons/2015/02/10/extension-signing-safer-experience/

**Comment by SammysHP** [comment]
Just wanted to write the same.

The main issue is that you need a developer build of Firefox to install the add-on without sending it to Mozilla first. This is a huge drawback because I compile it myself with some small patches, but don't want to use a special build of Firefox. And it is annoying to compile the xpi first, then upload it via a web interface, wait, download it again etc.

I hope they'll implement some sort of local signing with own certificate that can be added to your Firefox installation.

**Comment by maxauthority** [comment]
I am quite sure there'll be some about:config setting for developers, but
they want the security for default users (which I actually understand and
is probably very useful).

**Comment by SammysHP** [comment]
> After the transition period, it will not be possible to install unsigned extensions in Release or Beta versions of Firefox. **There won’t be any preferences or command line options to disable this.**

**Comment by gkatsev** [comment]
We'll see what's there as more info is coming out and this is available.

**Comment by gkatsev** [comment]
Looks like you'll be able to disable the signed extension mandate in FF40.
```
xpinstall.signatures.required
```
Starting in FF41, the `about:config` option won't work in stable and beta versions of firefox, but nightly, aurora, and ESR will still accept it.
A good write-up of it: http://www.ghacks.net/2015/06/19/how-to-disable-the-firefox-40-add-on-signing-requirement/

**Comment by SammysHP** [comment]
Just tried to get a signed version of vimperator.

> The validation process found these issues that can lead to rejections:
>
>    Access to the `Function` global

So how can I get a signed version of vimperator with some custom modifications?

**Comment by SammysHP** [comment]
My signing request war rejected:

> Your version was rejected because of the following problems:
> 
> 1) Your add-on uses the 'eval' function, which is something we normally don't accept. There are many reasons *not* to use 'eval', and there are alternatives available. You can read more about it here: https://developer.mozilla.org/en/XUL_School/Appendix_C:_Avoid_using_eval_in_Add-ons
> 
> Please fix them and submit again. Thank you.

And now?

**Comment by Segaja** [comment]
Firefox nightly 42.0a1 (2015-08-05) just enabled the option mentioned by gkatsev above as default. It can still be disabled which lets me uses some addons again, but it has to be addressed soon.

**Comment by gkatsev** [comment]
@SammysHP thanks, hopefully, we'll get all those issues fixed up before signed extensions land in stable firefox.

**Comment by SammysHP** [comment]
I told the reviewer that the release version is already published on AMO. The response:

> Thank you for letting us know, I approved your add-on.

**Comment by gkatsev** [comment]
Closing this since it isn't really an issue. You can disable the signed extensions in Aurora for development.
