### ISSUE TITLE
gui=none leaves 1px line at the top

### ISSUE THREAD

**Issue by nagisa** [vimperator/vimperator-labs#182]
Line is especially visible in pages with dark background

**Comment by gkatsev** [comment]
Not sure that vimperator itself can do anything about that. It might need to be done in the custom styles css.

**Comment by nagisa** [comment]
I used
```
style browser #navigator-toolbox::after{height: 0 !important;}
```
to great effect.

**Comment by gkatsev** [comment]
Thanks for the comment. Glad you figured it out!

**Comment by Hund** [comment]
This does not work for me. :(
