### ISSUE TITLE
Using Vimperator with Programmer Dvorak

### ISSUE THREAD

**Issue by ooker777** [vimperator/vimperator-labs#184]
In Programmer Dvorak layout keyboard (image), numbers are on top of the row, you have to press Shift to add a number. Do you have any ideas not to use Shift when on Hint mode of Vimperator? (Others keys still keep normal.)

![enter image description here][1]

Note: this question is a duplication of my question [in Super User](http://superuser.com/questions/758118/using-vimperator-with-programmer-dvorak). I have also asked [in Google Group](https://groups.google.com/forum/#!topic/vimperator-labs/YdozM6fC3Gw) but it seems that noone cares. I have found [an email conversation](http://www.mozdev.org/pipermail/vimperator/2008-October/002372.html) but I have no idea how to follow it.
  [1]: http://i.stack.imgur.com/i0HmK.png

**Comment by klaplong** [comment]
Try another type of hint matching, like fuzzy. This lets you type the text of the link, instead of numbers.

**Comment by mina86** [comment]
set hintchars=htnsdgfcrlmwvzb-/@

is what I’m using.
