### ISSUE TITLE
Muttator stopped to work with Thunderbird 36

### ISSUE THREAD

**Issue by elfi** [vimperator/vimperator-labs#187]
After a recent beta release of Thunderbird 36 Muttator stopped to work for me. It does not complain about anything, but keybinding is simply not picked-up.

I am running on MacOs. Recompiling Muttator form sources did not help.

**Comment by maxauthority** [comment]
Do people on windows/Linux also have the problem?

**Comment by NgrNxk** [comment]
I have the same problem under Windows8.1:
Muttator:	1.2 (created: 2015/03/17 10:32:34)
Thunderbird:	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:36.0) Gecko/20100101 Thunderbird/36.0

I'm trying to mitigate it by something like this, but...
```javascript
map j :emenu<Space>Go.Next.Message<Return>
map k :emenu<Space>Go.Previous.Message<Return>
```

**Comment by maxauthority** [comment]
We certainly need some more Muttator maintainers, it just seems many core
developers prefer web mail nowadays, so we'll need somebody motivated to
look into these issues and I'd be very glad to apply all patches/pull
requests.

**Comment by maxauthority** [comment]
Can somebody test the current master and report if #213 fixed the issue? Then i'll close this issue.

**Comment by elfi** [comment]
Tested. All is OK in Thunderbirds 31.5.0, 36, 37 beta1. Thanks a lot.

**Comment by maxauthority** [comment]
Thanks @NgrNxk for the commit! Closing.
