### ISSUE TITLE
Crash firefox when running `:echo content.`

### ISSUE THREAD

**Issue by gkatsev** [vimperator/vimperator-labs#191]
I can *reliably* crash vimperator/firefox when running `:echo content.`, as soon as I type the `.` the browser crashes.

**Comment by gkatsev** [comment]
Using vimperator 3.8.3-a5 and firefox 35 on OSX.

**Comment by carlosreyes** [comment]
Reproducible on Vimperator: 3.8.3 (created: 2014/11/09 13:19:01)
Firefox: Mozilla/5.0 (X11; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0 on Arch.

**Comment by dkasak** [comment]
Reproducible on current master also, but I've found pages where it doesn't happen (it does on this one, though).

**Comment by aureooms** [comment]
see #159

**Comment by gkatsev** [comment]
Closing as a dupe of #159.
