### ISSUE TITLE
Double statusbar in Firefox 36

### ISSUE THREAD

**Issue by klaplong** [vimperator/vimperator-labs#193]
I installed Firefox 36 today, and now I'm seeing an extra bar below the Vimperator status bar. See the attached screenshot.

![double_bar](https://cloud.githubusercontent.com/assets/2972759/6392665/44139c18-bdc3-11e4-856e-36c96416c98d.png)

**Comment by gkatsev** [comment]
What version of vimperator are you using?

**Comment by klaplong** [comment]
I was running the previous version, but I just noticed the double bar is gone, so I'm going to close this.
