### ISSUE TITLE
downloads, help, addons, and extoptions do not open in a new tab

### ISSUE THREAD

**Issue by brianbuccola** [vimperator/vimperator-labs#194]
**Command:** `:downloads` (or `:addons`, `:extoptions`, or `:help`)

**Expected behavior:** downloads dialog opens in a _new_ tab (and the new tab is _activated_, if `set activate=downloads` is set, which by default it is).

**Actual behavior:** downloads dialog opens in the _current_ tab.

The following all properly open in a new tab: homepage (`gH`), quickmark (`gn`), tabopen (`:tabopen[!]`), and paste (`P` and `gP`). But the following do _not_ open in a new tab: addons (`:addons`), downloads (`:downloads`), extoptions (`:extoptions`), help (`:help`). These all open in the current tab.

The reason that downloads, addons, extoptions, and help are all expected to open in a new tab is that they can all in principle be _activated_ with the `'activate'` option.

**Comment by maxauthority** [comment]
Yes, the consistency of what to open in a new tab, and what not is really
consistent yet. And yes, probably just opening (and activating) these
things in a new tab just is the best thing which we should do (why does
anyone want to open :downloads in a background tab?).

For now at least you can do :tab downloads   to open that thing in a new
tab.

(gH and gn don't really count, as that are just variations of the gh and go
commands doing the same in the current tab).

**Comment by timss** [comment]
Trying to 'resolve' this old issue.

Am I misunderstanding anything here, or isn't this already decided and configured by the `newtab` option anyway? By default it is empty, but some keybindings such as `C-S-a` or certain commands like `:preferences` already open a new and activated tab. Current `:addons` behavior does not match official keybinding.

How about changing it to include addons, downloads, and help by default? If not, let's close this issue.

**Comment by timss** [comment]
No response, use `newtab` option for now.
