### ISSUE TITLE
<C-Q> in Vimperator for selecting rectangular regions in Vimperator?

### ISSUE THREAD

**Issue by llinfeng** [vimperator/vimperator-labs#195]
Upon entering CARET mode by pressing `c`, I find that `<C-Q>` does not trigger a "VISUAL BLOCK", as would have happened in Vim for selecting a rectangular area.

Had the "VISUAL BLOCK" function been implemented but was mapped to another key-binding? If so, please point me to the function that triggers "VISUAL BLOCK".

I was trying to select a certain column in a table on the webpage. Any thought on this? Or, had there been utilities (functions implemented in Vmiperator) that could help with selecting contents from tables on webpage?

Thank you.

**Comment by gkatsev** [comment]
Not sure we can do block selection in the browser.

**Comment by llinfeng** [comment]
Thank you all as well!

**Comment by maxauthority** [comment]
As Gary pointed out, block selection (neither of HTML content, nor of text
in textareas) cannot be done. While it might be cool, it is incredibly
complex and CARET mode in general is so broken to be really usable in the
modern world of web pages. (Alone the nearly invisible CARET, so if one
improved CARET mode, he'd probably start with the basics like finding (or
positioning) the cursor first).

**Comment by dkasak** [comment]
Somewhat related: I've found [this plugin](https://github.com/vimpr/vimperator-plugins/blob/master/caret-hint.js) to work quite well for enabling me to use caret mode more efficiently. It adds several extended hint modes which allow you to position before or after an element, optionally selecting the contents within (so you can yank it). This might be similar to what you're trying to achieve with your suggestion.

**Comment by maxauthority** [comment]
Probably (I haven't used that), but I still doubt that it'll work well for
all obscure web pages which just haven't been built with caret navigation
in mind. And also it doesn't fix one of the other main problems - the
really bad visibility of a little black, thin caret on a large screen and
complex web page.

**Comment by gkatsev** [comment]
Closing since there isn't much we can do plus there's the plugin which tries to make life better in caret mode.
