### ISSUE TITLE
Enhancement:  add digraphs capability as in vim

### ISSUE THREAD

**Issue by mrwessel** [vimperator/vimperator-labs#196]
In vim it is easy to add special characters with `:digraphs`, for example: `^k ss` generates a German double-s character (esszet; looks sort of like a capital B).  I would like to see this in vimperator as well; it does not appear that `^k` is currently used for anything.

**Comment by ropez** [comment]
I was also thinking about this. Maybe this could be implemented as a plugin.

However, I found that it's actually possible to do this already, only using simple mappings:

```
:imap <C-k>ss ß
:imap <C-k>aa å
:imap <C-k>AA Å
```

**Comment by klaplong** [comment]
Why not setup Compose Key? You can type any Unicode characters with that.

**Comment by gkatsev** [comment]
Going to close this since you can it via mapping as @ropez stated.
Perhaps someone can make a plugin for it.
