### ISSUE TITLE
Undo no longer works in latest master

### ISSUE THREAD

**Issue by Tranquility** [vimperator/vimperator-labs#198]
I just tried the master and undo (open the last closed tab) does throw some weired error message about an untracked window. The 3.9 release does not have this problem.

**Comment by SammysHP** [comment]
Additionally I can't open links in new tabs (via middle mouse button or ctrl+click) and back/forward buttons aren't working too.

**Comment by SammysHP** [comment]
And I can't open the developer tools in Firefox anymore.

**Comment by SammysHP** [comment]
Fixed by reverting f28e7be.

**Comment by maxauthority** [comment]
Thanks for investigating the issue, I reverted #154 until this issue can be fixed.
