### ISSUE TITLE
Unable to use the Follow Link feature

### ISSUE THREAD

**Issue by MaikoID** [vimperator/vimperator-labs#199]
Hey guys my vimperator suddenly stopped to work properly out of blue.

Now I'm unable to use the f/F key to follow links, making the plugin useless. How can I fix it or properly attach debug logs ?

I already restarted the Fifrefox and did a vimperator update too from the web site without success.

BR

**Comment by gkatsev** [comment]
What version of vimperator are you using? I believe this has already been fixed in vimperator 3.9 (which is awaiting AMO to put it out officially).

**Comment by MaikoID** [comment]
The latest one, I presume: https://github.com/vimperator/vimperator-labs/releases/download/vimperator-3.9/vimperator-3.9.xpi

Firefox: Mozilla Firefox 35.0.1

**Comment by MaikoID** [comment]
Update: I disable all ubuntu/unity default add-ons for firefox. And reinstalled the vimperator plugin from the link above.

For now its working but is kind of slow, and the highlight is a bite slow to drawn.

Ubuntu 14.04 x64
