### ISSUE TITLE
Ability to change focus between parts of sites

### ISSUE THREAD

**Issue by wldcordeiro** [vimperator/vimperator-labs#200]
Maybe this is something I haven't been able to figure out and is part of Vimperator already. But I'd like to be able to change the focus on sites that have multiple scrollable elements like the site in the screenshot.

Currently, when you load something like this the first element will have your focus and you have to click in the other to be able to move around it.
![screen shot 2015-03-04 at 01 50 22](https://cloud.githubusercontent.com/assets/580982/6480427/d93e1c9a-c210-11e4-9c09-6aa2216bef42.png)

**Comment by gkatsev** [comment]
You can use vimperator to select frames using `]f`, I think.

**Comment by wldcordeiro** [comment]
@gkatsev Trying that on the site I screenshot doesn't seem to work. http://doc.rust-lang.org/book/hello-world.html

**Comment by c0ffeeartc** [comment]
If frame has visible links `;;` may work.
 Works for me on that site.

**Comment by c0ffeeartc** [comment]
Here is a hack solution.
 Thanks to [stackoverflow](http://stackoverflow.com/questions/5572540/how-to-right-click-in-vimperator), I've found `keynav`.
 It works by hitting `<c-;>` and places giant crosshair over all screen, pressing `hjkl` moves it and teleports mouse cursor into its center. Then it's possible to perform left click and focus whatever is under the cursor.

The best part of it, **it can steal focus from Flashplayer** !

**Comment by demokritos** [comment]
"Focus frame" was working, but now is not working. By `;f`, I could change focus between frames. Maybe since 3.10, `;f` shows "Focus frame" for very short time and disappears.

**Comment by demokritos** [comment]
I found out a workaround. If you search a text existing only the desired division, the division is focused.

**Comment by gkatsev** [comment]
Theoretically, we could look for scrollable elements in the current viewport and allow you to focus between them with some command. This isn't an easy thing but we'll definitely accept a PR for this.
I'm going to close this as we're unlikely to implement that ourselves, unfortunately.

**Comment by AakashMallik** [comment]
I don't know how they are doing it, but VimFX gives this feature... they have a separate key combo just to focus on different elements...
