### ISSUE TITLE
<C-v> <C-c> Copy deselects text

### ISSUE THREAD

**Issue by Jefftree** [vimperator/vimperator-labs#202]
The command to copy text works, but the highlighted text is deselected after <C-c> is pressed. Is there a way to keep the selected text highlighted?

Vimperator 3.8.3-a5, Firefox 38

**Comment by maxauthority** [comment]
Right now, no. It's mostly done for vim compatibility which also deselects
the text on "y"ank. Probably adding "gv" to restore the selection might be
a good idea, but why do you need to keep the text selection after copying?
Or do you keep the selection as a visual reminder where you are?
