### ISSUE TITLE
make :edit and :tabedit be an alias to :open and :tabopen

### ISSUE THREAD

**Issue by Mizuchi** [vimperator/vimperator-labs#205]
in vim we use :edit and :tabedit to open a new tab, to keep the consistency I would suggest to make :edit and :tabedit be an alias to :open and :tabopen

**Comment by maxauthority** [comment]
That was discussed a few years ago, but as we are only inspired by Vim, and
not a 100% clone, we decided against such aliasing, alone that the tab
completions are cleaner. That said, we still have lots of old craft here,
but I don't want to introduce new ones.
