### ISSUE TITLE
"Search suggestions" interrupts input method

### ISSUE THREAD

**Issue by JasonXJ** [vimperator/vimperator-labs#207]
When I use the search command "S", the "search suggestion" will be updated every time I type something. And the update will keep interrupting my input method (Fcitx). I have to wait until the update is finished.

You can see the phenomenon in the following gif (Fcitx was activated the whole time).
1. First I used command "S" to invoke searching
2. I typed "hello" and then press ENTER so that "search suggesting" started to be updated
3. I typed "world" before the update was finished. You can see that the Fcitx input window was flashing because it was interrupted and all the input disappeared.
4. After the update was finished, I was finally able to type "world".

![gif](https://cloud.githubusercontent.com/assets/6949499/6664376/40583002-cc23-11e4-9610-e6314cdd35d9.gif)

BTW, I am using version 3.9 (and this bug also exists in older version)

**Comment by maxauthority** [comment]
As I am not Chinese/Japanese where I have clues about how those input
methods work in detail, I can't really help you here. I just know that
Japanese build the 2nd largest group of vimperator users and I have not
heard of any problems with input methods. Mayby fcitx does something
different than other IMEs?

**Comment by timss** [comment]
In an effort to clean up old and unconfirmed issues I'm closing this one.

If it's still present please notify me and I'll reopen it and investigate further. Thanks!
