### ISSUE TITLE
Link to plugins on the homepage is wrong / new place for plugins?

### ISSUE THREAD

**Issue by blueyed** [vimperator/vimperator-labs#210]
The [homepage](http://www.vimperator.org/vimperator/) links to http://code.google.com/p/vimperator-labs/issues/list?can=2&q=label%3Aproject-vimperator+label%3Atype-plugin - which isn't correct anymore.

Is there a new place for the new plugins?

**Comment by gkatsev** [comment]
Most of the plugins are available in the vimpr repo: https://github.com/vimpr/vimperator-plugins/

**Comment by maxauthority** [comment]
Thanks for the info! I updated the vimperator.org homepage with a link to
the "vimpr" repository (and removed all links from the Muttator page as we
don't really have a place for muttator plugins anymore). Thanks all of the
plugin authors for their work there (although I guess one author should
also change the

Note: Master is valid only for versions Firefox 19.* and lower.
<https://github.com/vimpr/vimperator-plugins#for-versions-firefox-20-and-higher-please-check-the-branch-36-here>For
versions Firefox 20.* and higher, please check the branch 3.6 here
<https://github.com/vimpr/vimperator-plugins/tree/3.6>

in the README.md there, as it doesn't seem to be correct anymore.
