### ISSUE TITLE
blank landing page and ctrl-k focus changed

### ISSUE THREAD

**Issue by sberney** [vimperator/vimperator-labs#216]
With and only with vimperator enabled, even in pass through mode (&lt;S-esc&gt;), ctrl+k does not focus the search bar, but instead a search box on the landing page. (Preferences: home page is set to blank.) Even if I change the blank page to be truly blank via the little gearbox, if I press ctrl+k I will get a page with the large firefox icon, with the focus in a search box below the icon that I do not care for. ctrl+k should focus the search box next to the url address.

If this is not a bug, how can I disable this?

Also, I still like using ctrl+t tab to go to that search box, but with and only with vimperator enabled, tab does nothing of the sort, even in pass through mode. I can't stand this ("t google " is a lot longer than &lt;C-t&gt;&lt;Tab&gt; or &lt;C-t&gt;&lt;C-k&gt;, and old habits die too hard for this business).

**Comment by gkatsev** [comment]
I think this might be a default functionality for firefox. I have the search box removed from the toolbar and `<c-k>` brings me to the search page but when it's in the toolbar `<c-k>` focus on search, as it should.

Also, you should check out `:h 'defsearch`, it allows you to set a search engine and then when you use `:tabopen` or `:open` (via `t` or `o`), you can just type your query in.

Also, you could probably do something like
```vim
map <c-k> <Nop>
```
to disable the key combo. I think it'll work.

**Comment by sberney** [comment]
When I disable vimperator, and/or when I disable all add-ons, none of what I described occurs, and the focus is _always_ to search.

map &lt;c-k&gt; &lt;Nop&gt; does not seem to change the behavior.

**Comment by gkatsev** [comment]
`:map <c-k> <Nop>` prevents me from going to the search page when pressing `<c-k>`.

**Comment by qeatzy** [comment]
try keybinder, [https://addons.mozilla.org/de/firefox/addon/keybinder/](url), I just use that to disable <C-k> and <C-j>.
