### ISSUE TITLE
Update URLs in help messages in Japanese locale

### ISSUE THREAD

**Issue by afukumoto** [vimperator/vimperator-labs#217]
commit dd0c8866e171b2baa591dfbcb152c19c5dd44a4e updates the URLs in the help message and now I know where to report the issues, but the Japanese locale messages need update as well.

**Comment by maxauthority** [comment]
Yeah, keeping such things up-to-date always is/was my main problem with
having localized docs. But good there is a bug report now, so maybe the
Japanese docs maintainer sees it.
