### ISSUE TITLE
Some toolbar menus and popus don't work when navigation bar is hidden

### ISSUE THREAD

**Issue by maki57** [vimperator/vimperator-labs#218]
When clicking some buttons of Firefox's menus or extensions placed on any of the toolbars, their menus don't pop up when the navigation bar is hidden with `set gui=nonavigation`. Here are some examples of Firefox menus and extensions on either the tabs bar (top) or on the bookmarks toolbar (bottom) for instances where they work or don't work with or without the navigation bar:

#### Firefox Menus
**Downloads w/ Location Bar**
![downloads-bar](https://cloud.githubusercontent.com/assets/11873511/7071059/776cf2c6-df15-11e4-8aac-6a4668785afa.png)
Works

**Downloads w/o Location Bar**
![downloads-nobar](https://cloud.githubusercontent.com/assets/11873511/7071064/7e3da1c2-df15-11e4-803f-cb78ea793bb2.png)
Works

**Developer Tools w/ Location Bar**
![devtools-bar](https://cloud.githubusercontent.com/assets/11873511/7070983/0520f3a2-df15-11e4-8ce1-e34bf097a7c3.png)
Works

**Developer Tools w/o Location Bar**
![devtools-nobar](https://cloud.githubusercontent.com/assets/11873511/7071018/4354095c-df15-11e4-94b0-07da1cc9d389.png)
Doesn't Work

#### Extensions
**Privacy Badger w/ Location Bar**
![privacy badger-bar](https://cloud.githubusercontent.com/assets/11873511/7071070/8224cf7c-df15-11e4-9053-71fac5b00fbe.png)
Works

**Privacy Badger w/o Location Bar**
![privacy badger-nobar](https://cloud.githubusercontent.com/assets/11873511/7071081/99717464-df15-11e4-8b7f-e869e7dde6ce.png)
Works

**uBlock w/ Location Bar**
![ublock-bar](https://cloud.githubusercontent.com/assets/11873511/7071082/99751416-df15-11e4-92eb-d63de866846c.png)
Works

**uBlock w/o Location Bar**
![ublock-nobar](https://cloud.githubusercontent.com/assets/11873511/7071085/9e0d00c4-df15-11e4-9f58-818dd31d3058.png)
Doesn't Work

Using `set gui=navigation` to bring back the navigation bar allows the menus to work again (what I did for the examples). I also get weird behaviour concerning the "Downloads" button because it sometimes works with or without the navigation bar (like the pictures above), or doesn't work completely as long as Vimperator is on.

Disclosure: I made a similar issue for 5digits/dactyl and used the same images for this post since the outcome for both is the same.

**Comment by IGI-111** [comment]
I have that exact same issue, with uMatrix in particular, clicking it doesn't show anything unless I `set gui=navigation`.

**Comment by tobimpub** [comment]
from https://github.com/gorhill/uBlock/issues/112#issuecomment-95848638:

`style -name ublock * #nav-bar * { visibility: visible ; }`

in .vimperratorrc, fixes the issue.
It fixes Developer Tools as well.

**Comment by maki57** [comment]
That did it.

**Comment by timss** [comment]
Unfortunately this seems to reintroduce focus issues with `about:newtab` if you use `set focuscontent`. 

That is, if a new tab is opened with `#nav-bar * { visibility: visible ; }`, the navigation bar will be given focus until the page is fully loaded (and content is focused), which may be slower than whatever keybind you want to press on your new tab. Especially noticeable with many tabs or slow machines.

Not really a proper solution, but a possible workaround due to the "slow" design of `focuscontent` one may use `LocationChange` to trigger <kbd>ESC</kbd> as such:

    autocmd LocationChange about:newtab <ESC>

This is more or less instant, although you'll still see "INSERT" in the vimperator bar for a split second.

**Comment by JanusDC** [comment]
@timss The workaround with autocmd does not work for me. Do not know why.

**Comment by timss** [comment]
Did you `set focuscontent` ?

**Comment by JanusDC** [comment]
That did the trick. Thanks
