### ISSUE TITLE
Question: One step ":buffer or :tabopen"

### ISSUE THREAD

**Issue by ropez** [vimperator/vimperator-labs#224]
Is there a way to tell vimperator to go to a given URL, and have it open the existing tab if it exists, and otherwise open it in a new tab?

I would very much appreciate such a feature, because I tend to do this all the time for application-like web pages like Gmail and PivotalTracker:

1. Try to switch to existing tab: `:b name`
2. If not found, press escape, and then `:tabopen url`

**Comment by jwvim** [comment]
" open url a, url b, url c at same time.
map gq :tabopen url a, url b, url c<CR>

" switch between application-like web pages like Google Canlenda, Gmail and PivotalTracker( links below is for example)
map gc :buffer! google.com/calendar<Tab><CR>
map gw :buffer! wx.qq.com<Tab><CR>
map gs :buffer! weibo.com<Tab><CR>

" <C-6> Select the previously selected tab. This provides a quick method of toggling between two tabs. 
map ge <C-6>

with these settings, when you browse in <page a>, press <gc>, you weill go to <google canlendar>, and when you finished checking your schedule, press <ge>, you will go back to <page a>

**Comment by ropez** [comment]
Yes, I know all of these commands, but none of them answers the use case that I was trying to explain.

I have all GUI elements disabled. As I'm writing this, is says in the bottom corner that I have 75 buffers, or "tabs" in my buffer list (`:ls`). I _don't remember_ whether I have Gmail there or not. So if I would like to open Gmail right now, even with those mappings, I would have to try and fail. First the `:buffer` mapping, if that fails then the `:tabopen` mapping. And I would need one `:tabopen` mapping for each application, because I don't know if I have the other two open either.

In vim (the real vim), assuming `set buffer` is enabled, when I issue an `:edit` command it behaves exactly like I want. If I have the file open in another buffer, it gives me that buffer. If I don't have it open, it creates a new buffer. This ensures that I never end up with the same file more than once in my buffer list. Of course web pages are different than files. Sometimes you want to open one site several times. But sometimes you don't, and I would like to be able to create a command/mapping that behaves exactly like that.

Note: I don't want to complain or anything. I've been using this extension for a long time, and I'm very thankful for it. I'm just suggesting something that I think is currently not possible with it. I might be able to help out, if this is agreed to be something useful.

**Comment by jwvim** [comment]
There was a plugin named 'opener.js' could satisfy your requirement.

But it seems doesn't work on the newest vimperaotr

please check:
vimperator-plugins/opener.js at master · vimpr/vimperator-plugins
https://github.com/vimpr/vimperator-plugins/blob/master/opener.js

**Comment by ropez** [comment]
Ah, nice. I will definitely have a look at that. Closing this now, as I agree that this is probably something that is best implemented as a plugin.
