### ISSUE TITLE
Using 'd' to close tab moves you to the next tab, not the tab you were on last

### ISSUE THREAD

**Issue by mrapogee** [vimperator/vimperator-labs#225]
When you close a tab in Firefox, it directs you to the last tab you were on. But it doesn't do this with vimperator tab close. This is extremely useful since it means you can go `:tabopen search`, find answer, `d` and your back to where you were.

**Comment by sclarke** [comment]
I added `nmap d :bdelete<Space>-select<Space>lastactive<CR>` to my `.vimperatorrc` file to address this. It works well, although it doesn't make as much sense in sessions with tabs restored.

**Comment by gkatsev** [comment]
An easier map is just `:map d <c-w>`. `d` and `D` are currently set up to go to the right and left tabs respectively. I generally use `<c-w>` directly when wanting the "go to last tab" thing.

**Comment by mrapogee** [comment]
Okay. For some reason <c-w> doesn't make a difference, but @sclarke your suggestion worked. Thanks!

**Comment by gkatsev** [comment]
Closing since there's a work-around.
