### ISSUE TITLE
Increase z-index for hints

### ISSUE THREAD

**Issue by rr-** [vimperator/vimperator-labs#226]
I started using vimperator yesterday and when I visited Youtube, I discovered that hints don't appear at the top of the page - the elements are highlighted, but the numbers are missing. After playing for a while I found out the reason - Google adds following ridiculous CSS rule to the top bar:

    #masthead-positioner {
        z-index:1999999999;
    }

To counter this I added to my `.vimperatorrc` following fix:

    highlight Hint -append z-index:2999999999

Now the hints on Youtube appear as intended. At the same time this also fixes some issues with Gmail.

While this worked in my case, I believe Youtube and Gmail are popular enough to include similar fix upstream.

**Comment by gkatsev** [comment]
Yay, z-index war :/

But yeah, we probably should do something about it.

**Comment by Evidlo** [comment]
See https://github.com/vimperator/vimperator-labs/issues/255

**Comment by Evidlo** [comment]
#255 has been merged.  This issue should be closed.
