### ISSUE TITLE
Opening tabs next to current one

### ISSUE THREAD

**Issue by rr-** [vimperator/vimperator-labs#227]
I checked `:helpall`, `:set all` and all the issues, and looks like this isn't yet supported nor has it been reported before, with exception of [this pull request](https://github.com/vimperator/vimperator-labs/pull/95):

When I open a tab using `:tabopen`, it appears as the last tab.
When I open a tab using hints, it appears near the current tab.

It would be desirable to have this behavior configurable, especially considering that having TabMixPlus installed, the Firefox's <kbd>Ctrl</kbd>+<kbd>T</kbd> is inconsistent with Vimperator's `t URL`.
Unfortunately I see no way of implementing this in `.vimperatorrc` alone.

**Comment by doomikus** [comment]
Did you ever find an answer for this issue?  I'd like to do the same.

**Comment by rr-** [comment]
Nope, I kind of got used to the default behavior.

**Comment by blu2lz** [comment]
https://addons.mozilla.org/de/firefox/addon/open-tabs-next-to-current
works with vimperator

**Comment by gkatsev** [comment]
@blu2lz thanks for the tip.

**Comment by ratijas** [comment]
+1 thanks.

**Comment by derenio** [comment]
You can always define your own function that will do just that.
Put this into your `.vimperatorrc`:
```vim
javascript <<EOF
	function tabnextto(url) {
		let n = gBrowser.tabContainer.selectedIndex;
		liberator.execute(':tabopen ' + url);
		liberator.execute(':tabmove ' + (n + 1));
	}
EOF

command! tabnextto -nargs=1 :js tabnextto('<args>')
```

Usage:
```vim
:tabnextto example.com
```

To remap `t` from `tabopen` to `tabnextto` use:
```vim
:nnoremap t tabnextto<space>
```

**Comment by llinfeng** [comment]
@derenio I found a "bug" in your code: if I supply the following query right next to the `:tabnextto` command, I will see this error message "Trailing characters". Is there a quick fix to this?
* The query that gets me error: `:tabnextto site:example.com keywords`.
* Currently, the newly defined command can only handle strings. If I improve the query to `:tabnextto "site:example.com keywords"`, I will get a new tab, but the query sent to my default search engine is, exactly, the string `"site:example.com keywords"` (double-quotes included).

**Comment by Koushien** [comment]
The `-nargs=1` denotes that tabnextto only accepts 1 argument.
For a "quick fix", you can change it to `-nargs=*` to accept any number of arguments, remove the url parameter and replace the lookup to url with [].slice.call(arguments).join(' ');
e.g.,
```
javascript <<EOF
	function tabnextto() {
		let n = gBrowser.tabContainer.selectedIndex;
		liberator.execute(':tabopen ' + [].slice.call(arguments).join(' '));
		liberator.execute(':tabmove ' + (n + 1));

command! tabnextto -nargs=* -complete=url :js tabnextto('<args>')
	}
```

**Comment by llinfeng** [comment]
@Koushien Glad to find that the quick fix worked! Also, I found the Javascript solution is **neater** than the Add-on solution.
1. **Speed**: in creating a new tab right next to the current tab, the newly defined function does the job immediately, but the Add-on seems to burden the browser with one additional step --- a new tab is first created at the farthest right location, and then *moved* to the ideal slot. One can even notice such tab-movement visually, if his/her computer is as slow as mine :)
2. **Order**: internal to Vimperator, tabs are ordered as buffers and are thereby enumerated by the order as shown in the "tab-line" (the GUI compartment defined as `set gui=tabs`). Only tabs created through the Javascript approach is correctly *inserted* to the buffer list. If one were to create a new tab through the Add-on approach, the new tab shall remain at the bottom of the buffer list. [To check the buffer list, use `:buffers` command.]
    * The Javascript approach maintains the functionality of tab-navigation: `:tabnext` and `:tabprevious` are essentially switching to the next/previous buffer in the buffer-list.

PS: The "Add-on" solution as mentioned in the previous discussion ---- https://addons.mozilla.org/de/firefox/addon/open-tabs-next-to-current/

**Comment by derenio** [comment]
@Koushien thanks for pointing out the `-nargs=*`.
About your solution, the part with `[].slice.call(arguments).join(' ')` isn't necessary. The `<args>` are passed as a single string; e.g. `:tabnextto a b c` will result in calling the corresponding `js` as `tabnextto('a b c')`.

I've considered the `-nargs=*` solution but I totally forgot about the usage of the `search keywords` and thought it's useless to mention because the `-complete=url` seems to be working only on the last argument. If I try to go to a github repository I'm working on I might type:

    :tabnextto git saleor<tab>

but it changes into:

    :tabnextto git https://github.com/mirumee/saleor

Perhaps someone know how to make `-complete=url` act as the one from `:open` that uses all the arguments?
