### ISSUE TITLE
How can I disable the special tratement of comma in command-line?

### ISSUE THREAD

**Issue by llinfeng** [vimperator/vimperator-labs#232]
Based on my elementary observation, when I use the search function in Vimperator through pressing `o` followed by `search-pattern`, `,` (comma) will play a role of search-separator. Let `search-pattern` be a string, `,` is like a parser that truncate the search pattern into several pieces.

If there a way to stop this treatment of comma?

Had I been asking the question in the wrong place, please point me to the right one. 

Thank you!

All the best, 

-Linfeng

**Comment by gkatsev** [comment]
Check out the `'urlseparator'` (`:h 'urlseparator') setting. It has comma by default. You probably want to remove the comma from it.
Going to close this, but feel free to ask more questions, if you have any.

**Comment by llinfeng** [comment]
Hi @gkatsev, I tried to use `set` and `let` to specify the values for `'urlseparator'`, but none of the following specifications solved the problem as you have described. Could you provide a sample for not "setting the `'urlseparator'` as an empty string"?
````
let 'urlseparator' = ""
set 'urlseparator' = ""
let urlseparator = ""
set urlseparator = ""
````

Thanks!

**Comment by llinfeng** [comment]
Update: I typed the following in command-line of Firefox, and it worked. 
```set urlseparator =```

Specifying settings in `_vimperatorrc` would only lead to the display of values of `'urlseparator'`. This is abnormal though. It seems that Vimperator is sourcing a hidden directory/file upon starting Firefox.
