### ISSUE TITLE
no select all answer for vimperator on firefox?

### ISSUE THREAD

**Issue by skinnywonderfulman** [vimperator/vimperator-labs#233]
This is my major complaint with using vimperator.  I remember being able to change my key  bindings before easily on Ubuntu but I'm having trouble with Windows.  Do we still have to create a file? What text to we put in it to remap Ctrl+A?

**Comment by Griffinhart** [comment]
Just to clarify, you want to use ^a to select all text in a text-entry dialogue, right?

>What text to we put in it to remap Ctrl+A

```
:inoremap <C-a> <Insert><C-a><Insert>
:mkv!
```

Or just add `inoremap <C-a> <Insert><C-a><Insert>` to your _vimperatorrc.

(If you want a "select all text in page" command, I *think* that's `noremap <C-a> <Insert><C-a><Insert>`, but I'm not 100% sure.)

**Comment by skinnywonderfulman** [comment]
sorry I've perused several threads on this topic before and I've never understood what "^a" stands for. I'm assuming it stands for insert+a?  What is the text mkv? Also where is the vimperatorrc file located in Windows? Can't seem the find the location anywhere.  Thanks!

**Comment by maxauthority** [comment]
^a means ctrl-a.

:mkv!

is a command which you can enter on the the commandline to automatically
save the current settings to the file, so you don't have to search for it
yourself.
