### ISSUE TITLE
Page turns blank after beeing displayed

### ISSUE THREAD

**Issue by thorondev** [vimperator/vimperator-labs#235]
I have some issues when opening this url with Vimperator enabled:
https://www.opengl.org/sdk/docs/man2/xhtml/gluSphere.xml

The page opens, shows up for half a second and then dissapears. I can still see the page structure in Firebug, but nothing is rendered.

I am on Arch Linux with Firefox 38.0.1, Vimperator 3.9.1 and also tried a new profile with only Vimperator installed. The problem occures as soon as I enable Vimperator. I can also remember seeing this bug 2-4 years ago (same page, Firefox+Vimperator).
I also tried another Firefox on Ubuntu - same bug.
All pages linked from here seem to cause the issue: https://www.opengl.org/sdk/docs/man2/xhtml/ - but this page itself is visible.

One more note: If I reload, focus Firebug or the built in inspector from Firefox, and then reload again, the page stays visible. Reload: still visible. Click into the page (removing focus from Firebug), then reload: invisible again.

And one more thing I just discovered: If I open the 'broken' page and switch to another page before it vanishes (or open it in another tab without switching to it), it always stays visible. So it seems to break if the page has focus and finished rendering - (and I have a little workaround).

**Comment by gkatsev** [comment]
Super weird. The page is loading fine for me with ff 38 and vimp 3.9 on osx.

**Comment by kminh** [comment]
I would like to second this as well. One thing I notice is that it happens with XML files that have a stylesheet attached.

**Comment by gkatsev** [comment]
This seems to be working fine in latest firefox and vimeprator.

**Comment by thorondev** [comment]
I can confirm this on FF 43.0.4 and Vimperator: 3.10.1.1. Thank you very much.
