### ISSUE TITLE
No hints for <area>s

### ISSUE THREAD

**Issue by sandwm** [vimperator/vimperator-labs#236]
Since a few weeks vimperator doesn't show hints for `<area>` tags. `_isVisible` in common/content/hints.js returns `false`, because `<area>` tags get computed style `"display: none"`, even if the image is visible and you can click the area-link.

A workaround is to modify [line 279 in hints.js](https://github.com/vimperator/vimperator-labs/blob/master/common/content/hints.js#L279) to read
```javascript
if (elem.nodeName.toLowerCase() != "area" && (computedStyle.getPropertyValue("visibility") != "visible" || computedStyle.getPropertyValue("display") == "none"))
```

Test cases:
http://wiki.selfhtml.org/extensions/Selfhtml/example.php/Beispiel:HTML_img-Element2.html
http://ars.userfriendly.org/cartoons/?id=20150613

I'm using Firefox 38.0.1 on Arch Linux. The bug does not occur in Debian 7 with Iceweasel 31.7.0 where the `<area>`s get `"display: inline"`:
```javascript
window.content.document.defaultView.getComputedStyle(document.getElementsByTagName("area")[0], null).getPropertyValue("display")
```

I'm not sure whether this is actually a bug in vimperator or in Firefox. See also old Mozilla [Bug #616333](https://bugzilla.mozilla.org/show_bug.cgi?id=616333).

**Comment by maxauthority** [comment]
This will unfortunately also yield in (many?) false positives. And in the
first example with the map, does the "hack" really put a link on each city?
When I tried the link, it seems I can click on each city, so just having
one hint would be too little.

**Comment by sandwm** [comment]
I'm using the workaround since I posted it and it's working without any issues so far. There is a link / hint on each clickable city in the first example.

Regarding the false positives: It seems like Firefox itself doesn't really care about "visibility" or "display" on an `<area>` tag. Even if you explicitly try to hide one, it is still used as a link. But I think this isn't very surprising, because the actual visible element is the `<img>` itself and not the `<area>`.

You might want to try some sample HTML. This places three links / areas on "Koblenz", "Wiesbaden" and "Mainz" (top left in the picture) and assigns the style "visibility: hidden", "display: none" or even both. But in any case you can click the "invisble" areas even in a vanilla Firefox and it will follow the link.
{{{html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="UTF-8">
    <title>area visibility</title>
</head>
<body>
    <p> 
        <img src="http://wiki.selfhtml.org/images/5/5e/Karte-deutschland-sw.jpg" width="690" height="582" alt="Karte" usemap="#Landkarte">
        <map name="Landkarte">
            <area shape="rect" coords="11,10,80,46" href="http://www.koblenz.de/" alt="Koblenz" title="Koblenz" style="visibility: hidden; display: none">
            <area shape="rect" coords="97,77,175,116" href="http://www.wiesbaden.de/" alt="Wiesbaden" title="Wiesbaden" style="display: none">
            <area shape="rect" coords="112,119,176,152" href="http://www.mainz.de/" alt="Mainz" title="Mainz" style="visibility: hidden">
        </map>
    </p>
</body>
</html>
}}}

So showing hints on "invisible" areas would be consistent with Firefox's current behavior.

**Comment by maxauthority** [comment]
Can you provide a pull request (with a comment just before line 279 which
links to the bug report or a description why we handle areas differently)?
Then I'll merge it, if nobody objects.
