### ISSUE TITLE
A command to start reader view

### ISSUE THREAD

**Issue by xuhdev** [vimperator/vimperator-labs#238]
The latest firefox has added a reader view feature:

https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages

Maybe we can add a command to start reader view?

**Comment by gkatsev** [comment]
Maybe a key command behind `g` or something. `gr`?
Anyway, meanwhile, you can use `:emenu`.
```
:emenu View.Enter Reader View
```
on a page that can be put into Reader View.

**Comment by xuhdev** [comment]
Yeah, `gr` would be good.

**Comment by maxauthority** [comment]
Yeah, gr sounds the most reasonable shortcut. But as always for new
features, it requires docs and a NEWS entry.

**Comment by Geraint** [comment]
I added this to my .vimperatorrc

    no gr :emenu View.Enter Reader View<CR>
    no gR :emenu View.Close Reader View<CR>

`gr` now turns on Reader View, and `gR` turns it off.

**Comment by gkatsev** [comment]
If someone PRs `gr` to toggle reader view, we'll accept that PR.

**Comment by gkatsev** [comment]
Added in latest vimeprator.
