### ISSUE TITLE
<P> and <t> split address by commas

### ISSUE THREAD

**Issue by deterenkelt** [vimperator/vimperator-labs#240]
Whether I copy an address to paste in after a search keyword in the field opened by `t` key or paste it from clipboard to open it right away with `P` it gets split into several parts and I got several useless tabs with google and part of the address I pasted instead of one tab with maps.

**Comment by gkatsev** [comment]
Change the url separator from `,` to something else. By default, urls are comma separated.
We might want to consider changing this default to something else because it seems to stump a lot of people.

**Comment by deterenkelt** [comment]
What should I put in .vimperatorrc? //Sorry, but pressing F1 gives me a blank page and google had no answer.

**Comment by gkatsev** [comment]
If you type `:h 'urlseparator'` it should give you the help page for it. You might need to refresh once or twice because our help pages have a bug where they might not render the first time.
You can do several things:
```vim
" if you want to just disable this feature
urlseparator=

" to set the separator to |
urlseparator=\|

" to set the separator to !
urlseparator=!
```

**Comment by deterenkelt** [comment]
Thanks. It should work now
Though, when I type `:h 'urlseparator'` I see a page filled with unformatted text then a blank page. F5 doesn’t help neither here not with the general help page. This is another bug however, so I should close this one.
