### ISSUE TITLE
How to open current url with Chrome?

### ISSUE THREAD

**Issue by ghost** [vimperator/vimperator-labs#244]
I know we can use this code to open current url with IE:
command! ie js liberator.execute('!start iexplore ' + buffer.URL)

but how to open current url with Chrome.
My path of chrome is:
c:\Program Files (x86)\Google\Chrome\Application\chrome.exe
I use windows 7

**Comment by fedemp** [comment]
I'm not using windows, but from your example, it seems that `iexplore` is in your path. Won't it work if you replace `iexplore` with `chrome`?

The worst scenario should be that you hardcode the full path to chrome.

**Comment by jwvim** [comment]
Thanks fedemp.

I found the solution. check below:
map ,e :js io.run("C:\\Program\ Files\\Internet Explorer\\iexplore.exe", [buffer.URL])<CR>
map ,c :js io.run("C:\\Program\ Files\ (x86)\\Google\\Chrome\\Application\\chrome.exe", [buffer.URL])<CR>
