### ISSUE TITLE
yank URL to encode + by default

### ISSUE THREAD

**Issue by cizmazia** [vimperator/vimperator-labs#25]
With the default yankencodedurl = false, only whitespace charaters are replaced by %20. When yanking URL with the + sign and pasting it back to open a new tab, the + sign is interpreted as a space character. 

Desired behavior: With the default yankencodedurl = false, the + sign (%2B) should be escaped, too.

**Comment by gkatsev** [comment]
We're unlikely to change this default for a while longer.

**Comment by l29ah** [comment]
Why?

**Comment by Mine02C4** [comment]
[FYI] Old discussion of similar topic
https://groups.google.com/d/topic/vimperator-labs/S1Cm6usL28w/discussion

**Comment by cizmazia** [comment]
Glad to hear more support! Please could you reconsider this?

**Comment by l29ah** [comment]
In fact it is sad that there's no way to make it escape only non-UTF8 (#579) and misinterpreted characters, as `yankencodedurl` makes non-latin URLs unreadable.
