### ISSUE TITLE
FF Nightly (branch fixup-nightly) stopped work with 42.0a1 because it is not signed

### ISSUE THREAD

**Issue by cyber-duracel** [vimperator/vimperator-labs#254]
Hi,

Master branch does not work with nightly, fixup-nightly worked but stopped now. Is there a way how to get fixup-nightly signed or how to elude this check in FF?

Thanks a lot

**Comment by gkatsev** [comment]
You can turn off signing in nightly and aurora builds. Follow #180 for status on official signing support.

**Comment by cyber-duracel** [comment]
Great. Thanks a lot. It works.
