### ISSUE TITLE
Unable to see Hint #'s in Wikia.com menubar

### ISSUE THREAD

**Issue by Evidlo** [vimperator/vimperator-labs#255]
## Reproducing
Visit `wikia.com` and hit `f`.  The links along the top have no number associated with them.

Someone mentioned that this is potentially because the z-index of the menu is enormous (5000101).

**Comment by The-Compiler** [comment]
The `z-index` vimperator currently uses for hints [is 5000](https://github.com/vimperator/vimperator-labs/blob/master/common/skin/liberator.css#L5)  - it might make sense to use `2 ** 32 / 2 - 1` which is the maximum value every engine should support IIRC. Firefox might even support higher values, no idea.

I can't easily check, but I think this will also be broken for the search field (and buttons in the same bar) on youtube.com as that uses `1999999999`.

**Comment by mcarton** [comment]
This is indeed really annoying and 5000 is definitely not enough for a lot of websites.

There are several
```css
z-index: 2147483647; /* max value for this property */
```
instances in Firefox's source (which is 2³¹-1). And there are several variables named `aZIndex` whose type are `int32_t`. Although there [does not seem to have any limit](https://drafts.csswg.org/css-values-3/#integers) to what an integer can be.
I've set vimperator's `z-index` to 2³¹-1 and haven't had any problem so far. Maybe this should be the new default?

**Comment by Evidlo** [comment]
I tested this.  Firefox will actually cap the z-index at 2^32-1

    <!DOCTYPE HTML>
    <html>
      <body>

        <p> Hello World
        <div style="z-index:0;border: 1px solid;">This Div has a z-index of 0</div>
        <div style="z-index:2147483647;border: 1px solid;">This Div has a z-index of 2147483647</div>
        <div style="z-index:2147483648;border: 1px solid;">This Div has a z-index set to 2147483648, but FF caps it at 2147483647.</div>
      </body>
    </html>

**Comment by gregist** [comment]
This issue reappeared on FF44+. Please reopen.

**Comment by Neftas** [comment]
I can corroborate. Google, YouTube, wikia.com suffer from this issue in Firefox 44.

**Comment by rr-** [comment]
Another site, same problem.
