### ISSUE TITLE
Statusline remains visible in full screen mode.

### ISSUE THREAD

**Issue by demokritos** [vimperator/vimperator-labs#26]
Hi,

I am using Youtube with HTML5 player. When I change the player to full screen mode, the statusline does not disappear.
I tried hiding the statusline using a javascript on http://stackoverflow.com/questions/21053262/vimperator-autohide-statusline , but about 2px dotted white line was still shown at the bottom in full screen mode.
I think that in full screen mode(not only for Youtube), the statusline should be hidden from the start and be shown by user input.

Thanks.

**Comment by nuisanceofcats** [comment]
I wish somebody would apply this.

**Comment by nuisanceofcats** [comment]
Here's a nice way to do it in your vimperatorrc for the meantime:

```vim
" Hide status bar when fullscreen mode is detected
autocmd Fullscreen .* js updateBottomBar()
:js << EOF
```
```javascript
var hlContentSepValue = highlight.get('ContentSeparator').value

function updateBottomBar() {
  var bb = document.getElementById('liberator-bottombar')
  if (! bb) return

  if (window.fullScreen) {
    bb.style.height = '0px'
    bb.style.overflow = 'hidden'
    liberator.execute('highlight ContentSeparator display: none;')
  }
  else {
    bb.style.height = ''
    bb.style.overflow = ''
    liberator.execute('highlight ContentSeparator ' + hlContentSepValue)
  }
}
```
```vim
EOF
```

**Comment by cpypcy** [comment]
Still not fixed :(

**Comment by nuisanceofcats** [comment]
@cpypcy No big deal just add the text from the previous comment into your .vimperatorrc

**Comment by cpypcy** [comment]
Would be nice to have some path where i can find this file.

**Comment by maxauthority** [comment]
If somebody can turn the JavaScripts in a nice integrated
fullscreen-handler which I can apply to the main source code, I'd be very
happy to apply it as I agree in fullscreen mode like when watching videos
we should hide the command line (at least until the user presses : to show
it temporarily but that's more of a plus and not required in the first
place).

The entry point should probably be common/content/events.js:onResize()
where we detect fullscreen changes.

Good luck,
Martin

**Comment by demokritos** [comment]
https://github.com/demokritos/vimperator-labs/commit/55c622c231c4bcb13c122d6712b7135e9cc1191b

This is my humble code for this issue. I have used this for a long time.
You can map a key to statusline toggle by adding the following line into .vimperatorrc:
```
noremap <silent> <F8> :js statusline.toggle('toggle')<CR>
```

**Comment by maxauthority** [comment]
Thanks for the first attempt.

Instead of:
statusline.toggle(p, q)

(especially where p and q are "bad" in terms of non-descriptive
abbreviations), I would make a

statusline.updateVisibility() function which is called in the above cases
(toggling fullscreen, or entering/exiting command line mode).

and that function would just check the window.fullScreen and the mode to
determine the new visibility state.

Yes, we would loose the "manual" possibility to toggle the command line,
but is that really required? If yes, than I'd rather opt for a :set
autohide=true/false option, which would also hide the command line in
non-fullscreen mode.

**Comment by nuisanceofcats** [comment]
I'd prefer to have two APIs, one to check if the status line is visible and one to set visibility. You could easily toggle it then by combining the APIs then.

**Comment by maxauthority** [comment]
Yeah having just a setVisibility() and getVisibility() is also fine.

On Fri, Feb 27, 2015 at 12:44 PM, Nuisance of Cats <notifications@github.com

**Comment by sam113101** [comment]
@gkatsev maine_coon doesn't work, and IMO this feature should be a vimperator default.

**Comment by c0ffeeartc** [comment]
Last scripts work well with fullscreen videos. Is there a way to hide 1px separator for regular browsing when statusline is manually hidden?

**Comment by quaritexa** [comment]
Line «cnoremap <CR> <CR>:js toggle_bottombar('off')<CR>» blocks command yield (like :usage).

**Comment by jgkamat** [comment]
+1 on this should be the vimperator default. A plugin shouldn't be needed for this.

**Comment by srustamo** [comment]
>  Line «cnoremap :js toggle_bottombar('off')» blocks command yield (like :usage).

I suppose 'blocks command yield' means that this line breaks writing into and reading `~/.vimperator/info/defaults/history-command` file for completion. In my case, having this code stops this file being updated and read, if I have being

**Comment by srustamo** [comment]
Apparently, 'command yield' is a different matter, now that I checked.

So, `~/vimperator/info/defaults/history-command` not being read/written is a separate issue.

**Comment by atommixz** [comment]
So where is the best solution?

**Comment by demokritos** [comment]
pizzooid's autohide function works well, but there is no capability to hide the bottombar in non-fullscreen mode or to unhide it in fullscreen mode. This code also disables users from coding related functions in .vimperatorrc.
