### ISSUE TITLE
embed mode?

### ISSUE THREAD

**Issue by anoda9** [vimperator/vimperator-labs#261]
Sometimes when viewing flash videos, vimperator goes into "embed" mode and becomes unresponsive. Where in the help documentation is information on this mode? How can I get out of it once it triggers?

**Comment by gkatsev** [comment]
`embed` mode is basically any time a plugin (like flash) steals focus. Unfortunately, there's basically no way to exit it without using the mouse and clicking outside of the flash video. At least until plugins allow us to take focus back. Which probably won't happen any time too soon.
Some people have hacked together autohotkey or xdotool scripts to "click" on the page for them. Either way, this has to be done outside of vimperator and probably firefox.
Unfortunately, there isn't anything we can do. Closing this, but if you have any more questions, feel free to ask them here.
