### ISSUE TITLE
set gui=none not working

### ISSUE THREAD

**Issue by gregist** [vimperator/vimperator-labs#265]
latest master build + FF aurora + win 10

```set gui=none``` returns ```Invalid argument: none```

**Comment by gregist** [comment]
workaround: ```set gui=noaddons,nobookmarks,nomenu,nonavigation,notabs``` works fine.

I don't know whether it's a feature change or a bug...

**Comment by gkatsev** [comment]
That's because I'm silly and forgot to re-add `all` and `none` in my fixup branch before merging: https://github.com/vimperator/vimperator-labs/pull/242/files#diff-8c3f97ad46f1aaab399a814717ef6e0cR1308
I'll fix it before a release.

**Comment by gkatsev** [comment]
Fixed by 4a8e1edff7802dbde215913a7f7af3c1ae2c1465
