### ISSUE TITLE
The menubar cannot be shown by Alt key in NORMAL mode.

### ISSUE THREAD

**Issue by demokritos** [vimperator/vimperator-labs#27]
It would be nice if menubar could be shown by Alt key. But in NORMAL mode, it is not.
In INSERT and COMMAND_LINE modes, pressing and releasing the Alt key unhides the menubar.

I modified common/content/events.js. This solves the issue, though I don't know its side effects. 

```diff
diff --git a/common/content/events.js b/common/content/events.js
index 4c2830b..18effcf 100644
--- a/common/content/events.js
+++ b/common/content/events.js
@@ -1069,7 +1069,9 @@ const Events = Module("events", {
     onKeyUpOrDown: function (event) {
         if (modes.passNextKey || modes.passAllKeys || modes.isMenuShown || Even
             return;
-        event.stopPropagation();
+       let key = events.toString(event);
+       if (!key)
+            event.stopPropagation();
     },
 
     onPopupShown: function (event) {
```

**Comment by gkatsev** [comment]
I can show and hide the menu bar by pressing alt in all vimeprator modes. Going to close this unless there's more evidence shown that the change is necessary or useful.
