### ISSUE TITLE
Can't remap <space>?

### ISSUE THREAD

**Issue by anoda9** [vimperator/vimperator-labs#270]
It seems like vimperator can't remap the spacebar.
I put this in my rc file:
>nnore <Space> 24j
nnore <S-Space> 24k

and shift-space works fine, but space still keeps its default behavior.

**Comment by gkatsev** [comment]
Duplicate of #10.

**Comment by anoda9** [comment]
Whoops. I searched issues for "remap space" before posting but nothing came up. :)

**Comment by gkatsev** [comment]
no worries :)
