### ISSUE TITLE
Tabnumbers with vimp 3.10.1 and latest aurora builds don't play nicely together

### ISSUE THREAD

**Issue by gkatsev** [vimperator/vimperator-labs#274]
I'm not sure whether it's an issue on linux only or not and whether it's just with the dev edition theme. But the numbers aren't shown and the tab styles end up looking weird.

**Comment by derenio** [comment]
I'm not sure if it's the same bug, but with the arrival of stable FF41 my `tabnumbers` started to look like this:
![tabnumbers](https://cloud.githubusercontent.com/assets/432308/10058666/037d498c-6247-11e5-8d5f-6423af2fa612.png)
I've even switched to the default theme in case that could be the culprit, but no luck.

**Comment by gkatsev** [comment]
yeah, it's probably the same issue.
