### ISSUE TITLE
Bookmarks not deleting

### ISSUE THREAD

**Issue by soredake** [vimperator/vimperator-labs#275]
:delbmarks sub.domain.example don't works.

:delbm! works
FirefoxDevEdition 42, e10s off

**Comment by gkatsev** [comment]
I believe this is by design. I think `:delbmarks` is only meant to delete one bmark at a time where-as with the `!` at the end it will delete everything that is matches. This is so that you don't accidentally delete a bunch of stuff you dont want.

**Comment by fenque** [comment]
With ```!``` it deletes all bookmarks, deletes all the bookmarks and not those that match.

**Comment by gkatsev** [comment]
Yep, you might be right. I may have misread it. It's very possible it broke at some point.

**Comment by zklinger** [comment]
```:delbmarks``` only deletes one bookmark identified by a full matching url. Partial matches are not supported. For example, if you had two bookmarks http://foo.com/bar/aaa.html and http://foo.com/bar/bbb.html ```:delbmarks http://foo.com/bar``` wouldn't delete anything only ```:delbmarks http://foo.com/bar/aaa.html``` or ```:delbmarks http://foo.com/bar/bbb.html``` would work.

**Comment by fenque** [comment]
Maybe you should broaden its functionality to delete multiple bookmarks on the part of the url?

**Comment by maxauthority** [comment]
At least supporting wildcards like * would be a good extension, I agree.
