### ISSUE TITLE
Support for Thunderbird 38.2 on Ubuntu 12.04

### ISSUE THREAD

**Issue by morsedl** [vimperator/vimperator-labs#277]
For reasons unknown to me, Canonical stopped updating Thunderbird at v31.8, at least on 12.04 LTS.  In the last week or so, however, they finally updated to v38.2.  It seems clear, however, that something relevant to the keyboard handling has changed, as Muttator is still installed but none of its keyboard shortcuts work, nor can I press the colon key (:) to get a Muttator command line.

I have thus uninstalled the Ubuntu .deb Thunderbird packages (keeping my Thunderbird profile, and hence Muttator) and re-installed v31.8 from the Mozilla site into /usr/local/lib/thunderbird.  Then I ran "ln -s /usr/local/lib/thunderbird/thunderbird /usr/bin/thunderbird" as root to make it accessible, and all seems fine, except there is now no integration with gnome (notifications) or the global menu, which is fine.

I probably use Muttator more than any other add-on in any program, so I am curious as to when it will support Thunderbird 38.2 and what I can do to help move that along (I'm Ph.D. candidate these days, but was [and still am] a software engineer).  Thanks!

**Comment by gkatsev** [comment]
Do you mean thunderbird in the title? If so, this sounds like a dupe of #237

**Comment by morsedl** [comment]
@gkatsev Yes, I believe you are correct, this is a dup of #237.  Closing this ticket.
