### ISSUE TITLE
Unable to use `gg`, `G` and marks on some websites

### ISSUE THREAD

**Issue by mcarton** [vimperator/vimperator-labs#278]
On some website scrolling with `gg`, `G` or marks does not work.
Example of such websites:
  - https://groups.google.com/a/isocpp.org/forum/?fromgroups#!forum/std-discussion
  - https://blog.wikimedia.org/

Trying to set a mark with `ma` cause the following message:
```
Added local mark: a, https://blog.wikimedia.org/, (0%, 0%)
```
even if you're not in the top-left of the page. Then trying to jump with `'a` does nothing. `gg` and `G` do nothing either.

Navigation is still possible with `hjkl` and other features seem to work too.

**Comment by maxauthority** [comment]
Confirmed. Although we should just reuse the scrolling of Firefox anyway, so we get nice smooth scrolling (unless the user disables that).

**Comment by Enzime** [comment]
Working on fixing this now: airodactyl@302568be20d942b80cb8a569b12892239212991b

I have fixed the scrolling for gg and G, and will fix C-d and C-u, but I can't see an easy fix for marks as it is unknown for what you want to save the mark for and other than the window, it is hard to make sure we identify scrollable elements in such a way that they work even after reopening the tab. My suggestion would be to not allow adding marks in this situation just like pentadactyl.

**Comment by maxauthority** [comment]
Just send me a pull request, once you think that fixes have been tested
thoroughly and are ready to be pushed. Thanks!

**Comment by gkatsev** [comment]
@Enzime did you ever get a PR for this? Thanks.
