### ISSUE TITLE
Sometimes vimperator stops to function correctly

### ISSUE THREAD

**Issue by amosbird** [vimperator/vimperator-labs#279]
after I open a bunch of tabs, Vimperator becomes disfunction from time to time. I have to close some tabs or wait for a while.

**Comment by amosbird** [comment]
also I found that on some pages ctrl keys don't work

**Comment by Enzime** [comment]
When this happens can you test if you can still open a new tab, and and if Ctrl-Tab still works to switch tabs.

Extra steps that if you ran these would greatly help in debugging this:
1. set this option as soon as you can: :set! devtools.chrome.enabled=true or through about:config (as you may have trouble trying to do this when vimperator gets into that state)
2. whenever that state occurs, press Ctrl-Shift-J (opens the browser console) and type: liberator.eval("modes.isMenuShown") and post the result of this
3. Try right clicking on the page and then closing that right click menu and seeing if this fixes the issue

Also, with the Ctrl keys not working on some pages, could you give any examples where it doesn't work?

**Comment by losingkeys** [comment]
I have this (or a similar) issue. When it stops working I can "fix" it in one of two ways:

1. close/reopen firefox
1. Press `Alt` to open a menu, then esc to close it

When it stops working I can't use o/b/t, or really anything vimperator, and my vimperator `<nop>` mappings stop working, so I can use things I was disabling before, like `<c-w>`. 

I'm not sure how to relaibly trigger this yet, but I'll come back if I figure it out.

**Comment by Enzime** [comment]
An alternate solution is to just right click and then close the right click menu, which will get vimperator out of 'MENU mode' (there's no explicit mode for this like there is in pentadactyl).

For some reason vimperator is probably thinking that some menu is still open and until you open and close a menu it won't reset this state.

**Comment by timss** [comment]
Menu sounds plausible. It could possibly explain why Ubuntu's Unity is often acting up as well, since their menu bar is somewhat special being integrated in their taskbar with activation trigger on hover and other. Please see #39 as well.
