### ISSUE TITLE
Vimperator broken in latest Nightly 44.0a1 (2015-09-23)

### ISSUE THREAD

**Issue by danemacmillan** [vimperator/vimperator-labs#289]
Vimperator is broken in the latest Nightly build. I suspect this will be a common theme as Firefox continues to improve its core, and [deprecate its old addons framework](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/). There are about six weeks till DevEdition/Aurora, etc, etc: this ticket is just a rehash of the original in https://github.com/vimperator/vimperator-labs/issues/231, which was patched a few weeks back.

Here's some additional logging for the latest break:

```
10:07:09.883 OpenGL compositor Initialized Succesfully.
Version: 2.1 NVIDIA-10.4.2 310.41.35f01
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 750M OpenGL Engine
FBO Texture Target: TEXTURE_2D
10:07:24.285 options.get(...) is null autocommands.js:110:0
10:07:24.640 unsafe CPOW usage remote-browser.xml:164:0
10:07:24.642 TypeError: options.get(...) is null autocommands.js:110:13
10:07:24.882 unsafe CPOW usage remote-browser.xml:164:0
10:07:24.884 TypeError: options.get(...) is null autocommands.js:110:13
10:07:27.062 options.get(...) is null autocommands.js:110:0
10:07:27.872 options.get(...) is null autocommands.js:110:0
10:07:27.945 Use of nsIFile in content process is deprecated. bootstrap.js:36:40
10:07:28.207 Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:3:6598
10:07:28.224 options.get(...) is null autocommands.js:110:0
10:07:33.909 TypeError: this.controller is undefined
 browserPlacesViews.js:263:1
10:07:37.850 OpenGL compositor Initialized Succesfully.
Version: 2.1 NVIDIA-10.4.2 310.41.35f01
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 750M OpenGL Engine
FBO Texture Target: TEXTURE_2D
```

Admittedly, there is probably a lot of work ahead to prevent Vimperator from becoming obsolete over the next [12 to 18 months](https://github.com/vimperator/vimperator-labs/issues/264). The Mozilla Hacks blog recently published an article about writing an extension using the new [Web Extension API](https://hacks.mozilla.org/2015/09/lets_write_a_webextension/), which is a good start for anyone interested in Vimperator development.

CC: @dersam

**Comment by gkatsev** [comment]
Yep, sounds like some more fixes are needed :)
Thankfully, I don't think we use any binary XPCOM plugins.

**Comment by protrolium** [comment]
I updated to Firefox 41.0 tonight and can confirm Vimperator is completely broken.

**Comment by maxauthority** [comment]
Yeah, I guess, we'll need to take a look at WebExtensions soon, as all
other fixes probably won't stay too long when Firefox is changing so fast.

It's be interesting, if one could take Vimium (for Chrome) as a base, and
port that to the new webextenstion and then just add back Vimperator
functionality over time.

**Comment by danemacmillan** [comment]
@maxauthority When a feature branch with some foundational work is created, I'll gladly commit some of my time to this project. It has become essential in my day-to-day.

**Comment by Segaja** [comment]
One thing I found is this: https://www.fxsitecompat.com/en-US/docs/2015/nosuchmethod-is-no-longer-supported/ which might explain it, because the util.js uses it in the init() function of the Array object.

**Comment by danemacmillan** [comment]
Since opening this bug I moved to Developer Edition, and *now* Developer Edition has kind of broken. Netscape 6 is on the horizon. [This is how I feel](http://www.element14.com/community/servlet/JiveServlet/showImage/2-140080-215872/scotty-meme-generator-she-cannae-take-any-more-captain-she-s-gonna-blow-1bc725.gif).

**This is what my statusline looks like as of today's update:**
<img width="1680" alt="screen shot 2015-10-22 at 9 51 44 am" src="https://cloud.githubusercontent.com/assets/4390491/10667245/51d48410-78a4-11e5-8126-7480e7199f04.png">

Fortunately it goes away with an `Esc`, and most of the functionality still appears to be intact, but unfortunately no themes load. 

**This is what the Browser Console reports upon opening the browser:**

```
10:05:46.266 Could not read chrome manifest 'file:///opt/homebrew-cask/Caskroom/firefoxdeveloperedition/latest/FirefoxDeveloperEdition.app/Contents/Resources/chrome.manifest'.
10:05:46.514 Get a connection to permissions.sqlite.
10:05:46.780 mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create base.js:316:5
10:05:46.999 OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.10.18
Vendor: Intel Inc.
Renderer: Intel Iris Pro OpenGL Engine
FBO Texture Target: TEXTURE_2D
10:05:47.113 DEPRECATION WARNING: FUEL is deprecated, you should use the add-on SDK instead.
You may find more details about this deprecation at: https://developer.mozilla.org/Add-ons/SDK/
jar:file:///opt/homebrew-cask/Caskroom/firefoxdeveloperedition/latest/FirefoxDeveloperEdition.app/Contents/Resources/browser/omni.ja!/components/fuelApplication.js 1458 Application
jar:file:///opt/homebrew-cask/Caskroom/firefoxdeveloperedition/latest/FirefoxDeveloperEdition.app/Contents/Resources/browser/omni.ja!/components/fuelApplication.js 726 af_ci
chrome://liberator/content/io.js 333 IO<.init
chrome://liberator/content/base.js line 300 > eval 14 io
chrome://liberator/content/modules.js 90 load
self-hosted 211 forEach
chrome://liberator/content/modules.js 119 onload
null 0 null
 Deprecated.jsm:79:0
10:05:47.186 Error: __noSuchMethod__ is deprecated options.js:44:26
10:05:47.233 vimperator: All modules loaded
10:05:47.244 vimperator: Vimperator fully initialized
10:05:47.245 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ import.js:223:4
10:05:47.538 OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.10.18
Vendor: Intel Inc.
Renderer: Intel Iris Pro OpenGL Engine
FBO Texture Target: TEXTURE_2D
10:05:47.651 vimperator: No user macros directory found
10:05:47.655 DEPRECATION WARNING: Search service falling back to synchronous initialization. This is generally the consequence of an add-on using a deprecated search service API.
You may find more details about this deprecation at: https://developer.mozilla.org/en-US/docs/XPCOM_Interface_Reference/nsIBrowserSearchService#async_warning
resource://gre/components/nsSearchService.js 3465 SRCH_SVC__ensureInitialized
resource://gre/components/nsSearchService.js 4497 SRCH_SVC_getEngines
chrome://liberator/content/commandline.js 1620 completer
chrome://liberator/content/completion.js 510 fork
chrome://liberator/content/options.js 423 Option<.validateCompleter
chrome://liberator/content/options.js 370 Option<.validator
chrome://liberator/content/options.js 200 Option<.isValidValue
chrome://liberator/content/options.js 307 Option<.op
chrome://liberator/content/options.js 1033 setAction
chrome://liberator/content/options.js 1207 Options<.commands/<
chrome://liberator/content/liberator.js 932 Liberator<.trapErrors
chrome://liberator/content/commands.js 86 exec
chrome://liberator/content/commands.js 98 Command<.execute
chrome://liberator/content/io.js 688 execute
chrome://liberator/content/io.js 734 IO<.source
chrome://liberator/content/liberator.js 1868 Liberator<.load/<
null 0 null
 Deprecated.jsm:79:0
10:05:47.681 vimperator: Searching for "colors/fxdevtools-dark.vimp" in "~/.vimperator"
10:05:47.716 vimperator: Sourced: /Users/danemacmillan/.vimperator/colors/fxdevtools-dark.vimp
10:05:47.718 vimperator: Sourced: /Users/danemacmillan/.vimperatorrc
10:05:47.718 vimperator: No user plugin directory found
10:05:53.858 OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.10.18
Vendor: Intel Inc.
Renderer: Intel Iris Pro OpenGL Engine
FBO Texture Target: TEXTURE_2D
```

**Comment by danemacmillan** [comment]
Good news--Vimperaor in DevEdition is working again! It's not perfect but, the colorschemes load, and there's no startup error. Here's the browser console output, though, which does display Vimperator-related debug output:

```
18:44:40.137 Could not read chrome manifest 'file:///opt/homebrew-cask/Caskroom/firefoxdeveloperedition/latest/FirefoxDeveloperEdition.app/Contents/Resources/chrome.manifest'.
18:44:40.391 Get a connection to permissions.sqlite.
18:44:40.945 OpenGL compositor Initialized Succesfully.
Version: 2.1 NVIDIA-10.6.47 310.42.05f01
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 750M OpenGL Engine
FBO Texture Target: TEXTURE_2D
18:44:40.956 mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create base.js:316:5
18:44:41.300 DEPRECATION WARNING: FUEL is deprecated, you should use the add-on SDK instead.
You may find more details about this deprecation at: https://developer.mozilla.org/Add-ons/SDK/
jar:file:///opt/homebrew-cask/Caskroom/firefoxdeveloperedition/latest/FirefoxDeveloperEdition.app/Contents/Resources/browser/omni.ja!/components/fuelApplication.js 1458 Application
jar:file:///opt/homebrew-cask/Caskroom/firefoxdeveloperedition/latest/FirefoxDeveloperEdition.app/Contents/Resources/browser/omni.ja!/components/fuelApplication.js 726 af_ci
chrome://liberator/content/io.js 333 IO<.init
chrome://liberator/content/base.js line 300 > eval 14 io
chrome://liberator/content/modules.js 90 load
self-hosted 211 forEach
chrome://liberator/content/modules.js 119 onload
null 0 null
 Deprecated.jsm:79:0
18:44:41.614 Error: __noSuchMethod__ is deprecated options.js:44:26
18:44:41.657 vimperator: All modules loaded
18:44:41.669 vimperator: Vimperator fully initialized
18:44:41.670 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ import.js:223:4
18:44:42.007 OpenGL compositor Initialized Succesfully.
Version: 2.1 NVIDIA-10.6.47 310.42.05f01
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 750M OpenGL Engine
FBO Texture Target: TEXTURE_2D
18:44:42.343 vimperator: No user macros directory found
18:44:42.346 DEPRECATION WARNING: Search service falling back to synchronous initialization. This is generally the consequence of an add-on using a deprecated search service API.
You may find more details about this deprecation at: https://developer.mozilla.org/en-US/docs/XPCOM_Interface_Reference/nsIBrowserSearchService#async_warning
resource://gre/components/nsSearchService.js 3465 SRCH_SVC__ensureInitialized
resource://gre/components/nsSearchService.js 4497 SRCH_SVC_getEngines
chrome://liberator/content/commandline.js 1620 completer
chrome://liberator/content/completion.js 510 fork
chrome://liberator/content/options.js 423 Option<.validateCompleter
chrome://liberator/content/options.js 370 Option<.validator
chrome://liberator/content/options.js 200 Option<.isValidValue
chrome://liberator/content/options.js 307 Option<.op
chrome://liberator/content/options.js 1033 setAction
chrome://liberator/content/options.js 1207 Options<.commands/<
chrome://liberator/content/liberator.js 932 Liberator<.trapErrors
chrome://liberator/content/commands.js 86 exec
chrome://liberator/content/commands.js 98 Command<.execute
chrome://liberator/content/io.js 688 execute
chrome://liberator/content/io.js 734 IO<.source
chrome://liberator/content/liberator.js 1868 Liberator<.load/<
null 0 null
 Deprecated.jsm:79:0
18:44:42.371 vimperator: Searching for "colors/fxdevtools-dark.vimp" in "~/.vimperator"
18:44:42.640 vimperator: Sourced: /Users/danemacmillan/.vimperator/colors/fxdevtools-dark.vimp
18:44:42.642 vimperator: Sourced: /Users/danemacmillan/.vimperatorrc
18:44:42.643 vimperator: No user plugin directory found
18:44:45.559 JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead tabview.js:4249:34
18:44:45.559 JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead tabview.js:4250:46
18:44:45.559 JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead tabview.js:4251:46
18:44:45.559 JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead tabview.js:4252:46
18:44:45.559 JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead tabview.js:4253:46
18:44:57.324 mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create frameworks-161cec7f4cb9a187f66c2ecb8f59c9098e2ad64458af917ec72f9d61d6b8089b.js:1:26585
18:45:06.957 OpenGL compositor Initialized Succesfully.
Version: 2.1 NVIDIA-10.6.47 310.42.05f01
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 750M OpenGL Engine
FBO Texture Target: TEXTURE_2D
```

**Comment by jackinloadup** [comment]
@danemacmillan What did you do to get it working again on the Developer Edition? Is "follow hint" mode working while e10s is enabled?

**Comment by danemacmillan** [comment]
@jackinloadup I just updated to yesterday's build. The problem went away. I don't have e10s enabled, but when it's on, follow hint mode does not work.

**Comment by vaibhavsagar** [comment]
Firefox 42.0b9 is now having issues as well. How are you accessing this browser console output? I've tried running `firefox` from the command line and viewing the console using developer tools but I'm not seeing any of the output you're seeing above, although my statusline is showing the `NS_ERROR_UNEXPECTED` and my theme is broken.

**Comment by gkatsev** [comment]
You need to tell firefox to log stuff out into the console. I should update the docs with some of this info.

**Comment by danemacmillan** [comment]
@vaibhavsagar I typically get to the Browser Console from here:

<img width="1680" alt="screen shot 2015-10-28 at 4 51 03 pm" src="https://cloud.githubusercontent.com/assets/4390491/10802589/20de8c8a-7d94-11e5-8f8a-df2c58e934be.png">

**Comment by dersam** [comment]
44.0a2 is now the latest version of DevEdition, which means that Vimperator is now broken on DevEdition.

Browser console dump:

Could not read chrome manifest 'file:///Applications/FirefoxDeveloperEdition.app/Contents/Resources/chrome.manifest'.
OpenGL compositor Initialized Succesfully.
Version: 2.1 NVIDIA-10.6.47 310.42.05f01
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 750M OpenGL Engine
FBO Texture Target: TEXTURE_2D
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create base.js:316:5
TypeError: modules.Config is undefined
 liberator-overlay.js:69:5
DEPRECATION WARNING: FUEL is deprecated, you should use the add-on SDK instead.
You may find more details about this deprecation at: https://developer.mozilla.org/Add-ons/SDK/
jar:file:///Applications/FirefoxDeveloperEdition.app/Contents/Resources/browser/omni.ja!/components/fuelApplication.js 1458 Application
jar:file:///Applications/FirefoxDeveloperEdition.app/Contents/Resources/browser/omni.ja!/components/fuelApplication.js 726 af_ci
chrome://liberator/content/io.js 333 IO<.init
chrome://liberator/content/base.js line 300 > eval 14 io
chrome://liberator/content/modules.js 90 load
chrome://liberator/content/modules.js 119 onload
 Deprecated.jsm:79:0
vimperator: All modules loaded
ReferenceError: tabs is not defined statusline.js:259:21
OpenGL compositor Initialized Succesfully.
Version: 2.1 NVIDIA-10.6.47 310.42.05f01
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 750M OpenGL Engine
FBO Texture Target: TEXTURE_2D
vimperator: No user macros directory found
vimperator: Searching for "colors/fxdevtools-dark.vimp" in "undefined"
vimperator: not found in 'runtimepath': "colors/fxdevtools-dark.vimp"
vimperator: Sourced: /Users/samuelschmidt/.vimperatorrc
SyntaxError: attr2 template-tag.js:197:1
options.get(...) is null autocommands.js:110:0
options.get(...) is null autocommands.js:110:0
ReferenceError: tabs is not defined buffer.js:155:13
options.get(...) is null autocommands.js:110:0
OpenGL compositor Initialized Succesfully.
Version: 2.1 NVIDIA-10.6.47 310.42.05f01
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 750M OpenGL Engine
FBO Texture Target: TEXTURE_2D

**Comment by jandem** [comment]
Hi, I'm responsible for removing the non-standard `__noSuchMethod__` feature from SpiderMonkey. According to https://bugzilla.mozilla.org/show_bug.cgi?id=1221584 this broke Vimperator. I'm sorry to hear that!

The Array init function in common/content/util.js uses `__noSuchMethod__`, this should be pretty easy to fix either by defining all methods we're interested in manually or by using `Object.getOwnPropertyNames(ary)` to get the function names and looping over that.

**Comment by jiixyj** [comment]
I've made a patch to work around some of the issues with FF 44 (https://gist.github.com/jiixyj/93277b471590c26cbc3d).
The `__noSuchMethod__` thing probably deserves a more thorough fix, but this seems to work for me.
Calling `exec()` on a regex returns null if no match was found.
There are some changes to scope in Firefox 44 (https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44/). Changing the scope of the Config module from `const` to `var` lets `liberator-overlay.js` find it again. I suspect this needs a more detailed look, however.

**Comment by jackinloadup** [comment]
@jiixyj Thanks your patch worked great.

**Comment by gkatsev** [comment]
@jiixyj want to submit that patch as a PR?

**Comment by googya** [comment]
It works @jiixyj

**Comment by maxauthority** [comment]
Great, I pushed the pull request sent by fenque. Hope that fixes the issue.

**Comment by dersam** [comment]
New version with the PR is working for me on Nightly 45.0a1. :tada:

**Comment by gkatsev** [comment]
Awesome. In that case, I'll close this until next time :P

**Comment by MoSal** [comment]
FWIW, in FF 44 beta, hints seem to not work correctly in Twitter (numbers not showing above many links/elements).

**Comment by Yackback** [comment]
In 44, Vimperator seems to be broken, as I am having the same issue as the OP, but only after updating.

**Comment by alexzorin** [comment]
Also broken in 44.0 (attr2 error, missing hints, search not highlighting until <cr>). Has the fix been pushed to AMO?

**Comment by gkatsev** [comment]
Looks like the option to disable signing check will be removed in firefox 46.

**Comment by 0mid** [comment]
Same problem here in Firefox 44.0. After upgrading FF, Vimperator stopped working.

**Comment by danemacmillan** [comment]
> Looks like the option to disable signing check will be removed in firefox 46.

That's terrible news for Vimperator. Unless somebody can dedicate real time to this project, I don't see it living for much longer.

**Comment by reepush** [comment]
> Looks like the option to disable signing check will be removed in firefox 46.
But how addon developers will test their work? Definitely without signing it after every change, so it shouldn't be a problem for developers at least.

**Comment by MoSal** [comment]
Mandatory signing should be the least of our worries us users. We can just get the unbranded builds Mozilla will provide.

What I'm really concerned about is not getting a fully working Vimperator in FF 45 ESR. And losing Vimperator altogether when XUL is dropped, with no viable alternatives on the horizon.
