### ISSUE TITLE
statusline text misaligned when ssl icon is enabled

### ISSUE THREAD

**Issue by kefkf** [vimperator/vimperator-labs#295]
I use <code>#liberator-bottombar toolbarbutton {
  min-height: 32px;
}
</code> to set the height of the bottom bar however if I turn on the ssl icon on the statusline the statusline text is misaligned whenever the ssl lock icon is displayed.

No icon: ![No icon](https://i.imgur.com/UQR6pNQ.png)
With icon: ![Icon](https://i.imgur.com/Mk1vCzM.png)

Is there anything I can do with css to fix this?

**Comment by danemacmillan** [comment]
I don't have an answer, but @kefkf what did you do to make the SSL icon appear? Are you just setting this: `set status=input,location,bookmark,history,tabcount,position,ssl`?

**Comment by kefkf** [comment]
On 05/10/15 at 18:30, Dane MacMillan wrote:
> I don't have an answer, but @kefkf what did you do to make the SSL icon appear?
> Are you just setting this: set status=
> input,location,bookmark,history,tabcount,position,ssl?
> 
> —
> Reply to this email directly or view it on GitHub.*
>
Yep, that's right. I'm using Firefox 41.

**Comment by hetisthijs** [comment]
Add the following line to userChrome.css:

`#liberator-status-ssl { min-height:14px !important; }`

**Comment by kefkf** [comment]
Yep, works for me as well. Thanks a lot!
