### ISSUE TITLE
Vimperator's status SSL icons are no longer in the Firefox codebase

### ISSUE THREAD

**Issue by danemacmillan** [vimperator/vimperator-labs#301]
The current stable release of Firefox is version 41. In about four weeks it will be supplanted by the current Beta version, 42. The main difference between these two releases is that from Beta (v42) onward, many of the `png` icons used in the browser chrome have been replaced by `svg` icons; the existing `png` icon files have been deleted. The SSL icons used by Vimperator in the status line are no longer available, because they have been removed from Firefox.

<img width="837" alt="screen shot 2015-10-05 at 9 33 58 pm" src="https://cloud.githubusercontent.com/assets/4390491/10299266/03e60df0-6bb6-11e5-9687-be864d14fd8b.png">

In addition, from v42 on, Firefox is not using a different color icon for distinguishing EV SSL (green lock) and regular SSL (grey lock): they are now both green.

I've got a pull request coming.

**Comment by timss** [comment]
Thanks for catching on so quick, but I must say this is kind of a bummer.

>In addition, from v42 on, Firefox is not using a different color icon for distinguishing EV SSL (green lock) and regular SSL (grey lock): they are now both green.
