### ISSUE TITLE
status line not displaying homepage and position

### ISSUE THREAD

**Issue by tsaber** [vimperator/vimperator-labs#305]
Tried release as well as compiling. 

didn't find anything on the net about it. Using archlinux and i3wm.
http://imgur.com/fdZf5ty

The problem was within my firefox profile. I deleted mine and made a new one with:
firefox -P 

I'll leave this issue open for others with the same problem

**Comment by polyzen** [comment]
Getting the same issue with the same setup

**Comment by timss** [comment]
Is this issue still present and reproducable with FF 44 and Vimperator 3.12.0?

**Comment by polyzen** [comment]
https://ptpb.pw/iRxs.png

Pentadactyl shows about:addons in the status bar. The other tab also doesn't show the url, either.

**Comment by timss** [comment]
I have not tested with Pentadactyl.

Which version of Vimperator have you tested? With a fresh profile in FF 44.0.1 and Vimperator 3.12.0 I'm getting `about:addons <history> <tabcount> <position>` as expected.

**Comment by polyzen** [comment]
The screenshot shows FF 44.0.2 and Vimp 3.12.0

**Comment by timss** [comment]
Sorry possibly asking for the obvious, but could it be a colorscheme or highlight issue?

    highlight StatusLine color: red; background: transparent;

**Comment by polyzen** [comment]
@timss that didn't seem to have an effect.

**Comment by timss** [comment]
Hm, ok. Can't think of much else unfortunately, seeing as I'm not able to reproduce what you're experiencing.

**Comment by polyzen** [comment]
:+1: Made a new profile again. Working through restarts

**Comment by timss** [comment]
Great, thanks for reporting back and testing again! 

Messy profiles, especially through Firefox updates, are the bane of all addons it seems.
