### ISSUE TITLE
]] not work for google search page in the latest firefox

### ISSUE THREAD

**Issue by seudut** [vimperator/vimperator-labs#306]
when I update Firefox and Vimperator to the latest version. I find the command  ]], which used to jump to the next label link, doesn't wok for google search result page. but it wok on other page (such as bing search result)
I am not sure if it is the issue of vimperator or firefox or google, but I do remember this worked before for google search page.

**Comment by girishb** [comment]
I'm also seeing the same issue.

**Comment by protrolium** [comment]
]] stopped working for me as well on Google Search results.

**Comment by amosbird** [comment]
+1

**Comment by liaowang11** [comment]
+1

**Comment by gkatsev** [comment]
No need to add +1s. We're aware of the issue and this is part of the whole js-on-web-pages-stealing-key-events that we need to deal with.

**Comment by seudut** [comment]
This issue doesn't happen any more in latest firefox and vimperator.

**Comment by tiborsimko** [comment]
@seudut Indeed, you may want to close the issue.

**Comment by seudut** [comment]
ok, thanks @tiborsimko
