### ISSUE TITLE
how to change the font color of the cmd bar 

### ISSUE THREAD

**Issue by woshichuanqilz** [vimperator/vimperator-labs#308]
I use the 'dark theme' now. And the cmd bar turn into black,so I can't see my type.
How to change the font color.
![10](https://cloud.githubusercontent.com/assets/11295355/10443994/90c84fca-7193-11e5-907d-6450eaec8a79.png)

**Comment by timss** [comment]
Depending on the mode, that would probably be the `CmdLine` highlighting:

    highlight CmdLine background: #191919; color: #afafaf; font-size: 9pt;

See `:highlight`.
