### ISSUE TITLE
No way to disable the default <MiddleMouse> mapping

### ISSUE THREAD

**Issue by MoSal** [vimperator/vimperator-labs#309]
I even removed the mapping from the source.

**Comment by timss** [comment]
Are you sure it's just not your global X11 clipboard mapping that is being used?

**Comment by MoSal** [comment]
Would an X11 mapping check if the current clipboard is a valid URL, then open that URL in the current buffer/tab in Firefox?

**Comment by nagisa** [comment]
@MoSal, yes. It will also “search” for arbitrary text you had selected if you middle-click-paste it somewhere that’s not an input.

**Comment by MoSal** [comment]
Okay.

Setting the following to `false` in `about:config` fixed this for me:
```
middlemouse.contentLoadURL
middlemouse.openNewWindow
middlemouse.paste
```
Closing.
