### ISSUE TITLE
`:ls` and `:b` cause buffer list to collapse

### ISSUE THREAD

**Issue by seletskiy** [vimperator/vimperator-labs#31]
When I want to see buffer list using command `:ls` or `:b`, almost always I see following picture:

![2014-08-28t18 47 04 07 00](https://cloud.githubusercontent.com/assets/674812/4075150/4572768a-2eab-11e4-810c-66d1a8de40f7.png)

Looks like height of that list is calculated incorrectly (I've noticed, that it's always off by one error, and only one item is hidden below).

Maybe it's just my setup, but it reproduceable even with empty vimpreratorrc file.

**Comment by timss** [comment]
Unfortunately this never got any proper attention. If you're still using vimperator, is the issue still present, @seletskiy ?

**Comment by seletskiy** [comment]
@timss: Nope. I do not use FF anymore, it's to laggy, especially, with vimperator :(

**Comment by timss** [comment]
@seletskiy Oh, ok. Thanks for responding though!
If anyone else is experiencing the same, notify me and I'll reopen the issue.

By the way, which platform were you using Firefox on?

**Comment by seletskiy** [comment]
As far as I can remember, there was no such problem at last time I used vimperator. I am using Linux.

**Comment by timss** [comment]
Great. 

Firefox in general has issues with profiles clogging after a while, especially so if the same profile has been used during multiple updates. Cleaning your profile regularly is a good idea, although it sucks doing so.

That being said, using a big addon like Vimperator probably doesn't help with regards to performance.

**Comment by seletskiy** [comment]
I think that my issue is more profound. It's barely has anything to do with profiles, it's more like some core performance problem, because FF lags at rendering very much. So, no matter that vimperator is still the best vim-like navigation addon available across all browsers and has great impact on productivity, it's just unbearable to use it with such lags, where I should wait 500+ms just to see hintchars.

**Comment by timss** [comment]
Perfectly understandable. Hints specifically can be a laggy feature unfortunately.
