### ISSUE TITLE
Reveal-js doesn't work with vimperator

### ISSUE THREAD

**Issue by shivams** [vimperator/vimperator-labs#310]
`Reveal-js` is a javascript framework for creating slides using HTML/CSS/JS. When using vimperator, the arrow keys used to navigate the reveal-js slides do not work. This needs to be resolved. 

Currently, what I do is that I disable vimperator using <kbd>Shift</kbd><kbd>Esc</kbd>, and then navigate slides using arrow keys.

**Comment by brianpeiris** [comment]
I believe needing to use Shift Esc is expected behavior. Reveal-js accepts input just like any other website and vimperator should not need to treat it specially.

**Comment by gkatsev** [comment]
Yep, what @brianpeiris said. Entering pass-through mode is the expected behavior.
