### ISSUE TITLE
Display insecure websites more prominently

### ISSUE THREAD

**Issue by nagisa** [vimperator/vimperator-labs#314]
With `set gui=none`, there’s no indication on the UI that the website is insecure (the infamous padlock is not visible).

Perhaps tinting the status bar/URL to some shade of red would be sufficient?

**Comment by timss** [comment]
You can add the SSL icon to your statusline. For example:

    set status="input,location,bookmark,history,tabcount,ssl" 

![ssl](https://i.imgur.com/RZmCtKW.png)

**Comment by nagisa** [comment]
Thanks, that helps a lot!
