### ISSUE TITLE
hint mode not working on FF aurora 43.0a2 / Windows 10

### ISSUE THREAD

**Issue by gregist** [vimperator/vimperator-labs#315]
the error message:
![2015-10-23_15-30-33](https://cloud.githubusercontent.com/assets/6292095/10686880/1c8522cc-799b-11e5-99aa-51841244d933.png)

**Comment by timss** [comment]
See the latest comment in #289 as well.

**Comment by gregist** [comment]
latest dev version 43.0a2 (2015-10-24) fixed this issue miraculously.
