### ISSUE TITLE
set! browser.download.dir= autocomplete

### ISSUE THREAD

**Issue by ratijas** [vimperator/vimperator-labs#318]
how do i make `set!` command autocomplete values from filesystem path?

**Comment by timss** [comment]
While filesystem path completion is available for commands such as `:source`, adding it to `:set!` would require logic that decides which commands to autocomplete filesystem paths. Personally I don't really see the big gain by doing so, and it would add complexity and possibly slow down the `:set!` command noticeably.

**Comment by ratijas** [comment]
Firefox options have `type`, so autocompletition by path can be narrowed down to options with type �string�.

Or at least can i redefine autocomplete behavior just for this case?

Let's say, i'm downloading video courses from coursera, so once in while i have to create new folder for next week and switch new downloads there. Wouldn't it be a pleasure to have better way than going preferences, using trackpad, you know, selecting directory�

i'm not a guru of VimL.  Thanks for your patience:)

**Comment by timss** [comment]
Preferences do have types, but they're not strictly enforced. I guess you could presume the type based on the current setting though, but again, this would add complexity for an odd case.

One suggestion I have is to make a javascript function in Vimperator which sets the download directory based on date if it matches a coursera website. You could add something like this to your `$HOME/.vimperatorrc`. 

Note that I did **not** get `browser.download.directory` to work, so change accordingly!

    :js << EOF
    function cdl() {
        if(buffer.URL.match(/.*coursera\.org.*/)) {
            today = new Date().toLocaleFormat("%d%m%y")
            Preferences.set("browser.download.directory", "/home/user/videos/coursera/" + today)
        }
    }
    EOF

Another solution is to use a dedicated tool for the job, such as coursera-dl:

https://github.com/coursera-dl/coursera-dl

**Comment by ratijas** [comment]
you have good point, though i didn't mean to download lectures once in a week.

your js may doesn't work because option supposed to be `browser.download.dir`, not `.directory`.

well, thanks a lot for pointing out coursera downloading tool!  that's much better than i could imagine.
