### ISSUE TITLE
Search for a sentence with comma results for seveveral searches of parts of the sentence.

### ISSUE THREAD

**Issue by tot-to** [vimperator/vimperator-labs#319]
When I do a search for a sentence with ":open" or ":tabopen" command in Firefox with Vimperator extention, the sentence is slitted into several parts and each part is submitted separately to the search engine resulting in a multiple tabs openning (even in the case of usage ":open", which is not supposed to open any new tabs).

This is extremely annoying. I have to remove commas manually after copy-pasting something, that I'd like to look for.

**Comment by ratijas** [comment]
[liberator://help/browsing#o](liberator://help/browsing#o)
[liberator://help/options#%27urlseparator%27](liberator://help/options#%27urlseparator%27)
>>> “Set the separator regex used to separate multiple URL args.”

hope, that'd help.

**Comment by tot-to** [comment]
Nice! Thanks a lot!
":set urlseparator=" solved the issue.

Perhaps, this report should then be considered as a request to change the default value of urlseparator to an empty string.

**Comment by timss** [comment]
The `urlseparator` option is quite useful indeed, but I'm not sure if I agree with its default being changed. You could try your luck by adding a pull request, realistically the maintainers would probably not take it upon themself to add it based on this issue alone. 

Either way, I think we should consider this issue resolved and to be closed :-)

**Comment by ratijas** [comment]
it's not an issue, but a feature :-)

personally, i'd better use `;\s` (semicolon), because few times i also got trapped into `'urlseparator'` when searching for post address, which is normally comma-separated: "42 fl., Universe st., City, Country"

**Comment by tot-to** [comment]
This feature is probably can be very useful... but only when user expects it to work in this way and do not copy-paste strings in order to search for them.

But I believe, that copy-pasting is very widespread use-case and for people like me this behaviour is something unforeseeable and even annoying.

Semicolon might be a better choice, since it more rare symbol in sentences, but still can arise such unwanted behaviour.

**Comment by maxauthority** [comment]
Actually having "" as the new urlseparator default would probably be ok for
me, I really think it causes more issues than helps. Maybe there is some
other good default value which would have the expected thing for copy'n
paste but still allow the multi-tab feature to be used in a custom
quickmark?

**Comment by tot-to** [comment]
I can't think about a single symbol, unless it's a symbol, that is not present in common keyboard layouts, but then it's useless to have it as a separator. But probably some sequence of two or three symbols would work, if it's extremely unlikely to find it in any texts or logs. For instance, double semicolon ";;" does not seem to be very common.

**Comment by wetneb** [comment]
I agree that this default behaviour is really annoying. I ran into the problem many times this week and it's extremely frustrating.
