### ISSUE TITLE
The wiki and the FAQ are gone?

### ISSUE THREAD

**Issue by spaghetti-** [vimperator/vimperator-labs#32]
I can't find them from the website because it redirects to google code which shows a shifted page instead.

**Comment by anEffingChamp** [comment]
What happened to these efforts to expand the wiki? I just arrived, looking for information on how I can customize with a `.vimperatorrc`, and there is no explanation on it. I am willing to contribute any thing I find, but wonder what the current climate is.

**Comment by maxauthority** [comment]
Well, still the same as before.
https://github.com/vimperator/vimperator-labs/wiki is just waiting for some
(good) content :)
I guess making sub pages "FAQ" "Tutorial" etc. make a good start but it
requires someone with dedication so it does end up with great content and
not some random notes which don't help the end user anything.

For now, looking through the :help pages within Vimperator are probably the
best for newbies (although it certainly has a steep learning curve).

**Comment by gkatsev** [comment]
Looks like you can get to the old stuff via cached urls: http://web.archive.org/web/20090703041629/http://vimperator.org/trac/wiki/Vimperator/FAQ and http://webcache.googleusercontent.com/search?q=cache:nLJHOPlmlpsJ:wiki.vimperator-labs.googlecode.com/hg/VimperatorFAQ.wiki+&cd=4&hl=en&ct=clnk&gl=us
