### ISSUE TITLE
[question] I want to youtube-dl current url

### ISSUE THREAD

**Issue by gregist** [vimperator/vimperator-labs#320]
What should I put into `.vimperatorrc`?

I tried:
```
com! yd js liberator.execute('silent !youtube-dl --no-playlist '+buffer.URL)
no <a-l> :yd<CR>
```

It worked, sort of, only that FF stuck until the download was finished...

Anyone can help? Thanks.

**Comment by gregist** [comment]
should be `com! yd js liberator.execute('silent !start youtube-dl --no-playlist '+buffer.URL)`

**Comment by timss** [comment]
Good thing you were able to solve it so quickly! :)

Depending on your use case this might be relevant as well. I use it to open videos on YouTube with mpv, which uses youtube-dl as its backend.

https://github.com/timss/dotfiles/blob/master/.vimperatorrc#L223

**Comment by gregist** [comment]
Thanks! Your script is very helpful. I borrowed many lines. :)
