### ISSUE TITLE
Can't use Vimperator to full screen in YouTube

### ISSUE THREAD

**Issue by utku1** [vimperator/vimperator-labs#321]
This is not a serious issue but I am just curious about why might it happen.

On YouTube, when I use the Vimperator to click on the full screen button in a YouTube player (that is: F and some number) YouTube tells that full screen is unavailable.

However when I use the mouse for full screen, it works.

What is the reason for this behavior?

**Comment by gkatsev** [comment]
Weird. Probably an issue with how vimperator "clicks" on the element vs when you actually click on it with a mouse.

**Comment by utku1** [comment]
@gkatsev By the way, don't get me wrong but aren't you one of the developers? You're supposed to know the code no? (I don't mean any offense I just did not understood if you are one of the developers, why you don't know the reason for this)

**Comment by gkatsev** [comment]
Heh, I'm currently a maintainer sure but I didn't write most of the code and don't really know much of it and hadn't had a chance to look at the codepath for this yet. :)

**Comment by timss** [comment]
The javascript used on YouTube is at best arcane magic. It does not suprise me at all that it doesn't deal well with "unusual" behavior, such as not using the mouse to click a button.

**Comment by ratijas** [comment]
try to type:
`if`,
where i — driving vimperator to IGNORE mode,
f — youtube's own short-cut for full-screen.

**Comment by danielwuz** [comment]
@ratijas thanks for your advice, works for me!
