### ISSUE TITLE
Can't go to next 'find' result

### ISSUE THREAD

**Issue by Zekario** [vimperator/vimperator-labs#323]
I figured out that / does find, but I can't cycle through the results. I've tried everything I can think of, how do I do it?

**Comment by gkatsev** [comment]
Have you tried `n` and `N`?

**Comment by Zekario** [comment]
That just adds an n/N to the find result, am I doing it wrong?

**Comment by ratijas** [comment]
did you tried `help /`?  are you hitting `<CR>` (enter) when finish typing search pattern?  how vimperator reacts to your `n` and `N`?
or wait, are you trying to `/n`?  because it's for 'find n', not for find next.

**Comment by gkatsev** [comment]
Yeah, make sure you're hitting `<CR>` after entering your whole query before trying `n/N`.

**Comment by Zekario** [comment]
Pressing enter fixed it. Thanks!

**Comment by gkatsev** [comment]
Cool. Thanks. Closing.
