### ISSUE TITLE
buffer! list oversized, interwinning with gui elements

### ISSUE THREAD

**Issue by yroYor** [vimperator/vimperator-labs#324]
I'm using the (awesome) "Group your Tab" feature from Firefox <C-S-e> to have nice groups ready for all of my weekly activites.
Now, that means I have aboutly 14 groups of ~3-8 tabs each. For exemple I've 86 tabs in my buffer list.

But because of those many tabs, my buffer! list grows too big for my screen and is overlapped by the navigation menu / tabs menu when those are active. 

Here is a screen :
![bug-vimperator](https://cloud.githubusercontent.com/assets/10077203/10967074/4824abce-83b8-11e5-8cc8-91293cc089b6.png)

I would find it a nice solution to limit the height of this buffer! list to the half of the screen or to 15 tabs... Or even better to have a setting to set it.

**Comment by timss** [comment]
Decrease the entires listed with <kbd>b</kbd> or other commands using `set maxitems=N`, where 20 is default.

**Comment by yroYor** [comment]
Okay, thanks ! My bad.
