### ISSUE TITLE
Release a new version of vimperator on AMO

### ISSUE THREAD

**Issue by nagisa** [vimperator/vimperator-labs#326]
SSL lock does not show up anymore since the update to 42nd version of Firefox. 41st version used to show it.

**Comment by timss** [comment]
Have you updated to the latest version of vimperator, ref. #301 / #82df3a3 ?

**Comment by nagisa** [comment]
Latest Vimperator from https://addons.mozilla.org/en-US/firefox/addon/vimperator/ is last updated on 2015 August 24.

**Comment by timss** [comment]
Both AMO and releases here on Github should probably get a new build. @gkatsev ?

In the mean time, it's not very difficult to just compile it yourself.

**Comment by gkatsev** [comment]
We're now up to firefox 44 and a new verison has been uploaded, sorry for the wait.
