### ISSUE TITLE
If a textbox has not get been selected normal mode command gi results in a TypeError

### ISSUE THREAD

**Issue by arsenerei** [vimperator/vimperator-labs#33]
Firefox 32-33

Visited any page with a textbox that is not initially select and use "gi" in normal mode.  The following error is displayed:

> TypeError: m.getClientRects is not a function

Click on a textbox and click somewhere else so that the focus is lost. Hit "gi" and now it works properly.

**Comment by oniatsu** [comment]
Almost the same problem is occured in Firefox 35.0 with Vimperator 3.8.3.
But the error message is different. The following message is displayed:

> TypeError: 'snapshotLength' getter called on an object that does not implement interface XPathResult.

**Comment by oniatsu** [comment]
I tried again to use 'gi' with Vimeperator 3.8.3-a3, then the probrem was not occured.

**Comment by protrolium** [comment]
if i may ask, where did you get alpha 3 and how did you install it. i am having the problem with 'gi' you described with the different error message

**Comment by gkatsev** [comment]
Alpha 3 is available in github releases: https://github.com/vimperator/vimperator-labs/releases/tag/3.8.3-a3

**Comment by derenio** [comment]
@protrolium as @gkatsev has mentioned, the a3 version is a tag of this repository.
To build it and install do as follows:
```
cd **SOMEWHERE**
git clone https://github.com/vimperator/vimperator-labs/
cd vimperator-labs
git checkout 3.8.3-a3
make
# to install the created `xpi` file into your firefox type the below into its `command line`
:open file:///**SOMEWHERE**/vimperator-labs/downloads/vimperator-3.8.3.xpi
```

**Comment by gkatsev** [comment]
There's a pre-build XPI available in my link, also.

**Comment by protrolium** [comment]
thank you @gkatsev + @derenio ... I was also having problems with ' ]] ' and ' [[ ' and alpha 3 seems to have fixed it for now.

**Comment by gkatsev** [comment]
Seems to be fixed in master/a3. I'm not seeing this behavior anymore either. Going to close this for now. Please let us know if the issue persists or returns.

**Comment by royaso** [comment]
after update to vimperator  3.8.3-a3 ,the "gi" problem seems to work, but the ]] still not working , it just dont give the TypeError: 'snapshotLength' anymore. Using firefox 35
