### ISSUE TITLE
`:set tabnumbers` doesn't work on the newest version of firefox

### ISSUE THREAD

**Issue by cdepillabout** [vimperator/vimperator-labs#335]
It looks like a change in the formatting of a tab is causing the tab numbers to not be visible.

This is occuring with the following versions:

Vimperator:	3.10.1 (created: 2015/08/25 00:41:59)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by gkatsev** [comment]
I believe it's been fixed in master. I probably need to release a new version. I'll look at it this weekend.

**Comment by cdepillabout** [comment]
Thanks a lot!

**Comment by gkatsev** [comment]
There's a new version released today.
