### ISSUE TITLE
Scrolling broken on http://www.iquilezles.org/

### ISSUE THREAD

**Issue by Earnestly** [vimperator/vimperator-labs#341]
As the title says, on the website http://www.iquilezles.org/ I can't use `j` or `k` (or `C-d`/`C-f`) to scroll, does anyone else have this experience and if so, why might this be?

**Comment by timss** [comment]
Just thought I'd pitch in and say that it is working for me. 

Also, lots of interesting things on that site!

Vimperator 3.10.1
Firefox 42.0

**Comment by Earnestly** [comment]
The only change I make to default mappings is:
```
noremap h 5h
noremap j 5j
noremap k 5k
noremap l 5l
```

With the latest (https://github.com/vimperator/vimperator-labs/commit/5ef082033dae1a338149d87c0e4d0aa810542fea) build of vimperator it seems `hjkl` works again, provided I focus the content.  `C-d` and `C-u` still remain non-function.

It's also worth mentioning that `C-f` and `C-b` do work as well, does anyone know why only `C-d` and `C-u` are failing?

**Comment by timss** [comment]
<C-d> and <C-u> doesn't work for me either, it seems.

I would guess it's because <C-d> and <C-u> scrolls according to the `scroll` option which defaults to half a page. Seeing as the content on the website is in a seperated "box" of some kind with its own scrollbar, maybe this logic fails.

**Comment by gkatsev** [comment]
It's broken for me as well until I focus on the page. However, it's broken in the same way on a browser like chrome. I think it's just an issue with the page and not with vimperator.
