### ISSUE TITLE
Google steals keys that should be bound to vimperator events

### ISSUE THREAD

**Issue by ohjames** [vimperator/vimperator-labs#342]
1. Rebind tabprevious/tabnext to `,` and `.` in `.vimperatorrc`

    ```
    map , :tabprevious<CR>
    map . :tabnext<CR>
    ```
2. Type `o blah` to search for `blah` in google.
3. Wait for search results to appear then hit `,` to go to the previous tab.

Expected: the search bar is not focused so I should be taken to the previous tab.

Actual: The text ` ,` is added to the search box (a space and then `,`). However typing `gT` works as expected and does take me to the previous tab.

**Comment by ohjames** [comment]
You can also trigger it without the rebindings by hitting `/` to search for something on the google page. Instead of the search dialogue opening it adds the ` /` to the search box.

**Comment by john-banks** [comment]
@ohjames this also occurs on other pages with search. Trying to search on https://docs.angularjs.org/guide/directive results in entering insert mode.

**Comment by jey** [comment]
I'm affected by this annoying bug too.

Also, why does the page keypresses events in Normal mode (not Ignore mode) anyway? :-/

**Comment by protrolium** [comment]
Yes I have noticed this behavior in Google Search, keybindings are hijacked by the search query input field. I guess there is no easy way to make vimperator somehow ignore this feature of Google's ?

**Comment by ohjames** [comment]
Never had/have the issue in Pentadactyl so it's possible. Weird how the search bar only seems to steal non-alphanumerics.

**Comment by j127** [comment]
This happens on Slack.com too. Pressing `/` enters the message box and you can't `ESC` out of it.

**Comment by jey** [comment]
Applying PR #287 fixes this issue, mostly. There are still some minor quirks, such as the key sequence `i/` opening Quick Find instead of sending a `/` keypress to the page.

**Comment by protrolium** [comment]
@jey how do I apply the changes made in that Pull Request? Hopefully this can be added to master soon.

**Comment by ratijas** [comment]
hey there.  i found one workaround for sites stealing keys.
```vim
map <M-;> :
imap <M-;> <Esc>:
```
while `<S-;>` (or simply `:`) can be entered as character in an input field, `<M-;>` cannot and is considered a shortcut.  well, that does not work with `o`, `t` and other zero-click features, but at least you have access to vimperator command line.

**Comment by Enzime** [comment]
@jey, the quick find box is Firefox's binding not vimperator's which opens the find in the command line

I'm just trying to think of how to override Firefox's binding but as far as I know there's no easy way without implementing a <Pass> and mapping / to <Pass>. I may take a shot at trying to fix this in future as I have a few ideas

**Comment by ohjames** [comment]
This has been fixed in the latest release for me! I'll leave this issue open a few days for others to verify then I'll close it unless I hear anything negative in response. Checked the commit log and can't identify which one has fixed this issue.

**Comment by gkatsev** [comment]
@ohjames thanks for the confirmation.
Going to close this for now. We can re-open if the issue comes back.
