### ISSUE TITLE
Make 'gi' keys insert at the end of input fields

### ISSUE THREAD

**Issue by jody-frankowski** [vimperator/vimperator-labs#345]
I think 'gi' should insert at the end of input fields, just like hints do. It is more natural in my opinion.
What do you think?

**Comment by ratijas** [comment]
no.  it's persistent now, and leave it as it is.  for example, if i've already entered some text, after went to another page (maybe to copy something) and return back, i'd expect `gi` to bring me back to the same location.  if you want append text to the end, `<Page down>`/`<Fn-Down>`/`<⌘-Down> (OS X)` is here to help you.

**Comment by jody-frankowski** [comment]
Indeed. But 'gi' inserts where you were, only if you were inserted before. When you do a new tab search, doing 'gi' inserts at the beginning of the search field, even though the search field already contains your keywords. Am I making myself clear?

**Comment by ratijas** [comment]
yeah, i see.  you mean to insert cursor to the end if the search field comes already preloaded with keywords.

but here raises the question: how on earth we gonna determine if it came preloaded, or we altered content?

**Comment by jody-frankowski** [comment]
Yes that is it. Well, I don't know the existing logic, but maybe vimperator could insert at the end of the field (preloaded or not) whenever there was no previous inserts. But that's just pure speculation.

**Comment by timss** [comment]
See #192. 

As suggested, you can do this using `noremap gi gi<End>`.

**Comment by jody-frankowski** [comment]
Well it seems to me this patch https://github.com/dkasak/vimperator-labs/commit/a439dfadeba8bcc2949cc4ed874ee7d4aed721e9 does exactly everything we all want.
But yeah the noremap trick works really good.

**Comment by timss** [comment]
Great. Might want to close this issue then.
