### ISSUE TITLE
Latest version of Nightly [45.0a1 (2015-12-02)] does not support `complete=t`

### ISSUE THREAD

**Issue by danemacmillan** [vimperator/vimperator-labs#346]
In this morning's version of Nightly it appears that Tab Groups have been removed, which has long been in the works. They worked yesterday, but as of this morning's update, they do not. This is brought up because it actually has an impact on Vimperator's `complete` option. My `complete` option is set to `complete=stlS`. With `t`, which suggests buffers, enabled none of the browser's bookmarks are being suggested, but the actual buffers get suggested, alongside the keywords. When removing the `t` option, so it reads `complete=slS`, I get bookmark suggestions back, but of course no buffer suggestions.

It seems Vimperator has some kind of dependency on Tab Groups. Here is the error I get:

![](https://i.imgur.com/OyrJH1C.png)

My current workaround is to just set `complete=slS` and lose buffer support.

Edit:

I should clarify that it *does* support `complete=t`, but just not in combination with others. For example, `complete=stlS` prevents bookmarks from being suggested.

**Comment by gkatsev** [comment]
This should be fixed in latest vimeprator/firefox released today.
