### ISSUE TITLE
Open hint link in program of choice

### ISSUE THREAD

**Issue by stagnation** [vimperator/vimperator-labs#347]
Hello

I would like to be able to open the url of a hint in an external program.

I often use `;y` to copy the url from a link to clipboard and then open the link from clipboard in one of many programs. For example youtube video in mpv on the laptop to watch it now, or a youtube music video that I want to open in mpd on the  server. I have not found a way to do this distinction via soap or the like since the urls look practically the same. 

By having this functionality in vimperator I would save a couple of key presses in my wm, and it would open up for very flexible link opening.

I have looked briefly in hints.js but my knowledge of javascript is to limited to propose a patch.
one way to do it would be to have a method/function that shows hints and sleeps until a hint is selected and loads it into clipboard then continues executing the map.

then a simple `map :hint_to_clipboard()<cr>:!mpv $(xclip -o)<cr>` would be feasible.
or a similar call through `:js`.

Better yet would be to have a variable with the url that can be used instead of the clipboard, but clipboard is enough, I can write a script to store away the contents of clipboard and restore after the call.

- spill on irc

**Comment by shedatc** [comment]
Such a change would also help to open a patch in an external program even when the HTTP response advertise Content-Type: text/plain.

**Comment by V-J-P** [comment]
You should be able to do that kind of stuff if you set your shell to interactive (set :set shellcmdflag=-ic)

Makes the :! and :run able to execute mpv with interaction, so it is possible to put this in a vimperatorrc file and execute it on a button hit.

I'm looking for such a solution myself, I just don't like changeing vimperator for it, I'd rather make a script for mpv to take away the interaction. I'm desperately looking for a client/server solution on mpv. So in my opinion this is not a vimperator issue, its rather a mpv issue. 

I'm dedicating some time to look into this, I've got the itch you can actually manage this with a special profile flag.

**Comment by V-J-P** [comment]
Hey folks a heads up after some digging,
There is a Firefox addon called [Watch with MPV](https://addons.mozilla.org/en-US/firefox/addon/watch-with-mpv/), I did a [pull request](https://github.com/antoniy/mpv-youtube-dl-binding/pull/24) that adds it in the menubar so the function is available through :emenu . So you guys just need to wait until the author merges it into the his project and signs it with mozilla.

If you can't wait, you can build my fork and add it to your browser extensions.

**Comment by timss** [comment]
That can be handy, nice. 

Currenly I'm just using a scriptable parser for xdg-open called SOAP. Will probably continue to do so, as it works for other stuff than mpv too (e.g. PDF or pictures). 

https://github.com/timss/dotfiles/blob/940ef7c01dd3827ea8241ef627ed115351ae0c6b/.vimperatorrc#L228

**Comment by V-J-P** [comment]
AAAAH, the vimperator plugin I was silently looking for, hidden deep down in a .vimperratorrc file!
`hints.addMode("P", "Open with SOAP:",` I LOVE YOU!
I just copy this into my rc file and hope you will transform it to a plugin... (if possible)

**Comment by timss** [comment]
Hehe, glad to help. I suppose it could be a plugin, but not sure if/when I would create one, you should certainly not hold your breath. Other than being easier to distribute, there is nothing wrong with just having it in your RC file.

If you're only interested in using it together with mpv, you don't really need SOAP. From https://www.reddit.com/r/linux/comments/3xfcsb/psa_firefox_now_support_youtube_1080p_60fps_with/cy5d4ek:

    javascript <<EOS
    hints.addMode("P", "Open with mpv (1080p):", (elem, loc) => liberator.execute("silent !mpv --fs --ytdl --ytdl-format='(mp4)[height>=720][height<=?1080][fps>=30]+bestaudio' '" + loc + "' &", null, true));
    EOS

Change the contents of `liberator.execute()` if necessary. All you really need to care about is the `silent` in the beginning, `loc` as an argument to mpv and the `null` plus `true` positional arguments.

Actually, all of this is probably a good candidiate for the wiki. I'll look into adding it later.

**Comment by V-J-P** [comment]
No actually, I'm using it for everything but MPV. [youtube-dl`s supported site list](https://rg3.github.io/youtube-dl/supportedsites.html) is far too much to regex and keep up to date with. I just like beeing able to send audio to mpd and images to feh!

**Comment by timss** [comment]
Indeed. Easy to expand :)

**Comment by stagnation** [comment]
Thank you both very much. This solves my problem
