### ISSUE TITLE
Firefox 42: Vimperator could not be verified for use in Firefox.

### ISSUE THREAD

**Issue by pjotrek-b** [vimperator/vimperator-labs#348]
Vimperator (v3.9) stopped working after upgrading from FF v39 to FF v42.
In the AddOns list, it says:
> Vimperator could not be verified for use in Firefox. Proceed with caution.

Yet, it seems like the addon is deactivated, but I don't find any way to activate it.

Any help greatly appreciated.
Thanks in advance :)

**Comment by pjotrek-b** [comment]
Updated Vimperator to "v3.10.1.1-let-fixed" and now it works again.

Sorry, thought I had the latest version, because on [Vimperator Labs website](http://www.vimperator.org/vimperator) it offers v3.9 in a way that looks like "download most recent version".
Going for "other versions", I then saw v3.10 on [Addons (at Mozilla.org)](https://addons.mozilla.org/en-US/firefox/addon/vimperator/).

Where do I find a manual "update" option for Vimperator in AddOns in Firefox?
(I don't want to enable automatic updates)

Thanks again :)

**Comment by maxauthority** [comment]
Oh I didn't see gkatsev released a new version :) I'll update the homepage
tomorrow (although I really don't like names like 3.10.1.1-let-fixed.
Wouldn't something like 3.10.2 also be suffice for those small fixes? (or
even 3.11, which we should call "Windows" as the nickname ;)

**Comment by timss** [comment]
Might as well replace the direct download URL to be an link to AMO and /releases here on Github, so you don't have to manually update it when there's a new release.

**Comment by gkatsev** [comment]
Closing as it's been "fixed"
