### ISSUE TITLE
ability to temporarily hide bar

### ISSUE THREAD

**Issue by Zekario** [vimperator/vimperator-labs#350]
When watching a fullscreen video, Vimperator pushes it up a bit. This can be annoying, and I was wondering if there was a way to temporarily hide the command bar.

**Comment by gkatsev** [comment]
We've gotten it merged into master. See https://github.com/vimperator/vimperator-labs/pull/328/ and https://github.com/vimperator/vimperator-labs/pull/338/.
I guess we probably need to do a new release soon, or at least a prerelease.

**Comment by maxauthority** [comment]
I don't think we really need pre-releases, just keep numbering them 3.11,
3.12, 3.21, ... (until we need to be like Linus torvalds, and finally
introduce a new 4.0 version :)

**Comment by gkatsev** [comment]
@maxauthority yeah, by prerelease I mostly just meant make a new xpi and post it here on github as opposed to just publishing on AMO.
