### ISSUE TITLE
Text search command | search forward `/` (forward-slash)  | not working on some websites.

### ISSUE THREAD

**Issue by fohrums** [vimperator/vimperator-labs#351]
On websites like http://rap.genius.com/, the search function for vimperator with it's keybinding `/` doesn't work properly.

What will happen is you'll be re-directed to the site's own search bar instead rather than having vimperator's search bar be brought up via `/`.

Other Throughts
=
If I can recall, I believe **pentadactyl** didn't have this problem.

**Comment by jody-frankowski** [comment]
Same thing happens on soundcloud.com. If I remember correctly, the maintainer took the let-the-website-keybindings work. In my opinion this is quite annoying in this particular instance.

**Comment by fohrums** [comment]
... But there's got to be a way for this to be enabled somehow via a setting inputted 'vimperatorrc' config-file

**Comment by jamalis** [comment]
Gee thanks a lot, with the post above I became rather well-informed about the discussions.
http://fotorumahmewah.com

**Comment by gkatsev** [comment]
I believe this has been fixed in a recent version. Going to close this but let me know if this isn't the case and I can re-open.

**Comment by gkatsev** [comment]
See #342.
