### ISSUE TITLE
Firefox 43; Icons unrecognisable in the statusbar

### ISSUE THREAD

**Issue by dschrempf** [vimperator/vimperator-labs#353]
Hello,

this has already been an issue some years ago.  In Firefox 43, the icons in the status bar are compressed again.  It looks the same as reported in https://github.com/vimperator/vimperator-labs/issues/15.

Cheers,
Dominik

**Comment by amosbird** [comment]
+1

**Comment by gkatsev** [comment]
Closing as a duplicate of #15. Unless someone figures a workaround, maybe some super fancy css magic, I'm not sure there's anything we can do.
