### ISSUE TITLE
Firefox 43; Vimperator could not be verified for use in Firefox. 

### ISSUE THREAD

**Issue by tsaber** [vimperator/vimperator-labs#354]

**Comment by gkatsev** [comment]
Thanks. I guess we really need to make a new release besides the fixes in master we need to get it signed.

**Comment by tsaber** [comment]
I'd much appreciate that. Using vanilla firefox is weird now.

**Comment by egolus** [comment]
as pentadactyl faces the same issue, @iegorka explained in https://github.com/5digits/dactyl/issues/99 how to get around the check for now:

go to **about:config** and set **xpinstall.signatures.required** to **false**

**Comment by gkatsev** [comment]
I've done a release as part of #352. Can take a couple of days to propagate, you can try grabbing the XPI from github releases.
