### ISSUE TITLE
qmarks for multiple sites broken?

### ISSUE THREAD

**Issue by zeltak** [vimperator/vimperator-labs#362]
Hi
i have recently come back to vimperator and noticed that the qmark syntax that i used a while back to open multiple sites with one qmark seems broken. for example:

```
silent qmark 6 http://woot.com | http://1saleaday.com/ | http://mobile.dailysteals.com/ | http://slickdeals.net/ | http://www.priceplunge.com/ | http://www.amazon.com/mobile-apps/b?ie=UTF8&node=2350149011 | http://deals.woot.com/
```

is this syntax correct, has it changed? what am i missing?

thx alot

Z

**Comment by timss** [comment]
Already solved on IRC, but for reference the character used to designate groups of URLs is defined by the `urlseperator` option. The default is `,\\s`, e.g. a `","` is to be used.

    silent qmark 6 http://url1.com, http://url2.com, ..

https://github.com/vimperator/vimperator-labs/blob/0e4e5224ae828080c478f0f47bdb9c8c258b22ec/common/locale/en-US/marks.xml#L293

**Comment by timss** [comment]
I believe this may be closed.
