### ISSUE TITLE
Is it possible to change keybindings?

### ISSUE THREAD

**Issue by fosskers** [vimperator/vimperator-labs#365]
I use a Colemak keyboard, and thus having up and down mapped to J and K is slightly inconvenient for my fingers. Is there a way to change this?

**Comment by timss** [comment]
Yes, but keep in mind when to use map and noremap in situations like these. See `:h map` for more information.

    noremap e k

Lucky for you, seems like someone already did most of the job :-)

https://github.com/lalopmak/lalopmak-mappings/blob/master/firefox/colemak.vimperator

**Comment by fosskers** [comment]
Interesting, thanks for that. There are really only a few remapping I'd need to do.

Where would one write said settings?

**Comment by timss** [comment]
In `~/.vimperatorrc`. You can also put it in a seperate file, and use `source ~/.colemak.vimperator` if you'd like.

**Comment by fosskers** [comment]
Done! While you're here, is there a nice way to cycle through the tabs? dwb and qutebrowser use Shift+j/Shift+k

**Comment by timss** [comment]
There are many. <kbd>b</kbd> is pretty cool, but there's also `gX` mappings:

liberator://help/tabs#changing-tabs (`:h changing-tabs`)

**Comment by klaplong** [comment]
I use `.` and `,` for tab switching.

**Comment by fosskers** [comment]
How did you set that, @klaplong ? I'm still very new to vimperator config.

**Comment by timss** [comment]
noremap . gT
    noremap , gt

Add this to your `~/.vimperatorrc`.

**Comment by fosskers** [comment]
Done, thanks a ton.
