### ISSUE TITLE
Wildoptions?

### ISSUE THREAD

**Issue by RomanADavis** [vimperator/vimperator-labs#366]
When I try to use ":set wildoptions=', at the top, the terminal says, no such option, is this a change from an earlier version?

Using the current stable release of firefox. I'm new to vimperator, so I haven't modified it much. It's possible that this has to do with some changes I've made to firefox through addons or the config panel.

Any ideas?

**Comment by gkatsev** [comment]
`wildoptions` were removed in 2011 in vimperator 3.0: https://github.com/vimperator/vimperator-labs/blob/cd414dd5c675242441a1d594bc802158e1454ab6/vimperator/NEWS#L209
