### ISSUE TITLE
Some keybinds not working in latest firefox aurora

### ISSUE THREAD

**Issue by vityas-off** [vimperator/vimperator-labs#368]
For example copy url (y) will not work after using new tab (t) and many other keybinds are broken too.
This is the error i get:
Typeerror: 'stopPropagation' called an object that does not implement interface event
Input mode seems to be broken too and after some test browser just becomes unresponsible
Used latest firefox aurora and vimperator from git

**Comment by ghallberg** [comment]
Also in aurora, keypresses in input fields (google search bar for example) are caught by vimperator instead. Trying to type 'd' just closed my tab etc.

**Comment by gkatsev** [comment]
There was a new release of vimperator. Please try it out. Thanks.

**Comment by notjosh** [comment]
This is occurring for me still off latest master (0f47a14), as well as from AMO (3.11.3) in Firefox 45.0b3. Tried clearing out some local prefs, but doesn't seem to make a difference. Any thoughts?

**Comment by notjosh** [comment]
45.0b5 seems to have resolved this? Either that, or my install seemed to have felt the love of Valentine's Day and decided to play along again :)
