### ISSUE TITLE
Incompatible with Findbar Tweak addon

### ISSUE THREAD

**Issue by sindikat** [vimperator/vimperator-labs#370]
Vimperator search (bound to <kbd>/</kbd>) is incompatible with [Findbar Tweak](https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) addon. When I press <kbd>/</kbd>, enter some text then press <kbd>Enter</kbd>, nothing happens. If I press <kbd>Enter</kbd> again, this error is printed:

    TypeError: window.gFindBar.browser.finder._highlight is not a function

It would be great to somehow be able to use all Findbar Tweak features (such as search highlights marked as thin horizontal lines on the scrollbar) with Vimperator.

**Comment by gkatsev** [comment]
Heh, I noticed that too. I wonder if the fix is similar to what @quicksaver did in #369

**Comment by Quicksaver** [comment]
I'll take a look. :)

**Comment by Quicksaver** [comment]
FYI, it's definitely not the same thing as in #369. Vimperator's finder.js file is... very messy. I can help with cleaning it up a bit, nothing will ever work with FBT until that happens (for instance, there's a lot of old code there that hasn't been valid/needed since Firefox 24).

**Comment by gkatsev** [comment]
Aww, too bad. Any fix that cleans up the code would be *amazing* and *highly* appreciated.

**Comment by Quicksaver** [comment]
I'm actually already working on that. Let me see what I can come up with until tomorrow. ;)
