### ISSUE TITLE
Keybindings in pdf.js

### ISSUE THREAD

**Issue by jody-frankowski** [vimperator/vimperator-labs#374]
I'm not sure if it's vimperator that sets those keybindings, but I feel pdf.js is missing some important keybindings:
G, gg, ^d, ^u, ^f, ^b.

**Comment by gkatsev** [comment]
Yep, `G`, `gg`, etc. are set by vimperator. I'm not certain that vimperator can actually do anything with pdfjs because it's a plugin. However, it may be possible. Someone would need to investigate.

**Comment by jody-frankowski** [comment]
If I remember correctly, it's a behavior that I saw in pentadactly, so that would be awesome to see it in vimperator too.

**Comment by gkatsev** [comment]
This has been fixed by #397.

**Comment by jody-frankowski** [comment]
Awesome, thank you very much.
