### ISSUE TITLE
'gui' option no longer recognized

### ISSUE THREAD

**Issue by lsm5** [vimperator/vimperator-labs#375]
I just updated to Firefox 44.0. Now I see that the option 'gui' is no longer recognized.

My .vimperatorrc has `set gui=none` which worked just fine before the upgrade.

**Comment by aldrik** [comment]
I also came across this, it seems like a duplicate of #352 (following the steps there fixes the issue).

**Comment by gkatsev** [comment]
@aldrik thanks. Yeah, seems like the issue is that vimperator is out of date. I'll be taking time tonight to make sure that everything works and releasing a new version of vimperator.
Closing as a dupe of #352 for now.

**Comment by lsm5** [comment]
@aldrik @gkatsev rocking, thanks!
