### ISSUE TITLE
Firefox 44 breaks vimperator

### ISSUE THREAD

**Issue by johntyree** [vimperator/vimperator-labs#378]
I only had it installed for a few minutes before I panicked and reverted to 43, but I noticed at least the following on 44.0.

- Every command causes a `SyntaxError: attr2` error message
- Hints do not show up at all
- The location bar does not hide

**Comment by gkatsev** [comment]
Thanks. This is a dupe of #352.

**Comment by johntyree** [comment]
Oh, Sorry. I assumed this would be new, of course people have been testing nightlies and so the issue is old by now. My fault. :)

**Comment by gkatsev** [comment]
Heh, no worries. I've updated the issue title so hopefully it'll be easier to find.
