### ISSUE TITLE
firefox update breaks everything

### ISSUE THREAD

**Issue by thrisp** [vimperator/vimperator-labs#380]
Title says it all. 

On load of firefox, something loads, but complains about everything in .vimperatorrc as being unrecognized options, with everything being a part way between vimperator as configured and firefox defaults; I had to disable the plugin.

**Comment by gkatsev** [comment]
See #352. I've released a new version to AMO but it'll take a couple of days to get verified.

**Comment by ivotron** [comment]
Is there a way to get the signed xpi ourselves?

**Comment by aspel** [comment]
@ivotron use 3.11
https://github.com/vimperator/vimperator-labs/releases

also need to disable xpi verify

**Comment by gkatsev** [comment]
I'm going to look at signing it and uploading a signed XPI tonight. Meanwhile, yes, you have to disable the signing verification.

**Comment by ivotron** [comment]
@aspel I thought `xpinstall.signatures.required` was gone in 44. I was wrong :) Thanks!

**Comment by wngr** [comment]
I installed 3.11, but it's still absolutely unusable.

Am I the only one experiencing that?

**Comment by aspel** [comment]
Try first uninstall and restar FF

**Comment by gkatsev** [comment]
uninstalling and reinstalling may help. I know that while it makes it work, there are still some issues with it, though, I think the most commonly used things should work.

**Comment by wngr** [comment]
I tried the removing, restarting, installing, restarting cycle now a couple of times.

At first it's behaving ok, but after the first tab strange things happen.

I cloned this repo && make && installed 3.11..

Any other ideas?
