### ISSUE TITLE
Huffman encoding for hints

### ISSUE THREAD

**Issue by lestrozi** [vimperator/vimperator-labs#381]
Hi
I'm interested on using n-ary huffman enconding for the hints. So we'd never have "C" and "CA" hints, for instance (because, in this case, if you need to use "C", you need to type "C&lt;Enter&gt;").
Is there any work on that already?
Would you be interested on a pull request for this feature using https://github.com/lydell/n-ary-huffman/blob/master/index.js (MIT license)?
Thanks

**Comment by gkatsev** [comment]
I think this sounds like a great opportunity for a plugin but we don't want the extra complexity in vimperator core right now.
Thanks.
