### ISSUE TITLE
No "Smart Completions" and "Search Keywords"

### ISSUE THREAD

**Issue by Jade-Shan** [vimperator/vimperator-labs#383]
When I use the `:o` command there is no "Smart Completions" and "Search Keywords".

- My Firefox version is "44.0 for Ubuntu canonical - 1.0"
- My Vimperator version is "3.10.1.1-letfixeds"

**Comment by gkatsev** [comment]
Thanks. That's a known issue. We're awaiting the release of version 3.11 of vimperator. See #352.
