### ISSUE TITLE
Vimperator 3.10.1.1-let-fixed not working in firefox 44

### ISSUE THREAD

**Issue by bobf32** [vimperator/vimperator-labs#385]
follow hint command not working, doesn't highlight links, brief text appears in status line 'SyntaxError: attr2'

help command doesn't display help, brief text appears in status line 'Sorry help file undefined not found'

**Comment by YHRen** [comment]
I have encoutnered the same problem after firefox updated to 44.
Also, composing in gmail became strange.
"delete" and "enter" became selecting texts.

**Comment by bobf32** [comment]
I am totally getting the same thing: entering text in any kind of web form text field is a nightmare. I usually give up and edit in external editor and paste in.

**Comment by YHRen** [comment]
Me too. I am using "it's all text" with MacVim.
It works perfectly fine with most of text fields.
But google's composing window is somehow different and 
I cannot invoke MacVim from there.
Hopefully this issue can be resolved soon.

**Comment by gkatsev** [comment]
Please update to vimeprator 3.11. It's now available on AMO. Also, see #352.
