### ISSUE TITLE
Autocomplete doesn't work with Firefox 44

### ISSUE THREAD

**Issue by MPW1412** [vimperator/vimperator-labs#386]
Hello,

I just upgraed Firefox to version 44 on Ubuntu 14.04.

Unfortunatly Vimperator doesn't work with this version properly. The autocomplete function of urls doesn't work. When I press "o" or "t", vimperator doesn't pop up suggestions.

Thanks for reading
MPW

**Comment by gkatsev** [comment]
What version of vimeprator are you running?

**Comment by MPW1412** [comment]
Ah I got it: It was the first start of firefox 44, so it upgraded the plugins in background and now after a second restart of firefox, it work's properly again.

This can be closed! Sorry for this, should have tested it more intensivly.
