### ISSUE TITLE
v44 breaks link hinting?

### ISSUE THREAD

**Issue by jonross** [vimperator/vimperator-labs#388]
Firefox just self-updated to v44 and has become nearly unusable.  About half the links on the average page don't show hints.  I've downloaded Vimperator 3.11.2 from https://addons.mozilla.org/en-US/firefox/addon/vimperator/ , to no avail.

It's hard to tell what's different about these links; from watching behavior in JIRA, ReviewBoard and other apps, it seems to be that links added after the page loads don't get hints.  (More precisely, they have a numbered hint that you can follow, but it doesn't appear.)  Has anyone else seen this / know a fix?

Thanks,
Jon

**Comment by gkatsev** [comment]
firefox 44 has a bunch of incompatible changes that we need to fix. It's possible that one of these incompatibilities makes the hinting not function fully.

**Comment by MoSal** [comment]
As I mentioned [here](https://github.com/vimperator/vimperator-labs/issues/289#issuecomment-166168603), I've noticed this brokenness while browsing Twitter when FF 44 was still in beta.

So, yes, hints seem to be broken. Especially on (dynamic) sites.

**Comment by gkatsev** [comment]
@MoSal is the breakage on twitter that buttons like `home` and `notifications` at the top don't have the hint numbering?

**Comment by v1kn** [comment]
The issue with following links is very noticeable. For example:  

* none of the links on `startpage` search engine have numbers. they can be accessed by typing words that match the links, but this is not ideal. [screenshot](http://i.imgur.com/5mx4aZW.png)
* most top bar navigation in reddit (hot, new, logout etc) do not have links. again, typing strings that match the links will focus the hint on it. [screenshot](https://i.imgur.com/sfhs5tg.png)

**Comment by gkatsev** [comment]
@v1kn thanks for posting with examples with screenshots. Greatly apprechiated.

**Comment by j127** [comment]
Probably related: hovering over links doesn't show the destination URL at the bottom left of the screen.

**Comment by gkatsev** [comment]
@j127 it apparently got moved to the right sometime. Also, the liberator toolbar may have gotten disabled altogether.

**Comment by j127** [comment]
Strange. It's difficult to see it there. If I disable Vimperator, it goes back to the usual position and color.

**Comment by gkatsev** [comment]
Let's discuss the url in another issue. It isn't relevant to hinting. The native statusbar is disabled for some reason, which I think may be a bug.

**Comment by kesdoputr** [comment]
I have maybe same questions on http://exhentai.org/ here is the screen shot.(vimperator ver 3.11.3)
With fireofox 43.0.4 [http://i.imgur.com/3jXvvSH.jpg](url)
With firefox 44.0 [http://i.imgur.com/4tHx8MV.jpg](url)
When use 44 i can't select those books by hints.

**Comment by gkatsev** [comment]
@kesdoputr yep, most likely the same problem.

**Comment by gkatsev** [comment]
Closed by #409.

**Comment by MoSal** [comment]
Could be unrelated, but some sites still have problems with hints.

For example, hints in articles in http://thedailybeast.com (e.g. [this one](http://www.thedailybeast.com/articles/2016/01/29/a-tale-of-two-twitters.html)) appear chopped from the top with no background set.
![Screentshot from thedailybeast.com](https://archive.org/download/unsorted_files/tw_hints.png)

**Comment by timss** [comment]
For anyone curious, it can be hard to see in @MoSal's picture, but there are white hintchars in the highlighting that are cut off.

**Comment by kmorihiro** [comment]
In @MoSal 's case, a following highlight fixs the problem.

`hilight -append Hint line-height: 1em;`

A fundamental issue is that top level css affect hintchars, so we should reset hintchars' css anyway.
e.g. `body { line-height: 0 !important}` affects hintchars.
