### ISSUE TITLE
3.11.2 breaks keybindings

### ISSUE THREAD

**Issue by orbisvicis** [vimperator/vimperator-labs#389]
These following keybindings no longer work after upgrading to 3.11.2 (same firefox version, no new addons):
```
nnoremap    <A-u>       <C-p>
nnoremap    <A-b>       <C-n>

nnoremap    <A-j>       <C-d>
nnoremap    <A-k>       <C-u>

nnoremap    <S-j>       :ju<Return>
nnoremap    <S-k>       :ju<Return>;o

nnoremap    <A-d>       :q<Return>

nnoremap    <A-[>       :tabopenleft<SPACE>
nnoremap    <A-]>       :tabopenright<SPACE>

nnoremap    <A-h>       H
nnoremap    <A-l>       L

nnoremap    <A-6>       <C-6>

nnoremap    \<          :tabhistory back<Return>
nnoremap    \>          :tabhistory forward<Return>
```

But this works
```
cnoremap    <A-j>       <down>
cnoremap    <A-k>       <up>
```

Looks like Shift-prefixed, Alt-prefixed and Backslash-prefixed keybindings are broken, but only in normal mode.

*- Firefox 43.0.3*

**Comment by gkatsev** [comment]
Weird. My `<a-a>` mapping still works. But yes, it's possible something is broken.

**Comment by orbisvicis** [comment]
Mark this closed. I should've restarted firefox after upgrading, or something? Regardless, all the bindings are working.

**Comment by gkatsev** [comment]
Ah cool. Glad you figured it out.
