### ISSUE TITLE
Firefox 44 doesn't show where links lead to anymore in bottom left corner of screen when using ;;

### ISSUE THREAD

**Issue by Neftas** [vimperator/vimperator-labs#399]
After the update to 3.11.2, Firefox 44 does not show where links lead to when you hover over them with the mouse or use `;;` to select the link. This used to be displayed in the left bottom corner of the screen.

Disabling Vimperator fixes this.

I use code like [in this answer on StackExchange](http://superuser.com/a/706543/267090) to hide the Vimperator status bar, and only show it when I need it. Was the link preview in Firefox disabled on purpose because it also shows in the Vimperator status bar, or is this a bug?

**Comment by gkatsev** [comment]
1. vimperator just got native hiding of status bar so you could try using that.
2. when the vimperator bar is present, it seems that this was moved to the right of the bar
3. the fact that the native firefox statusbar isn't showing is really the bug here, I believe.

**Comment by Neftas** [comment]
When I say "status bar in Firefox that displays the target link", I mean:

![statusbarlink](https://cloud.githubusercontent.com/assets/8035319/12698201/de7ae6ca-c796-11e5-92f5-002de183c0b4.png)

Just so that we are on the same page. I have changed the code in `.vimperatorrc` to show the target link in the Vimperator status bar after using `;;` and hides the bar again after a couple of seconds, making use of the new API. That is a workaround I can live with.

**Comment by gkatsev** [comment]
Yep, that's the native firefox status bar. I'm not sure where it went.

**Comment by demokritos** [comment]
@Neftas you can make the link preview appear at that position by setting showstatuslinks to 3.

**Comment by gkatsev** [comment]
@demokritos ha! thanks. Didn't know about that option.
Aah, it was your fix. I guess it got lost from the changelog. Looks like this is working as designed. Just tried it locally.

**Comment by demokritos** [comment]
@Neftas use the below code instead of the link's code.
```noremap <silent> <F8> :js statusline.setVisibility(statusline.setVisibility.TOGGLE)<CR>```

**Comment by Neftas** [comment]
@demokritos Thanks, that works like a charm! As to hiding the statusline, I rewrote the script I linked to to use the new API, but thanks for pointing it out explicitly.

**Comment by timss** [comment]
@Neftas Mind posting the updated version?

**Comment by Neftas** [comment]
@timss here it is.

    :js << EOF
    function toggle_bottombar(p) {
        if (p === 'on') {
            if (!statusline.setVisibility.currVisibility) {
                statusline.setVisibility(statusline.setVisibility.TOGGLE);
            }
            return;
        }
        if (p === 'off') {
            if (statusline.setVisibility.currVisibility) {
                statusline.setVisibility(statusline.setVisibility.TOGGLE);
            }
            return;
        }
        statusline.setVisibility(statusline.setVisibility.TOGGLE);
    }
    toggle_bottombar();
    EOF

I used `statusline.setVisibility.TOGGLE` rather than `MODE_ON` or `MODE_OFF`, because the latter two didn't do what I expected them to do (i.e. show and hide the statusline, respectively).

But even then, the code doesn't work properly. I noticed that it won't work on YouTube for instance, it starts to complain that an object can no longer be used. (Or something like that, the error shows for like a tenth of a second and then disappears). So I am back to the original code from StackExchange. Maybe someone who knows more about Vimperator can comment what is wrong with the code above?

**Comment by klaplong** [comment]
@neftas The code within both outer if-statement (the P checks) is identical. Also, you are not using `else if`, which means that if your status bar was visible, it will toggle to hide. But then it will not be visible, and the next if statement will pass, which means it will toggle to show. 

Try changing it to `else if`.

**Comment by gkatsev** [comment]
Also, we're probably changing how this is implemented. `TOGGLE` should still work but `currVisibility` will be going away. Also, an option is going to be added for it.

**Comment by Neftas** [comment]
@klaplong My knowledge of JavaScript is not great, so bear with me:

* The code in the two statements that check the value of parameter `p` doesn't look the same: one is checking if `p` is equal to the string `on` and the second one is checking if `p` is equal to the string `off`, right?
* If the statusline is invisible, and parameter `p` is set to `on`, it will toggle the statusline. Then it reaches the `return` statement, and the function will exit, right? So it won't reach the second `if`, if the first `if` evaluates to `true`.
* Same goes for when the statusline is visible, and parameter `p` is set to `off`: it will toggle the statusline, hiding it, and then reach the return statement, exiting the function.
* Only if parameter `p` is not set or is not equal to either string `on` or string `off`, will it reach the closing statement of the function, and make the statusline either visible or invisible, depending on the current situation. In fact, this statement is only carried out when the JavaScript is first loaded, thus hiding the statusline on startup.

I don't think an `else if` statement is mandatory, because we are using `return` statements to make sure the two `if` blocks cannot be reached in one call, although an `if - else if - else` construction would probably be better style (and easier to read). Anyway, let me know if I'm not understanding something correctly.

**Comment by klaplong** [comment]
@Neftas Yes, you're right. I looked over the return statements.

I do like `if-else if` better, but this style is exactly the same under the covers. The code looks fine.
