### ISSUE TITLE
j k scrolling error

### ISSUE THREAD

**Issue by crunchiebones** [vimperator/vimperator-labs#400]
i updated to 3.11.2 and now i get 'ReferenceError: Buffer is not defined' when I press the j k keys.

**Comment by gkatsev** [comment]
Are you using something like the smoozie plugin?

**Comment by crunchiebones** [comment]
Oh.. yeah it's fine now i've removed it

**Comment by gkatsev** [comment]
We actually fixed that issue in #393.

**Comment by gkatsev** [comment]
Also, I just released a new version vimperator with that fix. You can either grab it from github (you'll have to disable signing check) or wait a day or two for mozilla to approve it on AMO.
Thanks.

**Comment by gkatsev** [comment]
Wow, that was quick. 3.11.3 has been approved. Please try it out and let me know how it works.

**Comment by crunchiebones** [comment]
yea it works again, ty
