### ISSUE TITLE
Hovering over URLs broken

### ISSUE THREAD

**Issue by axbender** [vimperator/vimperator-labs#404]
Since 44, when hovering over an URL, that URL is no longer shown above the status bar.

**Comment by gkatsev** [comment]
By default it should now be visible on the right side of the command line. You can set the
`showstatuslink` option to `3` to have it use the native firefox status bar.

Given that a lot of users are having this option, I'm going to consider changing the default to 3.

**Comment by nedbat** [comment]
I seem to be having this problem.  Setting showstatuslink to 3 fixes it, and things are fine for a while, and then it goes away again, and I have to explicitly set showstatuslink to 3 again.  Any clues why the setting is being reset?

**Comment by gkatsev** [comment]
@nedbat is the setting included in your `vimperatorrc` file?

**Comment by nedbat** [comment]
I have added it now, thanks.  I'm not sure what changed, this used to be on all the time.
