### ISSUE TITLE
Hint numbers don't show on a lot of sites

### ISSUE THREAD

**Issue by Neftas** [vimperator/vimperator-labs#405]
Look like the same problem as #255.

Steps to reproduce: go to `google.com`, type a search, see the results. Type `f` to get the hints to display. Notice that in the top bar the numbers are behind the header and thus not visible.

Expected to see: numbers over the highlighting in the header bar.

Extra details: I am using Firefox 44, and didn't notice this problem on 43. A number of prominent sites are affected, including Google, YouTube and Wikia.

**Comment by gkatsev** [comment]
Thanks. Looks like a duplicate of #388.

**Comment by Neftas** [comment]
You're right, should have looked at the other open issues first, sorry!

**Comment by gkatsev** [comment]
No worries
