### ISSUE TITLE
TypeError: tabGroup.tabView is null

### ISSUE THREAD

**Issue by jaapz** [vimperator/vimperator-labs#406]
Whenever I open a new tab using vimperator (:tabopen), after the page is opened, vimperator gives me the error in the title.

I run Firefox 45.0b1.

**Comment by gkatsev** [comment]
This is because tabgroups are being removed. See https://support.mozilla.org/en-US/kb/tab-groups-removal
We probably should prep for that. In the meantime, if you install @Quicksaver's [tabgroup](https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/) plugin, it'll keep it working and keep tab groups around as well!

**Comment by Quicksaver** [comment]
FWIW I was going through all instances of ```tabGroup.tabView``` thinking an easy fix would be to null-check them all. But quite a lot of other things depend on it, and I'm not familiar with a lot of them. I'm sorry I can't write a follow-up to my previous tabview patch, but I don't feel I'm the most adequate person for that. :(

**Comment by gkatsev** [comment]
@quicksaver you're probably just a bit less familiar with the codebase than I am and you're definitely more familiar with firefox plugin internals than I am so I don't think you're doing a bad job :P
Appreciate any help you can provide.

**Comment by Quicksaver** [comment]
> thinking an easy fix would be to null-check them all. But quite a lot of other things depend on it

Took another look, I definitely misinterpreted a lot of it the first time. Anyway, PR #414. :)

**Comment by jaapz** [comment]
Thanks, I installed that tabgroup plugin and at least now the annoying message is gone again :)

**Comment by gkatsev** [comment]
Should be fixed now as part of #414
