### ISSUE TITLE
3.11.3 won't install

### ISSUE THREAD

**Issue by bobf32** [vimperator/vimperator-labs#413]
Not sure if this is a problem with vimperator or firefox. I search for the addon, install, restart ff but no vimperator in sight. I had a similar issue before, and  deleting the firefox profile files extensions.* and compatibility.ini helped, but no such luck this time.

Oddly, only occurring on one pc, the other seems fine.

**Comment by bobf32** [comment]
Fixed by manually copying the xpi file to the firefox <profile>\extensions folder. No idea if this is remotely valid to do but seems to work.

**Comment by gkatsev** [comment]
That's super weird. Not sure there's anything we can do about it. You basically did manually what firefox did automatically. Anyway, glad you got it working.
