### ISSUE TITLE
New install only the "f" key works

### ISSUE THREAD

**Issue by ralvez** [vimperator/vimperator-labs#417]
I have firefox 44 and a new install of vimperator.
Nothing works. Only the "f" key works to show the hints. I have not command line, themes do not work.
Is this a problem with FF44 or are there some other known issues?
Ideas on troubleshooting the problem are most welcome.

Thanks!!

**Comment by gkatsev** [comment]
What version of vimperator? Make sure you have 3.11.3 installed, 3.10.1 or older won't work with firefox 44.

**Comment by ralvez** [comment]
@gkatserv,

I found the problem!!
There was another plugin that was messing things up. Removed it and we are back to normal.
Thanks for your reply.

R.
