### ISSUE TITLE
cannot map <M><M> and similar

### ISSUE THREAD

**Issue by ratijas** [vimperator/vimperator-labs#418]
i know it's not a part of vim, but vimperator surely could do this, i guess?  would be nice to map double-shift or something like that.

**Comment by gkatsev** [comment]
I'm not sure that we could actually do this. Javascript's event system generally only knows when a modifier key is pressed and not how many are pressed. Also, given the maintenance state of vimperator, and the (probably) low usage of this proposed feature, I'm going to close this. If enough people chime in, we'll consider whether we should investigate if this is even possible.
Thanks.
