### ISSUE TITLE
Line in localstore.rdf turns the status line blank and unreadable

### ISSUE THREAD

**Issue by rtega** [vimperator/vimperator-labs#42]
When the following line is added (probably by firefox itself) to localstore.rdf in the tag  \<RDF:Description RDF:about="chrome://browser/content/browser.xul">:
  \<NC:persist RDF:resource="chrome://browser/content/browser.xul#liberator-statusline"/>  
the status line of vimperator is entirely blank and shows nothing at all. I don't know whether this is an issue with vimperator or with firefox.

**Comment by limansky** [comment]
I've got a same issue, and removing this line fix status line for me. I have no idea when it was introduced. I updated FF from 31.6.0 to 31.7.0, but I'm not sure what it caused the issue, or it happened couple days after upgrade.

**Comment by maxauthority** [comment]
Have you tried newer Firefoxes? I haven't heard of this issue from anyone using a current Firefox.

**Comment by limansky** [comment]
@maxauthority, well I'm using FF 37 on my other PC, and not faced with the issue. However 31.x is ESR branch. I suppose it is used in many Linux distros. The second thing I'd like to admit is that, possible it's reproducibility is less than 100%.

**Comment by gkatsev** [comment]
I seem to remember that we dropped support for some older firefox, which maybe have included ff31 and that an older version of vimperator was required. However, I cannot back up my claim right now.

**Comment by gkatsev** [comment]
Latest ESR of firefox is 38, I believe. Closing.
