### ISSUE TITLE
Follow hint numbers get stuck behind certain elements

### ISSUE THREAD

**Issue by lilpea** [vimperator/vimperator-labs#421]
**Steps for reproduction**:

1. Go to a site that has links (or elements which contain links) with a z-index property (like reddit.com's header) and use the link following function.

1. Notice that the numbers are behind the element.

**Comment by gkatsev** [comment]
Thanks. This has already been fixed in master. See #409.
I'll be reviewing the currently available PRs this week and try to make a release with them next week.

**Comment by rr-** [comment]
TFW still no release

**Comment by timss** [comment]
@rr- Follow the master branch if you don't feel like waiting. Download and `make`, or link extension file to a clone of master. See https://github.com/vimperator/vimperator-labs/pull/409#issuecomment-179986165 and http://www.vimperator.org/developerinfo.

**Comment by rr-** [comment]
@timss I already built master on Linux 2-3 weeks ago, but building binaries for Windows ain't that pleasant (esp. that it requires to install extra software on my work computer.) The `git clone` approach was what I needed. Thanks :+1:

**Comment by timss** [comment]
@rr- Ah, haven't tried building it on Windows, but I don't doubt you're right at all. Glad you got it sorted :-)

**Comment by gkatsev** [comment]
Yeah, Makefile on windows a nightmare at best :)
