### ISSUE TITLE
Common Youtube video control shortcuts stop working

### ISSUE THREAD

**Issue by chasorleo** [vimperator/vimperator-labs#424]
Firefox Version: 44.0.1 
Vimperator Version: 3.11.3
The common Youtube video shortcuts like:
    space: STOP
    left arrow: Go back 5 Seconds
    right arrow: Go forward 5 Seconds
...
stop working.

**Comment by gkatsev** [comment]
I think this was changed as part of the `passthrough` option.

**Comment by chasorleo** [comment]
@gkatsev Cheers dude! 
problem solved by set passthrough = true
