### ISSUE TITLE
Keybinds

### ISSUE THREAD

**Issue by h8uthemost** [vimperator/vimperator-labs#425]
Can somebody please be kind enough to walk me through setting up new keybinds for Vimperator 3.8.21-signed.

I'm using Linux(Debian) and usually a .vimperatorrc would appear in my home folder. I set my keybinds up in it like this:
```
noremap <C-c> <C-v><C-c>
noremap <C-v> <C-v><C-v>
:map <Ins> f
:map <A-Ins> F
:map <C-left> gT
:map <C-right> gt
```

A .vimperatorrc didn't show up on this upgrade, so I tried using the one from a previous version and it doesn't seem to be reading it since my keybinds aren't working.

Any help on this would be great appreciated.

Thanks.

**Comment by gkatsev** [comment]
The rc file doesn't appear automatically. You can run `:mkv` (see `:h :mkv`) to save the file.
You can also just do it manually by editing `~/.vimperatorrc`.
Hope that helps.
