### ISSUE TITLE
Not working with FindBar Tweak's features again

### ISSUE THREAD

**Issue by Quicksaver** [vimperator/vimperator-labs#428]
Fun fact, searches through Vimperator's console are not highlighting all matches by default, showing them in the scrollbar, etc. I'm sure this is something that should be fixed on FBT's side of course. Just giving you the heads-up and I'll let you know when I fix it (hopefully will be something simple so later today).

**Comment by gkatsev** [comment]
Thanks. Is this with the latest code in master?

**Comment by Quicksaver** [comment]
Both with master and with the latest version on AMO, so I'm sure it's something I did to FBT in the latest update.

**Comment by Quicksaver** [comment]
Fixed by https://github.com/Quicksaver/FindBar-Tweak/commit/26b08bc4d6f1ab183b0f49fdc0cb60af193dec3c
