### ISSUE TITLE
Linux type paste has trailing garbage

### ISSUE THREAD

**Issue by yoshi314** [vimperator/vimperator-labs#43]
When pasting url's to open command with Shift+Ins on linux, the default 'amazon' is appended to the url.

It doesn't happen with ctrl+v style paste.

How to reproduce: 

- press o for open url menu
- default text is 'amazon' in my case.
- paste url with shift+ins
- "amazon" becomes appended do end of url

**Comment by gkatsev** [comment]
I believe we've fixed this issue by changing paste behavior for disallowing pasting from the primary register (or whatever the register that <s-Ins> gets it's data from).
