### ISSUE TITLE
Closing tabs with 'd' will close last tab remaining

### ISSUE THREAD

**Issue by Zekario** [vimperator/vimperator-labs#433]
I remember `d` not closing the final tab, but now pressing `d` on the final tab closes the window. Is this toggleable? I didn't see anything about it in the settings.

**Comment by DArtagan** [comment]
Looking at the [release notes](https://github.com/vimperator/vimperator-labs/releases/tag/vimperator-3.11): 

> Closing the last tab of a window now respects the Firefox setting: browser.tabs.closeWindowWithLastTab, which means those who are used to :tabclose never closing the window when closing the last tab, should set this option to false (either through about:config or with :set! browser.tabs.closeWindowWithLastTab=false)

**Comment by Zekario** [comment]
@DArtagan That fixed it, thanks!
