### ISSUE TITLE
Missing Hints 3.11.3 FF-44.0.2:  Win10 & linux-4.1.15

### ISSUE THREAD

**Issue by hzzm** [vimperator/vimperator-labs#436]
First i noticed how the Hints were missing on google.com for the main menu that appears, after you yield the search results. Likewise the textinput's Hint is missing at that point. It didn't take long before i found other sites' menus also missing hints, including an ordinary website i coded myself.
I found a similar issue here on github, that indictes google had placed items with z-index: 199999999; or something, so i assigned a higher z-index to my hints, that didn't help either. Obviously i don't have that high z-indexes on my own site, so that shouldn't even be the problem.

The Win10 installation with FF-44.0.2 and Vimperator 3.11.3 has a clean vimperator, no .vimperatorrc.
Adjustments to the linux version's hints were made in .vimperatorrc, regardless the problem persisted before and after.
I disabled all addons except vimperator, the problem still persists.
I created a new linux FF profile and only installed a fresh vimperator, problem persists.

**Comment by rr-** [comment]
Why is this closed?

**Comment by timss** [comment]
@rr- Because it's a duplicate of #415, and @hzzm made a comment https://github.com/vimperator/vimperator-labs/issues/415#issuecomment-187648160 in that thread instead.
