### ISSUE TITLE
search becomes case sensitive after a whitespace

### ISSUE THREAD

**Issue by randomizedthinking** [vimperator/vimperator-labs#437]
By default, the search in vimperator is case-insensitive, but if we search for a multiple-word phrase, the search pattern becomes case sensitive after the white space. For instance,

/Bank ==> match bank, Bank
/Bank of ==> match "bank of", "Bank of" but not "Bank Of"

My vimperator version is 3.11.3. Thanks!

**Comment by SammysHP** [comment]
`/Bank` matches only *Bank* but not *bank*. If the search term contains an upper-case letter the search will be case sensitive.

**Comment by timss** [comment]
@SammysHP is correct. 

The default Vimperator settings is `ignorecase`, but also `smartcase` which overrides the `ignorecase` option if the search pattern contains upper case characters.

If you want to always ignore case, be sure to use `set ignorecase` as well as `set nosmartcase` in your RC file.
