### ISSUE TITLE
please, explain me these lines

### ISSUE THREAD

**Issue by ratijas** [vimperator/vimperator-labs#439]
```
TARGETS = all help info xpi clean
$(TARGETS:%=\%.%):
	@echo MAKE $* $(@:$*.%=%)
	$(MAKE) -C $* $(@:$*.%=%)
```
i'm not _so_ much familiar with `Makefiles`.  when i see these lines i feel confused and don't even know how to google it.  any comments, please?

background: i'm doing now my little js project with three targets, and most logical way to build them is to use `cat` with various sources combinations; and all that supposed to be controlled by `Makefile`.

**Comment by timss** [comment]
Make syntax is ugly. Helping you to write your own is certainly outside the scope of Vimperator, but here's a short summary anyway. 

- The makefile defines a [set of targets](ttps://github.com/vimperator/vimperator-labs/blob/144894bd8cc79998c6c0e7a022374ef982e3d727/common/Makefile#L48). Target `xpi` is probably the most interesting.
- `@echo` is a supressed `echo`. The following command `MAKE ...` isn't executed. See the [5.2 Recipe Echoing](http://www.gnu.org/software/make/manual/make.html#Echoing).
- `$(MAKE)` is used for [overriding part of another makefile](http://www.gnu.org/software/make/manual/make.html#Overriding-Part-of-Another-Makefile).
- Lots of magic with pattern matching variables such as `$*`. See [10.5.4 How Patterns Match](http://www.gnu.org/software/make/manual/make.html#Pattern-Match).

You can and should probably make your Makefile much simpler than the one in Vimperator.

**Comment by ratijas** [comment]
thanks.  10.5.4 was exactly what i was wondering.

although, i've already came out with my own try: https://github.com/ratijas/colorize-pinyin.js/blob/master/Makefile.  no magic, not at all. :)

**Comment by timss** [comment]
Good stuff.

**Comment by gkatsev** [comment]
Also, I'm thinking of probably rewriting make in something else so that it works cross platform equally, though, that's lower priority than most other things that we have to do for vimperator.

**Comment by ratijas** [comment]
@gkatsev remember 👆 it works => don't touch. ;-)

**Comment by gkatsev** [comment]
@ratijas yes, that's why it's definitely not happening any time soon. I would just like it to be windows-compatible (or really, cross platform fully) and also more maintainable in general. But since it works, there's no hurry.
