### ISSUE TITLE
Lastpass shortcut doesn't work

### ISSUE THREAD

**Issue by miccrun** [vimperator/vimperator-labs#440]
I'm using Firefox 44, vimperator 3.12.0, and lastpass 4.1.2a. I set a shortcut control+shift+] to fill the next login, usually it should pop up the lastpass login form, and focus on the password field, but now it doesn't work on vimperator 3.11 and 3.12, the password field won't be focused, but when I disable vimperator, lastpass work just fine.

**Comment by timss** [comment]
Not quite sure how the login form is generated, but if it's ingested into the website it may have something to do with passthrough. Could you try to enable (`set passthrough`) or disable (`set nopassthrough`) it?

956c35d, fdd276b and 25ae33a.

**Comment by miccrun** [comment]
set passthrough=true works for me, thanks!

**Comment by timss** [comment]
Great!
