### ISSUE TITLE
[Req] Honor hlsearch on n/N

### ISSUE THREAD

**Issue by axbender** [vimperator/vimperator-labs#444]
Now, that the search works again across tabs (thanks for that!), I would like to propose the following change:
In another tab, when pressing n/N (i.e. search the next/previous match) do honor the hlsearch setting. Right now only the first match is highlighted, all the others are not.

**Comment by SammysHP** [comment]
Just wanted to create an issue for a similar problem that I noticed, then I saw this issue. The reason should be the same.

When you

- search for *foo* in tab A
- switch to tab B and search for *bar*
- then switch back to A and press <kbd>n</kbd>

the current match for *bar* will be highlighted, but all *foo* are highlighted via hlsearch.

**Comment by axbender** [comment]
Glad you're looking into that, thanks!

**Comment by SammysHP** [comment]
Feels like a deja-vu… *Just wanted to create an issue*… but then I found this one and – oh – I already commented on it.

First, I cannot reproduce the issue that I described. The highlighting is updated to whatever is searched with <kbd>n</kbd>.

But initially (this time) I wanted to report the issue that pressing <kbd>n</kbd> does not trigger `hlsearch`. So something similar to this is missing:

```
:noremap n :set hlsearch<cr>n
```

Which works, but flickers a little bit and might slow down <kbd>n</kbd>.
