### ISSUE TITLE
vimperator: smarter gi implementation

### ISSUE THREAD

**Issue by pale3** [vimperator/vimperator-labs#449]
When executing `gi` on let's say google, and textarea is alreay filled with some strings, gi needs to go in position of `string.length + 1` rather then on `0` position (beginning of string).

**Comment by timss** [comment]
Thanks for reporting, but this is a duplicate of #192 and #345. 

Please use `noremap gi gi<End>` if you want this behavior.

**Comment by pale3** [comment]
thx
