### ISSUE TITLE
Several errors when using 3.12.0 with Firefox 45

### ISSUE THREAD

**Issue by HalosGhost** [vimperator/vimperator-labs#455]
##### Issue type:

- Version compatibility

##### Version:

```
Vimperator:	3.12.0 (created: 2016/02/28 22:07:56)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
```

##### Description:

I wanted to open a new issue about this because the other compatibility issues do not seem to list these specific errors/issues (and so I do not know if they are related). If it turns out that this is just more information that should be added to the other compatibility issues (like #453), just let me know and I will happily move this information to that issue and close this one off.

* When typing in a text box, ``Insert`` mode is not entered and so hitting any key that is bound to an action will lead to a break from input and running that action (e.g., typing ``r`` reloads the page)
* All follow-links or similar keybinds fail (no action is taken, no links are highlighted with their numeric identifiers), though the status line changes the mode and allows you to type as if it functions correctly
* I cannot escape ``Ignore all keys`` mode after having the mode enabled while typing in a text box; ``S-Esc`` and ``Ins`` cause the mode specifier to flicker and then immediately return to the ``Ignore all keys`` line
* Various errors show along the liberator status bar when I do various things (including, but not limited to what is mentioned above):
   * ``TypeError: 'preventDefault' called on an object that does not implement interface Event.``
   * ``TypeError: 'stopPropagation' called on an object that does not implement interface Event.``
   * ``TypeError: Argument 1 of EventTarget.dispatchEvent does not implement interface Event.``
   * ``window.location.content is undefined``

##### Expected behavior:

Updating to firefox 45 would not cause any of the above errors to happen and functionality present and usable with firefox 44 would remain available and functional with firefox 45

**Comment by SammysHP** [comment]
```
Vimperator:	3.12.0 (created: 2016/03/02 13:30:53)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
```

Cannot reproduce any of these issues.

**Comment by HalosGhost** [comment]
@SammysHP, I am on Archlinux, and am using the official repository version of Firefox. I will post more detailed listings of my environment to either help clarify how to reproduce or perhaps to make clear that this may be an issue with my setup; but that will have to wait since Firefox becomes essentially unusable for me with the above issues.

**Comment by SammysHP** [comment]
@HalosGhost I use Arch Linux and Firefox from [extra] as well. ;)

**Comment by HalosGhost** [comment]
@SammysHP, haha, sure! But again, I probably will not be able to get to this until after work (or, at least, till I'm taking lunch).

**Comment by HalosGhost** [comment]
@SammysHP, good call! A fresh profile doesn't experience any of the errors or breakage.

I must say though, I would really like to avoid having to start a new profile. Is there any chance that this can be fixed?

**Comment by KaiSforza** [comment]
I just tried starting a new profile and am still getting the same errors reported in the first comment.

**Comment by artemisclyde** [comment]
The same issue occurs with my firefox under Archlinux.
Any news on getting rid of it without starting a new profile @HalosGhost ?

**Comment by HalosGhost** [comment]
@artemisclyde, No, and I am not sure what is causing the breakage specifically, so there is little more that I can do without guidance.

**Comment by HalosGhost** [comment]
I updated OP to follow the new issue template style (if only as a show of good faith that I'd like to make the issue as simple to fix as possible for the devs). Let me know if any more information is needed, or if there is anything else I can do to aid a fix being made.

**Comment by HalosGhost** [comment]
Bump (I know this is bad manners, sorry).

Just wondering if anyone has suggestions on what I could try to avoid needing a completely fresh profile. I've been holding firefox back from updating because I just cannot use browsers anymore without a vim-like interface. But, that is a security risk that I would rather squash.

**Comment by gkatsev** [comment]
I think that it requires some development work to fully fix, unfortunately :(

**Comment by HalosGhost** [comment]
@gkatsev, that's okay. Can you give me some indication of where to look in the code for what specifically is broken (are there logs from my system that I can look into which would aid such a diagnosis)? If so, I would be happy to at least look into trying to fix it.

**Comment by gkatsev** [comment]
@HalosGhost there isn't anything specific to look at. You'd want to put firefox into development mode and then run it from the terminal and also open up the Browser Toolbox. Then when you try out various functions, you should be seeing various errors in the terminal or in the browser toolbox. Those errors will then need to be addressed.
Also, the other issues under the `compatibility` flag might be a good place to start as some of them may already include a line number.

**Comment by memeplex** [comment]
I'm on archlinux too (and very up-to-date) and I'm experiencing this issue. Sadly, I was unable to fix it either by:
* Creating a new firefox profile.
* Creating a new system user, and so a 100% clean home directory,

**Comment by HalosGhost** [comment]
Okay, as of Firefox 47 and vimperator 3.14.0, all of these issues have disappeared for me!

Shall I go ahead and close?

**Comment by artemisclyde** [comment]
Give me 1-2 days to confirm, I'll give it one more try!

**Comment by HalosGhost** [comment]
@artemisclyde, can do! I'm struggling to contain my excitement (I've been living with a subpar alternative to vimperator essentially since I opened this issue, being able to return feels like an incredibly thoughtful gift)!

**Comment by artemisclyde** [comment]
I'm really excited to use it again, too! I can't find version 3.14 though, only 3.13.

**Comment by HalosGhost** [comment]
@artemisclyde: https://github.com/vimperator/vimperator-labs/releases

**Comment by artemisclyde** [comment]
Ah, had to change my firefox's value for 'xpinstall.signatures.required' to false, no testing begins with version 3.14. Thanks :)

**Comment by gkatsev** [comment]
It's being reviewed, hopefully will be out officially later today or tomorrow.

**Comment by artemisclyde** [comment]
Alright, I tested it for almost a week now and I can say - it got better!
From time to time I still have the issue that neither vimperator commands nor shortcuts will work, probably due to some problem with the focus in the current ffx session. But despite that, I reckon this as a major improvement :)

**Comment by AlexTalker** [comment]
Meet the same in 49(aurora) on 3.14.
I also think that meet the same for pentadactyl.
Could try to fix if somebody helps me understand how.

**Comment by psamim** [comment]
I get the following error in Firefox 48, ArchLinux, Vimperator 3.14 and e10s enabled:
```
TypeError: Argument 1 of EventTarget.dispatchEvent does not implement interface Event.
```

**Comment by timss** [comment]
@psamim e10s/electrolysis conflicts with Vimperator (and other advanced addons), for now you'll unfortunately have to disable it. Please se #211 and [others](https://github.com/vimperator/vimperator-labs/issues?utf8=✓&q=is:issue%20e10s).

**Comment by kvelicka** [comment]
@timss is there any progress being made toward e10s compatibility? With Firefox being fairly slow these days, I'm having to make the excruciatingly painful decision of e10s vs Vimperator and I wish I didn't have to. 

In addition, if there's work that could be chunked out for the community, I would seriously consider contributing some of my time to bring Vimperator and e10s closer together. Please let me know if I could help.

**Comment by timss** [comment]
@kvelicka Sorry about the late reply, but just thought I'd pitch in to say that most discussions have been in #211, and the status of e10s is kind of in a limbo because of future deprecation of XUL and introduction of new addon API probably forcing a rewrite of vimperator. Not enough dedicated contributors/maintainers to show much progress at this point, unfortunately.

**Comment by HalosGhost** [comment]
This issue has been solved as far as I am concerned. Further compatibility issues seem to be dealing with e10s / deprecation of XUL and should go to those relevant issues. Thanks to all the Vimperator contributors/maintainers for their continued awesome.
