### ISSUE TITLE
"TypeError: context is undefined" - qmarks, bmarks, tabgroups, history, buffers etc

### ISSUE THREAD

**Issue by e1r0h1r** [vimperator/vimperator-labs#456]
Windows 10
Firefox 45.0
Vimperator 3.12.0

:qmarks
![qmarks error](https://cloud.githubusercontent.com/assets/4415725/13659887/b6e32338-e6c8-11e5-99ef-3c2b8d3db0ec.png)

TypeError: context is undefined
![typeerror](https://cloud.githubusercontent.com/assets/4415725/13659888/b97a2a4c-e6c8-11e5-94dc-e0fbd8e11520.png)

**Comment by stooj** [comment]
The `:ls` command also seems to suffer from this problem.

**Comment by alesandar** [comment]
Let's add `:tabgroups` to the list.

Arch Linux 4.4.5-1
Firefox 45.0
Vimperator 3.12.0

**Comment by timss** [comment]
Getting quite a lot of reports on this issue. This seems to be the first issue that reported this error, so I'm going to make this the "main" issue. 

Others: #457, #467, #468

**Comment by Vee-Kicks** [comment]
Arch Linux 4.4.6
Firefox 45.0.1
Vimperator 3.12.0
Same as above, bmarks and history are returning `TypeError: context is undefined`.

**Comment by clancyian** [comment]
Same issue on:
Windows 7
Firefox 45.0.1
Vimperator 3.12.0

**Comment by pippocode** [comment]
Same issue (begin some weeks ago):

Vimperator:	3.12.0 (created: 2016/02/28 22:07:56)
Firefox:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by memeplex** [comment]
I'm on a very up-to-date archlinux and I'm experiencing this issue. Sadly, I was unable to fix it either by:

* Creating a new firefox profile.
* Moving to a new .mozilla directory.
* Creating a new system user, and so a 100% clean home directory,

**Comment by Alaanor** [comment]
Same here:
Arch Linux 4.5.0
Firefox 45.0.2
Vimperator 3.12.0

**Comment by 4e554c4c** [comment]
Well since everyone else is here, I'll confirm.
Arch linux 4.5.0 & Arch Linux 4.4.5
Firefox 45.0.2
Vimperator: 3.12.0

**Comment by timss** [comment]
Thanks for reports and interest, but please use the reaction system instead of posting very similar setups. OS doesn't matter in this case, and certainly not which "version" of Arch.

**Comment by patsimm** [comment]
I'm experiencing quite the same problem.

**Comment by protrolium** [comment]
I am also getting these errors:
OS X 10.10.5
Vimperator: 3.12.0 
Firefox: 45.0.1

**Comment by timss** [comment]
Come on, we already have enough confirmations on this. Read my [comment](https://github.com/vimperator/vimperator-labs/issues/456#issuecomment-211486675) and stop spamming participants with notifications.

**Comment by Vtec234** [comment]
I also get this error on `:tabs`.
Firefox 45.0.2
Vimperator 3.12.0

**Comment by liamdawson** [comment]
@timss - would you consider locking replies to this issue?

**Comment by phantom-voltage** [comment]
So I did some searching in the developer section of Firefox versions and found this.

> 
 WebIDL constructors could be called without the new operator in chrome context.  Now such code will raise a TypeError as in Web content since Firefox 30. For example, var req = XMLHttpRequest(); needs to be var req = new XMLHttpRequest();.


Located here: https://developer.mozilla.org/en-US/Firefox/Releases/45

I'm not familiar with JS nor plugin development, but I think this is worth investigating. It appears to be a simple fix, at least in the given example, and the error matches the one that is thrown in vimperator.

**Comment by timss** [comment]
@liamdawson I don't think that's a good idea, because it'll also stop comments such as the one by @phantom-voltage. Maybe if it was a filter/allow-only option.

Next "+1" or similar comment will probably be deleted, though.

**Comment by oracleyue** [comment]
Arch Linux 4.4.5-1
Firefox 45.0.1
Vimperator 3.12.0

I didn't get error messages in the mini-buffer (where typing in the commands). However, none of the above commands work anymore, while no errors or other messages appeared.

**Comment by pippocode** [comment]
The 3.13.0 version resolve the issue ONLY if builded from the source (unsigned extension). The official release (signed extension) doesn't work.

**Comment by timss** [comment]
That sounds odd.                                                                                                                             

    # built from 3.13.0 git tag
    $ zipcmp vimperator-3.13.0.xpi amo/vimperator-3.13.0-fx.xpi 
    --- vimperator-3.13.0.xpi
    +++ amo/vimperator-3.13.0-fx.xpi
    +      18228 6c8f45d4 META-INF/manifest.mf
    +       4178 57b78c3e META-INF/mozilla.rsa
    +        121 4384b4e7 META-INF/mozilla.sf
    +      77061 aa21ecb2 common/content/liberator.js
    -      77061 b1bdfee6 common/content/liberator.js

    $ diff <(unzip -p vimperator-3.13.0.xpi common/content/liberator.js) <(unzip -p amo/vimperator-3.13.0-fx.xpi common/content/liberator.js)
    140c140
    <     version: "3.13.0 (created: 2016/05/03 16:05:31)", // these VERSION and DATE tokens are replaced by the Makefile
    ---
    >     version: "3.13.0 (created: 2016/04/28 00:20:02)", // these VERSION and DATE tokens are replaced by the Makefile

The rest of the files just contain signatures and hash sums.

I can test later, but are you sure it's not something on your part?

**Comment by pippocode** [comment]
Really odd. I don't know why but the behaviour is the same. I install official plugin (from https://addons.mozilla.org/en-US/firefox/addon/vimperator/) OVERWRITING the builded, and it doesn't work anymore (in inverse direction it works) O_o
Without any other extension too.
It is not a big problem but I must disable   xpinstall.signatures.required

I tested only the   :bmarks -T xxxx

**Comment by gkatsev** [comment]
This is fixed by #497 which has been merged into master, unfortunately, I didn't get around to making a release last night. If you can try out the master branch and let us know how it works would be great.

**Comment by timss** [comment]
Oh right sorry, I forgot that this was the PR that came right after the 3.13.0 release.

**Comment by eunikolsky** [comment]
@gkatsev, i installed the latest `master` version in Firefox 46.0 (OSX 10.10.5) and this is fixed! `:history`, `:bmarks`, `:tabgroups` work fine. thanks! waiting for the official release.
