### ISSUE TITLE
:bmarks command  doesn't work

### ISSUE THREAD

**Issue by mitsugu** [vimperator/vimperator-labs#457]
OS : Ubuntu MATE 15.10
Firefox : Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Vimperator : 3.12.0

![screenshot](https://cloud.githubusercontent.com/assets/55200/13690163/7c6ed374-e771-11e5-90d3-1885b88e353f.png)

![screenshot-1](https://cloud.githubusercontent.com/assets/55200/13690164/7c745c04-e771-11e5-9ad6-73528305fd5d.png)

**Comment by timss** [comment]
Thanks for reporting this issue. This does however look very similar to #456. Might be the same cause, although the bug might be present in different functions (needs to be looked into).

**Comment by nabulator** [comment]
experiencing same error here. 
os also ubuntu 15.10
Firefox 45.0

probably a firefox thing since it was working before I updated firefox.

**Comment by aless** [comment]
Same here with Firefox 45.0
Tried Vimperator 3.12.0 and the repository head (24008a4)

**Comment by a13ph** [comment]
Same on Firefox 45.0, Ubuntu 15.10, AMO(stable) Vimperator - as well (if reporting similar environment helps at all)

**Comment by timss** [comment]
Getting quite a lot of reports on this issue. Doing a little house cleaning so I'm going to mark this as a duplicate and use #456 as the main issue. Thanks.
