### ISSUE TITLE
:buffers -> TypeError

### ISSUE THREAD

**Issue by holomorph** [vimperator/vimperator-labs#467]
Bug report
Vimperator:	3.12.0 (created: 2016/02/28 22:07:56)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0

Doing `:buffers` results in the error message `TypeError: context is undefined` instead of showing the list of buffers.

**Comment by timss** [comment]
Please use the issue template.

This is probably yet another Firefox 45 issue, others being labeled with [compatibility](https://github.com/vimperator/vimperator-labs/issues?q=is:issue+is:open+label:compatibility). For example #456 and #457 is probably the same bug. Thanks for reporting, but I'm closing as duplicate.
