### ISSUE TITLE
HISTORY command is broken in 3.12.0 and Firefox 45

### ISSUE THREAD

**Issue by yurist** [vimperator/vimperator-labs#468]
##### Issue type:

- Version compatibility

##### Version:
Vimperator:	3.12.0 (created: 2016/02/28 22:07:56)
Firefox:	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0

##### Description:

:history with no parameters fails with TypeError: context is undefined
:history with a search parameter shows a list of history items, but trying to open any of them fails with the same error.

Restarting after totally removing Mozilla folder and vimperatorrc didn't help.

The problem appeared after a recent upgrade cycle. No problem with 3.12.0 and Firefox 41 (on Ubuntu) that's why I believe it's a compatibility issue.

##### Steps to reproduce:

See description above,

**Comment by timss** [comment]
Thanks for reporting, although this seems to be the same error in #456 among others. Closing as duplicate.
