### ISSUE TITLE
Vimperator does not respond in FF 46.0b2

### ISSUE THREAD

**Issue by RomanHargrave** [vimperator/vimperator-labs#470]
##### Issue type:

- Version compatibility

##### Version:

Affected:

```
GIT: g80ab95a
Plugin reports version 3.12.0
```

##### Description:

Vimperator does not respond to keyboard input, all keyboard input is instead forwarded to the browser. e.g., depressing `/` will show the regular firefox 'Find in Page' tool rather than vimperator.

Plugin buttons/icons/etc placed in the vimperator status bar do not respond to mouse hover/click

**Comment by reepush** [comment]
It's related to #398 issue. In short try to checkout [this](https://github.com/reepush/vimperator-labs/tree/comprehensions) branch and write about any issues you will have.

**Comment by timss** [comment]
Thanks @reepush !

Closing this as a duplicate so we can keep it all in the same issue, but thanks for reporting @RomanHargrave
