### ISSUE TITLE
Gmail selection menu cannot be navigated with vimperator

### ISSUE THREAD

**Issue by alexmsmartins** [vimperator/vimperator-labs#472]
##### Issue type:
- Bug report
##### Version:

Vimperator: 3.12.0 (created: 2016/02/28 22:07:56)
Firefox:    Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
##### Description:

When I  press 'f' and select  the selection menu on the top left corner just  below the search box, if I then press 'f' again, I get no hints for the options in the menu itself and the menu collapses.
##### Expected behaviour:

I expected to be able to select options in the gmail selection menu.

This behaviour works well with VimFx.

**Comment by dhottinger** [comment]
Try:
:set hinttags+=" | //xhtml:div[@role='button']"

**Comment by alexmsmartins** [comment]
Hi @dhottinger 

Did that work for you?

I added 

        set hinttags+=" | //xhtml:div[@role='button']"

to the end of my `~/.vimperatorrc`file.

I also added the same command through *vi last line mode* just in case

        :set hinttags+=" | //xhtml:div[@role='button']"

In both cases, after I press `f` and manage to enter the menu as show in the following screenshot. And in both cases, when I press `f` again, the menu disappears instead of showing *hints* for the various options

![screenshot from 2016-03-29 23 34 17](https://cloud.githubusercontent.com/assets/147842/14126241/742243d2-f607-11e5-9c2c-0ac4765cddb6.png)

**Comment by dhottinger** [comment]
Ah yes, I misread your first post.

Not sure what to do about it as the menu disappears before I can select it in firebug.

I'd just install the feedSomeKeys_3.js vimperator plugin from https://github.com/vimpr/vimperator-plugins and map the shortcuts that Gmail has:

fmaps -u=//mail\.google\.com/mail/ *a *n *r *u *s *t

Then to e.g. select all you'd press *a

**Comment by Rodartist** [comment]
You can just use the arrow keys to navigate down and select.
