### ISSUE TITLE
Add w3m "s" jumping

### ISSUE THREAD

**Issue by McSinyx** [vimperator/vimperator-labs#476]
##### Issue type:
- Feature request
##### Version:

```
Vimperator: 3.12.0 (created: 2016/02/28 22:07:56)
Firefox:    Mozilla/5.0 (X11; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0
```
##### Expected behavior:

Hi, I'm using Vimperator and I enjoy it a lot. Want feature I'd love to see is the w3m-like jumping, which is toggled by `s`:

![2016-04-03-214656_620x368_scrot](https://cloud.githubusercontent.com/assets/13689192/14233000/2ea7664c-f9e6-11e5-87f6-f920671c862a.png)

I knew there is `:jumps`, but it is less convenient to use (how should I use it, actually - I'm using `:jumps<CR>;o`).

Thanks.

Edit: what I really want is to be able to navigate in a jump list like in Normal mode (i.e. using the `hjkl` and `<C-f><C-b><C-d><C-u>` things) and select using Enter.

Edit 2016-06-06: Jump list stopped working. `:ju` show this error:

```
TypeError:    is not iterable
```

I'm on firefox-esr on Debian testing:

```
Vimperator: 3.13.1 (created: 2016/05/04 01:34:00)
Firefox:    Mozilla/5.0 (X11; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0
```

**Comment by gkatsev** [comment]
Does `<c-i>` and `<c-o>` not do what you want? They go forward and back through the jump list.

**Comment by McSinyx** [comment]
So you suggest me to open the jump list, remember the jump level then use `<C-o>` or `<C-i>`? I don't think that is anywhere close to convenience.

BTW jump list stopped working for me.

**Comment by gkatsev** [comment]
Can you describe what `s` does on w3m? I was just suggesting something that could possibly work as a substitute.
With `c-o` and `c-i` you don't necessarily need to remember, you can just hit `<c-o>` until you get to where you want or if you overshoot, you can correct by hitting `<c-i>`.

**Comment by McSinyx** [comment]
> Can you describe what s does on w3m?

Well in w3m, `s` pops up buffer selection menu of the previous/next web pages in the history, but w3m call them buffers, where you can use `j` and `k` to navigate up/down, `<Space>` or `<CR>` to go to that buffer. It's very convenient because you can visually see all the pages.

What I suggest is to have sth that can be navigate using `jk` or `<C-f><C-b><C-u><C-d>` things (w3m doesn't support the `<C-*` things which makes it to be quite inconvenient sometimes when the list is long. Also do you know why is jump list broken?

> With c-o and c-i you don't necessarily need to remember, you can just hit <c-o> until you get to where you want or if you overshoot, you can correct by hitting <c-i>.

Thanks, I already know that. But I have bad connection and slow machine, so that's not a very good idea.

**Comment by tiborsimko** [comment]
It's kind of like calling `:history` in Vimperator and being able to navigate in that history buffer quickly up and down using `j` and `k` to rapidly open some previously visited site.  BTW I confirm that `:jumps` doesn't work for me either, leading to `TypeError` with Vimperator/3.13.1 Firefox/46.0.1.

FWIW I use `C-o` and `C-i` all the time, but only for jumping around in "immediate history".  For going further backwards in time, it would be really nice to have working `:history` or `:jumps` buffer behaving like in w3m.
