### ISSUE TITLE
Tabnumbers with more than 5 tabs disable hints

### ISSUE THREAD

**Issue by liloman** [vimperator/vimperator-labs#484]
Hi,

##### Issue type:
- Bug report

##### Version:
```
Vimperator:	3.12.0 (created: 2016/02/28 22:07:56)
Firefox:	Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
```

##### Description:

When I set tabnumber on and I have more than 4 tabs then hints are disabled and not showing anymore.

##### Expected behavior:

Show hints as usual.

##### Steps to reproduce:

1. set tabnumbers=true
2. Create 5 tabs
3. You can see the last tabnumber is blinking
4. Hints don't work anymore in any tab

BTW awesome software I've been using it for more than 8 years if someone is interested here is [my vimperatorrc] (https://github.com/liloman/dotfiles/blob/master/vimperator/.vimperatorrc). ;)

**Comment by timss** [comment]
I tried this on FF 45 with latest commit (e8eade2), but I'm not able to reproduce fully. 

Hints are working correctly (`f`), although the last tab number seems to be missing even with < 5 tabs, but is visible when hovering over the tab. It's also acting up with Tree Style Tab, but that could be my style or CSS.

Which hint mode were you using?

**Comment by timss** [comment]
Tab number missing from last tab is in a seperate issue, #116

**Comment by liloman** [comment]
You're right I disabled my vimperatorrc and it worked. 

I debugged the root to this custom style line:
```
-moz-border-radius: 0px !important!
```

I tried several moz-border without luck.

So the issue should be:
Tabnumbers on with more than 5 tabs and -moz-border-radius used disable hints on other tabs. :D

**Comment by timss** [comment]
I'm not familiar with the CSS details, but Vimperator can't keep track of custom CSS changes that might interfere with Vimperator changes. 

You probably have to find a way around it, or see if you're able to make some possible changes in Vimperator's code that would allow your custom CSS to work as intended. In that case, maybe it should be included using a pull request. 

How does that sound?

**Comment by liloman** [comment]
Sound that I already did my workaround commenting it out. ;) 

I don't have that spare time right now. :)

Cheers and thanks. :)

**Comment by timss** [comment]
Great, thanks for reporting, even if it was nothing!

**Comment by liloman** [comment]
Thanks to you all for you work.

Great piece of software indeed.
