### ISSUE TITLE
Integrating Vimperator and Evernote Web Clipper

### ISSUE THREAD

**Issue by Andre0991** [vimperator/vimperator-labs#487]
##### Issue type:

- Bug report

##### Version:

![screenshot 2016-04-24 21 38 29](https://cloud.githubusercontent.com/assets/7083061/14771541/07c2bccc-0a65-11e6-93e2-8dbb32f51f54.png)

##### Description:

Vimperator shadows [Evernote Web Clipper](https://addons.mozilla.org/en-US/firefox/addon/evernote-web-clipper/)'s shortcut `CTRL-``

If I disable Vimperator, it works fine.

Actually, I wouldn't mind not using this shortcut if I were able to open the web clipper by running some js snippet or somethingl like that.

Googling for `vimperator evernote web clipper` results in a bunch of Japanese sites with suggestions like
`js __readable_by_evernote.__readable_by_evernote__launch(true)`
and
`command clip javascript evernote_doAction()`
but none of them worked here.

##### Expected behavior:

 `CTRL-`` should open the web clipper.

##### Steps to reproduce:

Install both plugins. Click on the web clipper icon and open the options panel. Enable the keyboard shortcuts and restart Firefox.

**Comment by malockin** [comment]
If you have the Evernote Clipper installed, you can create a command to activate the clipper:

`command! note emenu Tools.WebClipper`

**Comment by Andre0991** [comment]
@malockin Thanks!
