### ISSUE TITLE
Firefox 46 on Win7 breaks Vimperator 3.12.0

### ISSUE THREAD

**Issue by netserf** [vimperator/vimperator-labs#490]
##### Issue type:
- Bug report

##### Version:
- Firefox 46.0
- Windows 7 enterprise edition
- Vimperator 3.12.0

##### Description:
After upgrading to Firefox 46.0 the vimperator commands stop working. I do have a command line at the bottom of my screen and some commands appears, but they do not execute when I hit enter. I tried uninstalling and reinstalling vimperator, but no luck.

I'm back to using my mouse. Its a sad day.  :-(

##### Expected behavior:
All commands and functionality are currently broken in my instance of Firefox 46.0. 
- Hint mode - Does not work. Should bring up numbers corresponding to links.
- Command line - ":" does not focus on the command line. I have to manually click on the command line to get focus. I can type in the command line, but the commands do not execute when I hit enter.
- Completion - Auto-completion does not work. Should provide hints on available commands/searches.

##### Steps to reproduce:
On Windows 7 enterprise, install Firefox 45.0. Install vimperator (v.3.12.0). Upgrade to Firefox 46.0.

Thank you for all your hard work with Vimperator.

**Comment by gkatsev** [comment]
It's a known issue that we'll hopefully be able to address this week. Please follow #398 for updates.

**Comment by netserf** [comment]
Okay, thank you very much Gary!
