### ISSUE TITLE
Vimperator does not work with Firefox 46 at all

### ISSUE THREAD

**Issue by MPW1412** [vimperator/vimperator-labs#492]
##### Issue type:

- Bug report
##### Version:

```
Vimperator: 3.12.0
Firefox 46 on Ubuntu 14.04
```

##### Description:

Vimperator does not work at all. No keystrokes which are supposed to address vimperator work. Deactivating and reactivating the addon doesn't change this and the option are unopenable, the link liberator://help/options leads to file not found.

Thanks for reading.

Regards,
Matthias

**Comment by 7gitLak** [comment]
Same problem on Windows 7 (Vimperator: 3.12.0, Firefox 46)
Regards, Dirk Michael

**Comment by long-long-float** [comment]
The same problem on Ubuntu 16.04 (Firefox 46.0, Vimperator 3.12.0)

**Comment by msimonsson** [comment]
An update has been uploaded to Mozilla for review, see #398 for more information.

**Comment by 7gitLak** [comment]
Thanks a lot, installing the new xpi from github solved the problem.

**Comment by MPW1412** [comment]
Works like a charm again, thank you for your great effort!
