### ISSUE TITLE
Vimperator doesn't work with Firefox 46

### ISSUE THREAD

**Issue by j127** [vimperator/vimperator-labs#495]
##### Issue type:

- Version compatibility

##### Version:

Vimperator 3.12.0. Ubuntu 14.04. Firefox 46.

##### Description:

No Vimperator functionality appears to be working. Examples: `y`, `t`, `o`, `d` do nothing.

I tried creating a new Firefox profile and installing a clean copy, but that doesn't work either.

**Comment by gkatsev** [comment]
It's a known issue, see #398, it's already fixed in master, just waiting for it to get reviewed on AMO.
