### ISSUE TITLE
Restart can't work

### ISSUE THREAD

**Issue by kesdoputr** [vimperator/vimperator-labs#496]
I'm use the lastest 3.13.0 with firefox 46.0
As i mentioned before
https://github.com/vimperator/vimperator-labs/issues/453
Now the restart command still can't work,when i type :res and press enter
firefox just close but not restart~~i wait for about 5 mins.

**Comment by timss** [comment]
I didn't see your first point in #453 about restarting issues.

Let's use #460, although it was after your first issue it's older than this one. Thanks, and sorry about the mess.
