### ISSUE TITLE
Jumps doesn't work

### ISSUE THREAD

**Issue by kesdoputr** [vimperator/vimperator-labs#508]
Hello I'm using vimperator 3.13.1 with Firefox 46.0.1,and i find the jumps can't work.When i type
:ju and press enter i get the error message below:
https://i.imgur.com/YVC5nze.jpg

I try to use old version,when i back to 3.12.0 and Firefox 44.0.2 jumps works fine.
And i upgrade to vimperator 3.13.1 with firefox 44.02,i get the different error message below:
https://i.imgur.com/BJLrEZr.jpg

**Comment by McSinyx** [comment]
Can confirm this too. I'm on Firefox 45.0 on Debian GNU/Linux with Vimperator 3.13.1.

**Comment by tiborsimko** [comment]
See #476 where this is also discussed.

**Comment by ariponce** [comment]
I'm having the same issue with Firefox 47.0, Vimperator version 3.14.0 on Arch linux

**Comment by cdown** [comment]
TypeError seems to only happen if the current tab has no history.

But yes, on Firefox 47.0, Vimperator 3.14.0 on Arch Linux, `:jumps` seems to do nothing at all.

**Comment by cdown** [comment]
I suspect this might bisect to 0399b59e858986, but I need to investigate more.

**Comment by voidzero** [comment]
I really miss being able to use this function.
