### ISSUE TITLE
Key mappings on Github website corrupt.

### ISSUE THREAD

**Issue by amosbird** [vimperator/vimperator-labs#511]
##### Issue type:

- Bug report
##### Version:

```
Vimperator: 3.13.1 (created: 2016/05/04 01:34:00)
Firefox:    Mozilla/5.0 (X11; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0
```
##### Description:

When in `Insert` mode on Github site, key mappings like `Ctrl-h`, `Ctrl-m` are passed directly to firefox. (`Ctrl-h` needs to be typed serveral times to reproduce)
##### Expected behavior:

Key mappings work consistently.
##### Steps to reproduce:
1. Set up key mappings.
   
   ```
   inoremap <C-m> <Enter>
   inoremap <C-j> <Down>
   inoremap <C-k> <Up>
   ```
2. Active this input box  ![](https://ptpb.pw/k2FO.jpg).
3. Type those key bindings.

**Comment by javiertury** [comment]
On insert mode is `<C-i>` doesn't launch gvim but instead is used by github to open _italics_ with underscores.
