### ISSUE TITLE
Removing of privateBrowsing observer and 'PrivateMode' autocommand.

### ISSUE THREAD

**Issue by gineadai** [vimperator/vimperator-labs#513]
https://github.com/vimperator/vimperator-labs/commit/b04503baa90468e4c9a249a6fecc95ce07c0fb56
There is saying it needed to be deleted after Firefox 20 release. I assume it is relevant now, if comment still here. Or not?

**Comment by gkatsev** [comment]
Can be removed.

**Comment by gkatsev** [comment]
Also, thanks for going through and looking at what needs to be removed.

**Comment by gineadai** [comment]
https://github.com/vimperator/vimperator-labs/pull/514 Mayby it is. What is privateBrowsing observer i don't know and it seems to be gone already. There is code with 'PrivateBrowing' in content/commandline.js on line 1063 and 1066, but it's code two years later this commit, so i think it up-to-date

**Comment by gineadai** [comment]
https://github.com/vimperator/vimperator-labs/pull/514
