### ISSUE TITLE
Cannot source symbolic links as plugins

### ISSUE THREAD

**Issue by ktns** [vimperator/vimperator-labs#521]
##### Issue type:
- Bug report

##### Version:

```
Vimperator:	3.13.1 (created: 2016/05/26 20:22:45)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
```

##### Description:
After upgrading firefox to 45.0, symbolic links in ```$HOME/.vimperator/plugins``` cannot be sourced. Regular files are properly sourced.

**Comment by Futurile** [comment]
@ktns I'm not getting the same result - I think we have similar set-ups. 

```
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
```

My .vimperator directory is set-up as follows:

```
colors -> /home/steve/.dotfiles/vimperator/colors/
plugin -> /home/steve/.dotfiles/vimperator/plugin/
```

Vimperatorrc is:

```
.vimperatorrc -> /home/steve/.dotfiles/vimperator/vimperatorrc 
```
I'm sourcing in .vimperatorrc, the color themes and the plugins fine. Maybe trying the latest version of Vimperator?

**Comment by ktns** [comment]
Actually, I have a little bit different set-up.
I have vimperatorrc symlinked as you have, but I have each files under ```$HOME/.vimperator/plugins``` instead of the directory itself symlinked.

I've tried the latest vimperator from github (6e6bf77b63e3e5d4c1674c2cb5a8dc33d3082f4f), and the situation haven't  changed.

If there is something to be tried, please let me know.
Thanks!

**Comment by ktns** [comment]
I think now I understand why it's failing.
I have a set-up with symlinks to relative path:
```
$HOME/.vimperator -> .dotfiles/.vimperator/
$HOME/.dotfiles/.vimperator/plugins/foobar.js -> ../../vimperator-plugins/foobar.js
```
Probably the problem is relative symlinks in a symlink directory.
Linux resolves the symlinks properly, but this set-up is indeed messy.
After get them absolutely symlinked, they are sourced properly.

I don't know whether this issue should be closed or not, but feel free to close it.

**Comment by gkatsev** [comment]
I think absolute symlinks are always best to minimize any issues. Closing for now, we can re-open if there happen to be more symlink issues.
