### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by Pebebtol** [vimperator/vimperator-labs#534]
##### Issue type:

- Bug report or
- Version compatibility

##### Version:

```
Vimperator:	3.13.1 (created: 2016/05/04 01:34:00)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
<!-- (Paste the output of `:version` here) -->
```

##### Description:

I dont know, whether this is the right platform for this kind of issue, but since yesterday evening, i get the error ReferenceError: Application is not defined. 
The issue came up after rebooting my system, worked perfectly beforehand.
BTW, I'm using arch, tried reinstalling, vimperator and firefox. I also reinstalled with dependancies and  deleted the files in /home
##### Expected behavior:

Well, no ReferenceError (which occurs with every command (like t, :, f...) but not with j,k,h,l...)

**Comment by MarkusAmshove** [comment]
The same happened to me after upgrading to Firefox 47.0, I guess that's your problem too (maybe a silent update)

**Comment by frenchbeard** [comment]
There should be an upgrade available now (got the same problem, and am also on Arch running Firefox 47).

**Comment by Pebebtol** [comment]
Update fixed it for me. Thank you.

**Comment by erikw** [comment]
I still have this issue


> Vimperator:	3.16.0 (created: 2017/02/01 00:55:15)
> Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
