### ISSUE TITLE
an option to toggle visibility of status bar when fullsreen

### ISSUE THREAD

**Issue by qeatzy** [vimperator/vimperator-labs#536]
##### Issue type:

- Feature request

##### Version:
```
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
```

##### Description:
1. when fullscreen,  in some cases status bar should be hidden, e.g., watching video; in other cases, it should be visible.
2. when fullscreen, why prefer status bar being visible in some cases? 
    - It will be faster to 
        * type command, 
        * do searching, 
        * follow hint,

      there are some delay due to loading of the status bar.
     (the delay has been improved a lot in 3.14.0, compare to 3.13.1, but small difference do exist)

    - Currently some functionality doesn't work well when fullscreen, e.g., 
        * follow hint not work in some site, (e.g., google search page, whereas extended hint mode works fine),  
        * \<C-g\> not work either (like in less, I wanna show info of interest via type \<C-g\> )

    - Status bar provides valuable infomation (e.g, when toggle Insert/TextArea/Visual mode). 
      I hope I could toggle fullscreen to gain maximal view area, while pertaining the valuable infomation of status bar. 
      (note that status bar incurs no spatial inconvenience when do most part of browsing)

Thx, vimperator is great, and I'd like to see it being better.

**Comment by gkatsev** [comment]
I believe this has already been fulfilled under the `statuslinevisibility` option. It can be set to `auto`, `hidden`, or `visible`. `hidden` will always hide the bar unless it is being used; `visible` will always show the bar; and `auto` will hide it in fullscreen unless it is being used and will show it when not in fullscreen.

**Comment by jstetten** [comment]
Wonderful feature. The big problem is that setting `set statuslinevisibility=hidden` incurs a very significant amount of time to bring up the statusline automatically thereafter for me. Many seconds (or even minutes under certain circumstances) on my computer, which makes this feature unusable in real life, unfortunately.
