### ISSUE TITLE
3.14 breaks history

### ISSUE THREAD

**Issue by Minoru** [vimperator/vimperator-labs#538]
##### Issue type:

- Version compatibility
##### Version:

```
Vimperator: 3.13.1 (created: 2016/06/15 23:52:19)
Firefox:    Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0
```

This is an XPI I built myself from commit afe333b5615a5b42de209caec90ee8e5cf5cc80c. 3.14 installed from addons.mozilla.org behaves the same.
##### Description:

Whenever I initiate a history search, Vimperator only displays some subset of results. It seems like it's "forgetting" a lot of entries. There's no law I can see that governs which entries are "forgotten"—some of them are old, some of them are new. But there must be some underlying law as the set of "forgotten" URLs is the same after a restart. All of the entries are present in Firefox's native History dialog. They're also displayed if I roll back to previous commit.

afe333b5615a5b42de209caec90ee8e5cf5cc80c is to blame as its parent, e65a5662a4c992ccfce7a9dfbb778a11f81c6ea5, works just fine.

This can't be reproduced with a fresh profile (with and without my config), and even with mine if I use default configuration. The option that triggers the issue is `complete`—if it includes `h`, the issue is triggered (default includes `l` which is another way to pull entries from the history, and that search works just fine—but it behaves slightly differently from `h` and I don't like it as much.)
##### Expected behavior:

I expect new version to work just like the old one, i.e. it shouldn't pretend that some history entries don't exist.
##### Steps to reproduce:
1. Pick a URL you're sure you visited before (like, just now).
2. `:open` and start typing the URL

As I said, it only works for some URLs, so you might have to do this a couple (dozen/hundred/thousand) times.

**Comment by gkatsev** [comment]
Yup, you're right. It seems like this is necessary for older versions of firefox but in current versions (46 and up) it doesn't seem necessary.

**Comment by ernestorenanche** [comment]
I am experiencing the same kind of problem here.

Ubuntu 16.04
Firefox 47.0
Vimperator 3.14

**Comment by gkatsev** [comment]
@ernestorenanche what is your `complete` option set to?

**Comment by ernestorenanche** [comment]
`set cpt=sbht` but changing it to other value does not resolve the problem

**Comment by Minoru** [comment]
@ernestorenanche, you sure? Try the default, `sl`, or just anything without `h`.

**Comment by Geng-G-Razor** [comment]
So, how can we solve this problem?

**Comment by gkatsev** [comment]
Well, clearly https://github.com/vimperator/vimperator-labs/commit/afe333b5615a5b42de209caec90ee8e5cf5cc80c isn't a good solution for the issue that was occurring. Or there's something else that I'm missing.
Also, I'm not sure if firefox 49 is having other issues in addition.

**Comment by Geng-G-Razor** [comment]
I feel quite unsteady in firefox 49, but i just can't figure out these little discomfort feelings

**Comment by alexconst** [comment]
I'm not sure if this is the same issue, or even if vimperator is to blame, but sometimes history also breaks for me. (FF 47.0 on linux)

I have been able to replicate it:
- search something on google
- open link in new tab with ctrl+click or `F`
- switch to new tab
- click on any link
- try to go back with `ctrl+o` I get this error:

    > Exception... "Component returned failure code: 0x805e0006 [nsIWebNavigation.gotoIndex]" nsresult: "0x805e0006 (<unknown>)" location: "JS frame :: chrome://liberator/content/history.js :: stepTo :: line 64" data: no]
- try to go back with mouse, click and hold so the history drop-down shows, click on older page, nothing happens

Is this the same problem?

BTW, is there a way to copy these exception messages?

**Comment by dstar4138** [comment]
I believe #590 is a fix for some if not all of these issues.

**Comment by Minoru** [comment]
This issue wasn't fixed.

I upgraded to FF 45.4.0 in the meantime, but I just checked and the problem is still there: Vimperator 3.14 installed from addons.mozilla.org doesn't display some of the history entries.

I then built new Vimperator from commit 424473faa30bf8aaa51a25bbf6ced365a0f1f1b0, and it still doesn't display all history entries.

**Comment by donniebishop** [comment]
Did not have history issues prior to the last few days, but I believe on the latest FF update (49.0.1, I believe) I no longer see any history completions.

**Comment by Minoru** [comment]
@donniebishop, this issue is about *some* history entries missing, not *all* of them. If fiddling with `h` in `complete` option (as described in the first post) doesn't help, than you're experiencing a different issue and should file it separately.

**Comment by nachtgeist** [comment]
I've had this issue many times, for a very long time - independent of FF and Vimperator versions.

I could track it down to some serious problems with places.sqlite. Sometimes it was enough to just delete `places.sqlite-shm` and `places.sqlite-wal` while FF wasn't running. (I'm on Linux, names for Win might differ)

In some occasions this wasn't enough and I just deleted all places.sqlite* which triggered a re-import from bookmarks.html (which is why I keep the FF setting `browser.bookmarks.autoExportHTML=true` around...)

This is a very hackish workaround and although this kills history information, at least my bookmarks and the history-to-come works consistently again. Until this beast bites again...

HTH

**Comment by Minoru** [comment]
@nachtgeist, you have a different (maybe related, but different) issue, since this one is dependent on Vimperator version. Please report yours separately.

**Comment by ernestorenanche** [comment]
I still experiencing this kind of issue with Firefox 49, Ubuntu 16.04 and Vimperator 3.14. This makes the plugin unusable.

**Comment by timss** [comment]
@ernestorenanche and you're sure it's not related to #590, and fixed in 3.15? Have to ask, since they're seemingly seperate issues and you didn't respond to proposed workaround earlier in this issue.

**Comment by ernestorenanche** [comment]
Idk, the 3.15 version has not been pushed to the Mozilla addons repository yet. Will try it as soon as it is released.

**Comment by Minoru** [comment]
I somehow missed the 3.15 update, sorry for the delay.

Anyway, I installed 3.15 from Mozilla addons and the problem is still there: if I have `complete` set to `hbs`, some history entries aren't shown despite being present in History dialog (and also in autocompletion results if I set `complete=lbs`.)

**Comment by Minoru** [comment]
3.16 works properly. Sorry I forgot to check and report back in time (it's been 5 months since the release.) Thank you for fixing this guys!
