### ISSUE TITLE
Add keybinding to show/hide statusline.

### ISSUE THREAD

**Issue by stepshal** [vimperator/vimperator-labs#547]
##### Issue type:

- Feature request

##### Description:

It would be cool to be able to just press keyboard key and show/hide statusline.

**Comment by timss** [comment]
The option you're looking for is `statuslinevisibility`. 

Not sure what the optimal solution would be here to keep track of changes, but [`statusline.setVisibility`](https://github.com/vimperator/vimperator-labs/blob/master/common/content/statusline.js#L129) includes some auto logic for fullscreen that makes it a bit quirky to use for toggling outside of `options` it seems.

Working (ugly) example:

    :js << EOF
    function togglestatusline() {
        if (['auto', 'visible'].indexOf(options['statuslinevisibility']) >= 0) {
            options['statuslinevisibility'] = 'hidden'
        } else {
            // or 'visible'
            options['statuslinevisibility'] = 'auto'
        }
    }

    EOF

    noremap gs :js togglestatusline()<CR>

Dunno if it should be a default keybinding or not. In that case `statusline.js` should probably be used.

**Comment by stepshal** [comment]
@tmss 
>  includes some auto logic for fullscreen
 But when i use VImperator i always in fullscreen, without toolbars, so didn't see statusline at all. And i want to see it when i maybe press button, but it didn't show up.

**Comment by gkatsev** [comment]
I don't think that showing the status bar on key commands is what we want. You can map `Up` and `Down` yourself if that is helpful. Though, maybe you just want to have `slv` to `visible`?
