### ISSUE TITLE
:sanitize don't work since FF 46

### ISSUE THREAD

**Issue by stepshal** [vimperator/vimperator-labs#556]
##### Issue type:

- Version compatibility

##### Version:

```
Firefox 46-50
Vimperator 3.14
```

##### Description:

When i make any argument to :sanitize error show up:
```TypeError: sanitizer.canClearItem is not a funcion```

##### Expected behavior:

Clear history with/without timestap.

##### Steps to reproduce:

In Firefox 46-50:
Type :sanitize with any argument.

**Comment by pale3** [comment]
That happened probably even earlier!  

At the moment in `common/content/sanitizer.js` we are calling `canClearItem`function
which if you look at http://hg.mozilla.org/releases/mozilla-release/file/tip/browser/base/content/sanitize.js, doesn't exist anymore. I dont have a time to track when it was removed, but certanly this is issue. 

Solution, in the common/content/sanitizer.js, remove those if/else statement at line 110, and just leve everything else intact. 

If you/anyone have some spare time, try to truck when `canClearItem` was removed from firefox release branch, and then we can patch it properly, if we want to have compatibility with earlier firefox versions.

**Comment by insivest** [comment]
@pale3 It was woking in FF 45.

**Comment by insivest** [comment]
@pale3 http://hg.mozilla.org/releases/mozilla-release/file/ea9e749bb86b/browser/base/content/sanitize.js

**Comment by pale3** [comment]
I have made PR for this, tested with ff 47 and ff 45. It should be fixed!

**Comment by stepshal** [comment]
@pale3 I found out that command-line history not clearing at all, and it was before this issue.

**Comment by pale3** [comment]
@stepshal 
does it work with attached patch against FF 45?

**Comment by stepshal** [comment]
@pale Sorry, seems it's trouble on my side. I checked in new profile in FF45 and it works.

**Comment by pale3** [comment]
Then this can be merged!
