### ISSUE TITLE
(Question) quick searching for URL-like strings

### ISSUE THREAD

**Issue by rr-** [vimperator/vimperator-labs#557]
I'd like to search the Internet for `t.1000`. Typing `:open t.1000` wil treat `t.1000` as a URL and will open (non-existing) http://t.1000/.

Typing `:open google t.1000` works but I wonder if there is any shorter way, like we can use `/` as per issue #4?

Thanks.

**Comment by pale3** [comment]
Noone forbids you or anyone else to have TLD defined with digits. This is prefectly legal. Thus any browser will react on it as destination URL 

You can always quote search parameter `:open "t.1000"`, to instruct browser
that your term is search string and not URL.

**Comment by timss** [comment]
@pale3 is right. Even using the standard navigation toolbar in Firefox it'll try to treat `t.1000` as a URL.

In addition to his proposed workaround, you could add another keybinding that explicitly uses your search engine of choice, for example using `<leader>`. 

    let mapleader=","
    noremap <leader>t :tabopen google 

Where `,t` should give you `:tabopen google |`, where `|` is your cursor.
Of course, whatever keybinding works the best for you is fine.

**Comment by rr-** [comment]
>Noone forbids you or anyone else to have TLD defined with digits. This is prefectly legal. Thus any browser will react on it as destination URL 

I never claimed this is wrong behavior, I just looked for a trick like the one mentioned in #4 . Thanks for the tips, I like @timss solution.

**Comment by timss** [comment]
Good to hear :+1:
