### ISSUE TITLE
Implement continuous scroll effect option for page jumps

### ISSUE THREAD

**Issue by robrechtdr** [vimperator/vimperator-labs#56]
Currently I'm scrolling (jumping) mostly in half pages while going through pages. The disadvantage of the jumping behavior is that each time you go down, you need a small amount of time to recognise where you are in the whole of the page. When scrolling with a mouse, you don't have this problem and the navigation ends up faster in the end in a significant number of cases.

A convenient setting imo would be to enable an option that would enable one to apply a continuous scroll effect similar to the mouse on page jumping. Preferably applyable down to a single jump effect (e.g. half-page jump).

**Comment by gkatsev** [comment]
Given that we barely have enough people work on vimperator, I'm going to close this.
