### ISSUE TITLE
shift insert erase text

### ISSUE THREAD

**Issue by deadc0de6** [vimperator/vimperator-labs#560]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
```

##### Description:

When inserting some text from the *selection buffer* into a text area (as for example the one for filling new bug report on github) using SHIFT+Insert, the text is written where the cursor is however everything below it is completely removed.

##### Expected behavior:

I would expect the text to be pasted where the cursor is without actually erasing what remains after.

##### Steps to reproduce:

see *Description* above. This happens in any editable text area.

**Comment by benoit-pierre** [comment]
This happen with the command line too. As a workaround, since I use CopyQ to synchronize clipboard and mouse selection, I remapped `Shift+Insert` to `Control+v`:
```
inoremap <S-Insert> <C-v>
cnoremap <S-Insert> <C-v>
```

**Comment by deadc0de6** [comment]
Thanks for your support.

Well the selection buffer and the clipboard are two different things and I use them differently. I don't want to have the same behavior as `Ctrl+v` but wants `Shift+Insert` to paste what is in the *selection buffer* (which in my case is not the same buffer).

Any other solution ?

**Comment by timss** [comment]
Seems related to #452

**Comment by benoit-pierre** [comment]
The following patch fix the issue:

```diff
diff --git i/common/content/editor.js w/common/content/editor.js
index 8a4a6f3..4727a09 100644
--- i/common/content/editor.js
+++ w/common/content/editor.js
@@ -83,7 +83,8 @@ const Editor = Module("editor", {
                 let rangeEnd = elem.selectionEnd;
                 let tempStr1 = elem.value.substring(0, rangeStart);
                 let tempStr2 = util.readFromClipboard();
-                elem.value = tempStr1 + tempStr2;
+                let tempStr3 = elem.value.substring(rangeEnd);
+                elem.value = tempStr1 + tempStr2 + tempStr3;
                 elem.selectionStart = rangeStart + tempStr2.length;
                 elem.selectionEnd = elem.selectionStart;
```

**Comment by deadc0de6** [comment]
it does, thanks a lot for that !! :thumbsup:

**Comment by timss** [comment]
@benoit-pierre Sweet. Would you be interested in making a PR?
