### ISSUE TITLE
Extend makefile for signing

### ISSUE THREAD

**Issue by SammysHP** [vimperator/vimperator-labs#566]
Since Firefox 48 it is not possible to disable the signature verification for add-ons. There is an API to sign add-ons semi-automatically: https://addons-server.readthedocs.io/en/latest/topics/api/signing.html

Following modifications to the Makefile are necessary:

- Change the UUID of the XPI to a custom one (read from a configuration file)
- Also read the API user and token from the configuration file
- Increment the version to something unique (e.g. `${VERSION}.$(date '+%Y%m%d%H%M%S')`)
- Submit XPI via the API and check the response code.
- On positive response, check every 1 minute if the XPI is ready for download
- When ready, download signed XPI

**Comment by SammysHP** [comment]
I'm working on it, first tests look good.

**Comment by stepshal** [comment]
@SammysHP 
>  it is not possible to disable the signature verification for add-ons. 
Not true, there is hack already.

**Comment by SammysHP** [comment]
LOL, that was fast. But I wonder how long this will work.

**Comment by sandermarechal** [comment]
Any update on this? I got Firefox 48 pushed today and Vimperator has stopped working.

**Comment by stepshal** [comment]
@sandermarechal Why? If e10s is disabled it's should work fine.

**Comment by sandermarechal** [comment]
I have e10s disabled. My Firefox 48.0.1 disables Vimperator because the Vimperator XPI (using 3.14.0) is unsigned.

**Comment by stepshal** [comment]
@sandermarechal It can't be, are you installed VImperator from AMO?

**Comment by sandermarechal** [comment]
Maybe not, I can't remember. I removed Vimperator and reinstalled it. Now it does work on 48.0.1
