### ISSUE TITLE
"Preferences" button does nothing in FF Add-ons page

### ISSUE THREAD

**Issue by nschley** [vimperator/vimperator-labs#574]
##### Issue type:
- Bug report
##### Version:

```
Vimperator: 3.14.0 (created: 2016/06/07 23:58:16)
Firefox:    Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0
```
##### Description:

"Settings" button does nearly nothing.  When I click it, a small pale yellow box with an 'X' in the upper right appears for a fraction of a second in the middle of the screen before disappearing.
The small box is approx 1 text line high by "1 average word" wide.
##### Expected behavior:

With a settings button present, I'd expect some sort of non-trivial response.
##### Steps to reproduce:

Open FF Add-Ons window.  Click Vimperator's "settings icon" from the add-ons list, or open Vimperator's page and click on the Settings button.

This reproduces when starting FF normally or the following ways:
- firefox -no-remote -P
- firefox -no-remote -P <fresh profile> -vimperator "+u NONE"
- Note:  the button may not say "Settings" exactly.  I'm running the German language version, so my button is labeled, "Einstellungen."

**Comment by gkatsev** [comment]
We probably shouldn't have a settings button given how vimperator is configured.
While it'll be cool if hitting that settings button would allow you to edit your vimperatorrc file, it's probably not worth adding and there isn't really anyone who has the time to add it in.
I think that https://github.com/vimperator/vimperator-labs/blob/71e029e4ef323448ff04d21ea49e5b19f90bbbf0/vimperator/install.rdf#L14 might be responsible for it but I'm not sure.

**Comment by timss** [comment]
I didn't check that line specifically, but I tested the button on my laptop with a pretty old install of vimperator and it took me to the preferences help page. After updating to 3.14.0, it no longer seems to do anything. Seems like you're onto something, @gkatsev

**Comment by apheleia** [comment]
I call dibs on this issue 🙂
