### ISSUE TITLE
Statusline does not show

### ISSUE THREAD

**Issue by pelegm** [vimperator/vimperator-labs#575]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
```

For a while now I don't see the status line. I don't see the address of the page I'm browsing, I don't see any hint that `y` actually yanked this address, I don't see the mode, or the scrolling percentage in long pages, etc.

However, the output of
```
set statuslinevisibility?
```
is
```
statuslinevisibility=visible
```
(after consulting https://github.com/vimperator/vimperator-labs/issues/382).

Not sure it is relevant, but the output of
```
set status?
```
is
```
status=input,location,bookmark,history,tabcount,position
```

Any extra info you may need?

**Comment by timss** [comment]
Let's start simple; have you checked that the toolbar for the statusline is enabled?

Menu -> View -> Toolbars -> Liberator Statusline Toolbar.

**Comment by pelegm** [comment]
Simple enough. In fact, I had to go to
```
:emenu View.Toolbars.Customise… 
```
and look for `Liberator Statusline Toolbar` there. I never new about this option, and in fact **never** use the window menus.

Thanks! I guess I should close this issue now.

**Comment by timss** [comment]
Great :+1: 

It's the same if you use `about:customizing` or just add it using View -> Toolbars.
