### ISSUE TITLE
Firefox Developer Edition compatibility

### ISSUE THREAD

**Issue by wasamasa** [vimperator/vimperator-labs#576]
##### Issue type:

- Version compatibility

##### Version:

```
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
```

##### Description:

As of Firefox 48, add-ons must be signed to be installed.  For a developer, one of the ways around this is to include signing into the build process as outlined in #566.  The officially recommended way however is to use the developer edition, disable the signature check and install the add-on there.  The problem with this is that it is two major versions ahead of regular Firefox, currently at 50.  I've tried using Vimperator there, but got an error, so that route doesn't work for me.

##### Expected behavior:

Getting no errors at all in Firefox 50.

##### Steps to reproduce:

    TypeError: 'stopPropagation' called on an object that does not implement interface Event.

**Comment by timss** [comment]
I'm curious, did you try to install vimperator using the steps described here as well? Haven't gotten around to try this myself on the upcoming versions yet.

https://github.com/vimperator/vimperator-labs/blob/master/CONTRIBUTING.md#development-installation

**Comment by wasamasa** [comment]
I've done that in both regular and developer edition Firefox.  The former refused to load while the latter gave me the same error.

**Comment by timss** [comment]
Ok, thanks.

**Comment by stepshal** [comment]
It's e10s, which is not supported yet, you need to disable it. Go to about:config and set `browser.tabs.remote.autostart.2` to false.

**Comment by wasamasa** [comment]
Thanks, that solves it.  Time for a e10s ticket?

**Comment by davidsierradz** [comment]
If you have problems with Waterfox 55, search in about:config for 'browser.tabs.remote.autostart.2' and set to false, this seems to fix the issues so far.
