### ISSUE TITLE
autocmd -js here-document support

### ISSUE THREAD

**Issue by lolilolicon** [vimperator/vimperator-labs#577]
I'd like to request hereDoc support for `autocmd`, for example:

```
autocmd DOMLoad .* javascript <<EOF
(function(){
  return true;
})();
EOF
```

(Same for `autocmd ... -javascript`.)

**Comment by timss** [comment]
That'd be nice indeed! 

Unfortunately there's much to do and little time to work on functionality like this, so I have to echo the usual encouragement to submit a PR.

**Comment by lolilolicon** [comment]
Well, I've discoverd a better way...

js <<EOF
autocommands.add('DOMLoad', /.*/,
function(){
  return true;
});
EOF

so I kind of have lost the reason to do anything about this issue myself :P

**Comment by timss** [comment]
Ah, I see. That works too :+1:  
Anyway, if you change your mind .. :-)
