### ISSUE TITLE
Setting toolbars=none leaves a black horizontal line at top of window

### ISSUE THREAD

**Issue by ntwk** [vimperator/vimperator-labs#578]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
```

##### Description:

I am thinking about migrating from Pentadactyl to Vimperator and I am trying to replicate my Pentadactyl setup as closely as possible in Vimperator.

My preference would be to hide all Firefox and Vimperator GUI elements whever and whenever possible.  I like to see nothing but a webpage surrounded by my window's manager's border with all functionality being keyboard-driven.

The following lines in my `.vimperatorrc` file seem to get me most of the way there:

```
set noscrollbars
set statuslinevisiblity=hidden
set toolbars=none
```

However, setting toolbars to 'none' still leaves a black, one pixel tall horizontal line running across the top of the browser window.

I realize that this visual bug surely only matters to the aging, increasingly anal-retentive aesthete  that I am, but a fix for this really would make me very happy.  At one point Pentadactyl suffered from a similar issue, though it subsequently disappeared, which makes me think this can be fixed in Vimperator.

**Comment by timss** [comment]
Please see the solution in #182, I believe that should fix your problem :-)

Personally I use this, which is a bit more specific as far as CSS goes.

    style -name top1px chrome://* #navigator-toolbox::after { height: 0 !important; }

**Comment by ntwk** [comment]
The solution you referenced in #182 seems to fix the problem.  Thanks!

**Comment by timss** [comment]
Great!

**Comment by ArtemBan** [comment]
None of solutions worked for me. Firefox 54.0, linux.

**Comment by timss** [comment]
Compatibility probably isn't great for FF 54, but I haven't tested it
myself. Did it work for you in previous versions?

On Jul 10, 2017 21:49, "ArtemBan" <notifications@github.com> wrote:

None of solutions worked for me. Firefox 54.0, linux.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/vimperator/vimperator-labs/issues/578#issuecomment-314215312>,
or mute the thread

**Comment by ArtemBan** [comment]
Doesn't work in Firefox ESR too.
