### ISSUE TITLE
URL gets mangled on 'y'ank

### ISSUE THREAD

**Issue by l29ah** [vimperator/vimperator-labs#579]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
```

##### Description:

https://blog.torproject.org/blog/tor-project-elects-new-board%C2%A0-directors
gets converted to
https://blog.torproject.org/blog/tor-project-elects-new-board%A0-directors
on 'y'ank, producing an invalid url

**Comment by timss** [comment]
Seems to be something deeper than just yanking. The URL is displayed differently in vimperator (e.g. panel/command line/yank) than the native navpanel in Firefox.

Needs more testing.

**Comment by SammysHP** [comment]
y copies https://blog.torproject.org/blog/tor-project-elects-new-board%C2%A0-directors to the clipboard if `set yankencodeurl`.

**Comment by timss** [comment]
You're absolutely right. Thanks @SammysHP

**Comment by SammysHP** [comment]
But it seems to be wrong in the statusbar.
