### ISSUE TITLE
Location-bar completion shows nothing on Firefox49

### ISSUE THREAD

**Issue by ktns** [vimperator/vimperator-labs#583]
##### Issue type:
- Version compatibility

##### Version:

```
Vimperator:	3.14.0 (created: 2016/09/10 21:58:33)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
```

##### Description:
When smart completion mode is set as ```set complete=l``` on Firefox49,
smart completion does not show anything on completion list.

##### Steps to reproduce:
1. Install Firefox49.
1. Install vimperator (from addons.mozilla.org or 71e029e4ef323448ff04d21ea49e5b19f90bbbf0).
1. Type ```:set complete=l<CR>```.
1. Type ```:open <Tab>```.
1. Nothing shows up.

**Comment by timss** [comment]
Thanks for report. While it was reported earlier, I'm closing this in favor of #590 which has more activity and a PR #591 linked to it.
