### ISSUE TITLE
[Feature request] Conditional turn-on based on host names

### ISSUE THREAD

**Issue by xiaohan2012** [vimperator/vimperator-labs#584]
Is it possible to turn on the add-on based on the host names?

For example, when I am using Google Drive, I would like the add-on to be disabled because there are some short-cut key conflicts.

On the other hand, we browsing some news site, I'd like it on. 

Is there anyway to do so?

**Comment by timss** [comment]
I believe `ignorekeys` is the command you're looking for. 

liberator://help/browsing#:ignorekeys

**Comment by xiaohan2012** [comment]
That's cool! Thanks!
