### ISSUE TITLE
Smart Completions not work on Fx49

### ISSUE THREAD

**Issue by kesdoputr** [vimperator/vimperator-labs#590]
##### Issue type:

- Version compatibility

##### Version:

```
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0
```

##### Description:
- When i use vimp 3.14.0 with Firefox 48.02 and press t to open a new tab,i can see **Smart Completions**
under the **Search Keywords**, sample picture: https://i.imgur.com/rwDcTfO.jpg
- When i use vimp 3.14.0 with Firefox 49.0 and press t to open a new tab,the **Smart Completions**
disappear and just can see **Search Keywords**,sample picture: https://i.imgur.com/S6ngSgg.jpg

**Comment by girishb** [comment]
I'm also facing similar issues.

**Comment by teranex** [comment]
Similar over here: completions from buffers work but history (h) en location (l) do not work.
When I run firefox from the commandline I see the following error:

    Service creation failed for '@mozilla.org/autocomplete/search;1?name=history': TypeError: Cc[classes] is undefined

**Comment by kovrik** [comment]
Same thing.

**Comment by psihonavt** [comment]
+1

**Comment by fakedrake** [comment]
+1

**Comment by Stebalien** [comment]
@kovrik, @psihonavt, @fakedrake, @girishb,

Please use the :+1: [reaction](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) instead of posting a comment (so that subscribers don't get notified).

**Comment by grassofhust** [comment]
Hello:

I have a temporary fix. Add this line to your `.vimperatorrc` file.
```js
js services.services.autoCompleteSearch.class_="@mozilla.org/autocomplete/search;1?name=unifiedcomplete"
```

**Comment by HeidiSalami** [comment]
stopped working for me too, ff 49.0.1.

**Comment by x13945** [comment]
+1

**Comment by kazemihabib** [comment]
+1

**Comment by test-account-0** [comment]
+1

**Comment by stemar94** [comment]
can't you guys read, pls stop +1-ing this thread

> Please use the :+1: reaction instead of posting a comment (so that subscribers don't get notified).

**Comment by gabrielzhou** [comment]
same problem.

**Comment by JAORMX** [comment]
The workaround you posted worked for me. Thank you

**Comment by gkatsev** [comment]
If you haven't seen, there's a new version up on github. Still waiting on AMO.

**Comment by Smcchoi** [comment]
@gkatsev I have updated, but it still does not work without the hack. Bookmarks and etc shows up, but still not the history.

**Comment by gkatsev** [comment]
3.15.0 hasn't been approved on AMO yet.

**Comment by gkatsev** [comment]
It's approved.
