### ISSUE TITLE
Vimperator can no longer seem to find / store history

### ISSUE THREAD

**Issue by acken** [vimperator/vimperator-labs#594]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
```

##### Description:

3 or 4 days ago vimperator stopped being able to read it's history. I can find the expected history within the default directory. Within desktop's history is empty. Result is that open and tab open always displays empty lists.

➜  ~ ls .vimperator/info/default 
history-command  history-search  ignored-keys  local-marks  macros  quickmarks
➜  ~ ls .vimperator/info/desktop 
history-command  history-search  ignored-keys  local-marks  macros  quickmarks

##### Expected behavior:

To get a list of history elements that I can search and choose from

**Comment by rr-** [comment]
Duplicate of #590 

Temporary fix is to add

```
js services.services.autoCompleteSearch.class_="@mozilla.org/autocomplete/search;1?name=unifiedcomplete"
```

to your `.vimperatorrc`.

**Comment by acken** [comment]
Awesome sauce!
