### ISSUE TITLE
gtk-dialogs/popups override

### ISSUE THREAD

**Issue by neg-serg** [vimperator/vimperator-labs#604]
##### Issue type:
- Feature request

##### Version:

Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0

##### Description:

Is it possible to override default gtk3-dialogs with vimperator-like like it had been implemented  in conkeror? For example, if you select some file to upload you have to use gtk-dialogs. Is there way to override this without doing modifications in firefox code? Also you still need to use gtk autocomplete lists, where vimperator bindings doesn't work.

##### Expected behavior:

Conkeror-like load/save/select file dialog

##### Steps to reproduce:

Try to upload some file, anything that except filepath from you.

**Comment by timss** [comment]
Thank you for this feature request.

This issue definitely annoys me as well, but I'd say it's outside of the scope of Vimperator and certainly comes with additional overhead to maintain and support that is not available. Not even sure if it's possible anymore without altering the firefox code.

Interesting links if you want to look into a possible workaround yourself:

- https://bugzilla.mozilla.org/show_bug.cgi?id=298848
- https://aur.archlinux.org/packages/firefox-kde-opensuse/
- http://www.rosenauer.org/hg/mozilla/file/4d52d2b45cf0/mozilla-kde.patch
- https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Tutorial/Open_and_Save_Dialogs
- http://askubuntu.com/questions/2495/how-can-i-get-firefox-to-use-dolphin-instead-of-nautilus

Some may or may not be out of date. The dialog is called 'filepicker'.
