### ISSUE TITLE
Wrong version in Makefile in tag vimperator-3.15.0

### ISSUE THREAD

**Issue by nachtgeist** [vimperator/vimperator-labs#608]
The XPI provided under releases/ seems ok, however when built from source the vimperator XPI advertises itself as 3.14. (didn't look into muttator)

**Comment by gkatsev** [comment]
Oops, I guess I ended up forgetting to commit it. Must've made the change but never added it to the repo.

**Comment by gkatsev** [comment]
Fixed it in post :P

Thanks for letting me know.

**Comment by stepshal** [comment]
@gkatsev New muttator version when?
