### ISSUE TITLE
Facebook.com Enter key issue 

### ISSUE THREAD

**Issue by qubitnerd** [vimperator/vimperator-labs#61]
1.goto facebook.com
2. type out something in the search bar
3. hit enter key 

expected result is to initiate a search but hitting enter key does not work 
 however hitting insert key (going to ignore mode> then hitting enter works fine
so i tried remapping `<Enter> <Ins><Enter><Ins> `, but that does not work either

**Comment by gkatsev** [comment]
I'm going to close this and keep the discussion going in #90.
