### ISSUE TITLE
smart completion with :t doesn't work with FF 49

### ISSUE THREAD

**Issue by djz88** [vimperator/vimperator-labs#611]
##### Issue type:

- Bug report

##### Version:

```
<!-- (Paste the output of `:version` here) -->
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
```

##### Expected behavior:

when I use command ```:t KEYWORD ``` I see only search keywords(search engines) but not smart completion(history bookmarks) like in older version of FF

##### Steps to reproduce:

```:t KEYWORD```

**Comment by thejan2009** [comment]
```
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
```

Also applies to ```tabopen```, ```open```, ```winopen``` and similar.

**Comment by djz88** [comment]
I think it is duplicated #590 

Closing this.
