### ISSUE TITLE
3.14.0 still listed as current version on addons.mozilla.org

### ISSUE THREAD

**Issue by ciwchris** [vimperator/vimperator-labs#618]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
```

##### Description:

[Mozilla.org lists current version as 3.14.0](https://addons.mozilla.org/en-US/firefox/addon/vimperator/). Looking at the [version info on mozilla.org](
https://addons.mozilla.org/en-US/firefox/addon/vimperator/versions/) 3.15.0 is listed, but the "Continue to download" button leads to a 404. I don't know where to report this. If this should be reported elsewhere I'm happy to do so if directed to another location.

##### Expected behavior:

3.15.0 to be the current version and the "Continue to download" button to download version 3.15.0.

**Comment by gkatsev** [comment]
This is because it takes a while for things to get approved. I just got an email that 3.15.0 was approved so, you should get it soon.

**Comment by ciwchris** [comment]
Thanks so much! I was trying to patiently wait but started wondering if something was up. I see the update, updated and all is well. Much appreciated. Thanks!

**Comment by gkatsev** [comment]
Yeah, I think they were just swamped the past couple of weeks. Previously, it was approved within about a day. Took quite a while this time.
