### ISSUE TITLE
colorscheme reverts to default on restart

### ISSUE THREAD

**Issue by LeLobster** [vimperator/vimperator-labs#623]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
```

##### Description:

I've made a custom colorscheme and called it dark, it loads up fine by running `:colorscheme dark` and works without issues. But on a shutdown and restart of FF it reverts back to the default scheme and I have to load up `dark` again.
Not sure if this is intended behavior or I'm missing something (though I can't find anything about it on the help pages about styling).

##### Expected behavior:

I'd expect it to stick with whatever colorscheme I'd tell it to.

**Comment by SammysHP** [comment]
This is absolutely intended. To make your configuration persistent, use `~/.vimperatorrc`.

**Comment by LeLobster** [comment]
So whenever I make changes to something I want to stick I just run `:mkvimperatorrc` and that config is loaded on startup every time?

**Comment by SammysHP** [comment]
I've never used `:mkvimperatorrc` but edited it by hand.

**Comment by LeLobster** [comment]
Perfect, thank you. I'll close this issue

**Comment by timss** [comment]
@LeLobster You can also edit your changes into `~/.vimperatorrc`, and use `:source ~/.vimperatorrc`.
