### ISSUE TITLE
Changes to proxy settings not saved from 'dia connectionprefs'

### ISSUE THREAD

**Issue by nachtgeist** [vimperator/vimperator-labs#628]
With #593 a few weeks back I added 'dia connectionprefs'. Only now I noticed, that any changes made to the dialog won't get saved when the dialog is closed with [Ok].

When said dialog is accessed via Preferenced→Advanced→Network→Settings all is fine and working as expected.

For debugging purposes I also tried to make a simple extension with only this menu-related XUL-overlay:

```
<menupopup id="menu_ToolsPopup">
    <menuitem id="helloworld-hello" label="helloworld;"
        oncommand="window.openDialog('chrome://vimperator/content/connection2.xul',
            'Connection Settings', 'modal=yes,centerscreen,width=488,height=535', null);"/>
</menupopup>
```

The dialog opens, but changes will be discarded just like it's happening with `dia connectionprefs`. (tried both `dia connectionprefs` and the hello-world-plugin from above with FF 38.0 and 45.4)

I'm at a complete loss here and don't know how to further track this down. I'd be glad If someone could point me in the right direction or maybe even take over...

Thanks!

**Comment by timss** [comment]
Tested by running the dialog directly from command line, and the options are indeed discarded.

    :js window.openDialog("chrome://browser/content/preferences/connection.xul", "", "dialog,centerscreen,width=488,height=535")

Looking at the `connection.xul` source code might yield some hints:

- https://dxr.mozilla.org/mozilla-central/source/browser/components/preferences/connection.xul
- https://dxr.mozilla.org/mozilla-central/source/browser/locales/en-US/chrome/browser/preferences/connection.dtd

This part looks relevant, but I may be lost.

      <radiogroup id="networkProxyType" preference="network.proxy.type" onsyncfrompreference="return gConnectionsDialog.readProxyType();">

Maybe the `gConnectionsDialog.readProxyType()` doesn't work as intended when in a dialog?

**Comment by nachtgeist** [comment]
Hi timss,

thanks for the hints.

That's what I thought at first as well. But in the meantime, I think I can rule out misbehaviour of functions that are stored in /browser/components/preference/connection.js.

To avoid re-compiling FF, I added connection.xul and connection.js to vimperator (override entry in  chrome.manifest). Then I checked (by console.log() and debug-alert()'ing whether those functions got called at all when the connections dialog was called from somewhere else than via prefs→adv.→network...  and they did. As long as the dialog is open, the order of called functions is exactly the same (triggered by events when clicking the radio buttons...).

It seems to me that somehow the data model is just dropped when the dialog is closed, whereas some magic stuff happens when that dialog was accessed the official way. I looked at the XUL/js code from the preferences and its "advanced" subpage, but couldn't find anything fancy which would explain what's (not) going on here...

**Comment by timss** [comment]
Sounds like you've researched that bit more than me, quite thorough :+1: 

Not sure what the reason could be maybe try `#developers@irc.mozilla.org` or some of the [other](https://wiki.mozilla.org/IRC#Commonly_Used_Mozilla_IRC_Channels) channels?
