### ISSUE TITLE
:open, :tabopen -- wrong behavior when IME used to enter multibyte characters

### ISSUE THREAD

**Issue by randomizedthinking** [vimperator/vimperator-labs#630]
##### Issue type:
- Bug report
##### Version:

```
3.15.0
```
##### Description:

When an IME is used to input multibyte texts under either `:open` or `:tabopen` mode, the IME would not be able to enter any text. A little more digging, it is because vimperator expects input when a key is pressed. Yet, input can be entered only after multiple keystrokes for multibyte languages. Something vimperator does in the background then interrupt the input process.

Further, I notice that it occurs when `complete` setting is turned on. Other commands like `:set` which uses complete function has the same issue.

This issues occurs for both sogou and bing input IMEs.

**Comment by timss** [comment]
One thing that strikes me is that Vimperator has quite a few (native) Japanese users. Googling 'vimperator ime' yields some results, but I don't know nearly enough japanese to understand much of it. Still, some of the results include links to scripts and whatnot, might be worthwile to take a look.

**Comment by randomizedthinking** [comment]
Seems the issue disappeared with the latest firefox upgrade... so not a vimperator issue.
