### ISSUE TITLE
Can't enter "Insert Mode" on clicking text area when multiprocess tabs enabled

### ISSUE THREAD

**Issue by ka4eli** [vimperator/vimperator-labs#632]
##### Issue type:

- Bug report

##### Version:

Vimperator 3.15.0
Firefox Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0

##### Description:
Following the [tutorial](https://www.youtube.com/watch?v=442YSAqNyLM):

1) set
  **browser.tabs.remote.autostart** = **true**
2) create and set 
  **browser.tabs.remote.force-enable** = **false**
3) restart bowser

Go to google.com (for example) and try enter some text in search field - can't enter "Insert Mode",
everything that I type becomes Vimperator command.

**Comment by gkatsev** [comment]
Vimperator doesn't yet support multiprocess tabs, unfortunately.

**Comment by timss** [comment]
Thanks for your report. Closing in favor of #211.
