### ISSUE TITLE
When Firefox Addons Manager is open, Left clicking Vimperator OPTIONS box  does not work

### ISSUE THREAD

**Issue by joefiesta** [vimperator/vimperator-labs#635]
##### Issue type:

- Bug report

##### Version: 3.15.0

```
<!-- (Paste the output of `:version` here) -->   I would If I could figure out how to.  I issue :version, select the text, hit CTRL+C and then trying pasting (CTRL+V).   But, the text has not been put on the clipboard.  What was previously cut gets pasted.
```

##### Description:

When I open Firefox Addons, Vimperator is displayed with three boxes, OPTIONS  DISABLE and REMOVE.  clicking the OPTIONS box does not display any options.  A small window appears for a very brief time and then disappears.  
Happens on Vim 3.14.0 and 3.15.0.  Firefox fox is 49.0.2

##### Expected behavior:

 Some options to be shown, like is there a choice to have Vimperator Update itself automatically.

**Comment by timss** [comment]
Thanks for the bug report, but I believe this is related to #574. Closing as duplicate.
