### ISSUE TITLE
How to open current url with Google Chrome in Mac

### ISSUE THREAD

**Issue by elonwoo** [vimperator/vimperator-labs#639]
In Windows, it could be done with:
map ,c :js io.run("C:\Program\ Files\ (x86)\Google\Chrome\Application\chrome.exe", [buffer.URL])

how to do it in mac?

**Comment by timss** [comment]
You really only need to find out how to run Chrome from command line in Mac, and do that using Firefox or Vimperator API commands. Based on something I found on Google:

    :js io.run("/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome", [buffer.URL])

**Comment by elonwoo** [comment]
@timss It works. Thx!

**Comment by timss** [comment]
Great!
