### ISSUE TITLE
Javascript: getting value of an object

### ISSUE THREAD

**Issue by for-coursera** [vimperator/vimperator-labs#641]
##### Issue type:

- Bug report [?]

##### Version:

```
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:45.0) Gecko/20100101 Firefox/45.0
```
Firefox.app in question is actually Firefox Extended Support Release, which [seems](https://www.mozilla.org/en-US/firefox/organizations/faq/) to [be](https://www.mozilla.org/media/img/firefox/organizations/release-overview-high-res.d18fa90b7aad.png) the latest Firefox available (49.0.2 at the moment). Also, the same behaviour was confirmed with some older versions of Fx / Vimperator I had at hand.

##### Description:

Let's say I've just opened a [random Stackoverflow page](https://stackoverflow.com/questions/40577318/vimperator-and-javascript-getting-value-of-an-object), then I open Console in Firefox and run something like this:

    alert(document.getElementsByClassName("question-hyperlink")["0"]["firstChild"].textContent)

As a result, it will pop up me the question asked on that page (on [this particular page](https://stackoverflow.com/questions/40577318/vimperator-and-javascript-getting-value-of-an-object) it [would be](http://i.imgur.com/k8BenOp.png) `Vimperator and Javascript: getting value of an object`).

Now, I want to use that value in a script with Vimperator. Thus, I add something like this to my `.vimperatorrc`

    :js << EOF
    function dummyFu() {
        var myElement = document.getElementsByClassName("question-hyperlink");
        alert(myElement["0"].firstChild.textContent);
    }
    EOF
    map <F5> :js dummyFu()<CR>

However, when run on a [random Stackoverflow page](https://stackoverflow.com/questions/40577318/vimperator-and-javascript-getting-value-of-an-object), it says `TypeError: myElement[0] is undefined`.

So, what is wrong? Would be grateful for any suggestion, thanks.

**Comment by for-coursera** [comment]
See https://developer.mozilla.org/en-US/docs/Web/API/Window/content
Like, `content.document.getElementsByClassName("question-hyperlink")[0].firstChild.textContent;`

**Comment by timss** [comment]
Nice that you were able to solve it yourself, and thanks for posting a solution :-)

**Comment by for-coursera** [comment]
No, it's not me, but [your excellent help](https://github.com/5digits/dactyl/issues/196), actually :). Thanks again :).

**Comment by for-coursera** [comment]
No, it's not me, but [all the credits go](https://github.com/5digits/dactyl/issues/196) to @dkearns, actually :).
