### ISSUE TITLE
Mapping <CR> doesn't work

### ISSUE THREAD

**Issue by for-coursera** [vimperator/vimperator-labs#642]
##### Issue type:

- Bug report [?]

##### Version:

```
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:45.0) Gecko/20100101 Firefox/45.0
```
Firefox.app in question is actually Firefox Extended Support Release, which [seems](https://www.mozilla.org/en-US/firefox/organizations/faq/) to [be](https://www.mozilla.org/media/img/firefox/organizations/release-overview-high-res.d18fa90b7aad.png) the latest Firefox available (49.0.2 at the moment)

##### Description:

As title says, mapping `Return` key doesn't work any more (like `map <CR> y`). On the other side, combos `<C-CR>`, `<S-CR>` and `<M-CR>` do work just fine.

Also, can confirm this mapping did worked before, with Vimperator 3.10.1 (created: 2015/08/25 00:41:59) on some earlier versions of Firefox it was just fine.

**Comment by timss** [comment]
Hm, are you certain you were able to previously map `<CR>`? Certain keypresses are hardcoded because of their special behavior, and haven't always been usable in maps. Please see #10.

For now, please resort to using another key combination.

**Comment by for-coursera** [comment]
> Hm, are you certain you were able to previously map <CR>?

Absolutely. Moreover, it's mappable in Pentadactyl right now.
