### ISSUE TITLE
In FF 50, in the Add-ons Manager, clicking the Options button wouldn't open the options dialog.

### ISSUE THREAD

**Issue by axbender** [vimperator/vimperator-labs#646]
##### Issue type:

- Bug report

##### Version:

3.15.0 (created: 2016/10/05 01:11:26)

##### Description:

In FF 50, in the Add-ons Manager, clicking the Options button wouldn't open the options dialog. Instead, a tiny windows opens and closes immediatelay.

##### Expected behavior:

See the options dialog (if any).

##### Steps to reproduce:

see Description above

**Comment by timss** [comment]
Thanks for the bug report, but I believe this is related to #574. Closing as duplicate.
