### ISSUE TITLE
using o and shift insert to paste a url problem

### ISSUE THREAD

**Issue by mac1202** [vimperator/vimperator-labs#65]
Hello really annoying problem here forcing me to use pentadactyl for year but i m done too much performance issue with so I fill this bug report hoping it could be fixed.
I i copy text or a url i use the o key then shift + insert to paste my text then enter to launch a google search or to open it in case of a url.
The problem is when you press o in vimperator it auto suggest amazon and when you press shift+insert to paste your text it doesn t clear amazon so if i paste for exemple the word arrow and press enter it launch me a google search about arrowamazon the same thing with a url it add amazon to the end leading me to a 404 error. 
So its a really annoying bug hoping it could be fixed. thanks.

**Comment by gkatsev** [comment]
This has been fixed. Unfortuantely, it's a major change because we've removed the alt register emulation of <shift-insert>.

**Comment by pelegm** [comment]
Is it really fixed? Under 3.9?

#169 comes before version 3.9 in the commits log... However, the following mapping:
```vim
map stt t<S-insert>
```
does not inset the contents of the selected area, while pressing <kbd>t</kbd> and then <kbd>Shift</kbd>-<kbd>Insert</kbd> does.
