### ISSUE TITLE
Removal of printpreview toolbar

### ISSUE THREAD

**Issue by dschrempf** [vimperator/vimperator-labs#658]
##### Issue type:
The toolbar of printpreview is not removed after deletion of tab with `d`.

##### Version:
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0

##### Steps to reproduce:
1. Open printpreview with `:dialog printpreview`
2. Delete tab with `d`.

##### Expected behavior:
Deletion of tab and exit of printpreview mode.

##### Actual behavior:
The toolbar of the printpreview mode is not removed.  It cannot be closed anymore by pressing the `Close` button.

**Comment by Nefari0uss** [comment]
I am able to replicate this on Firefox 5.1 and on Nightly. OS is Windows 10 and Arch Linux.

**Comment by timss** [comment]
Thanks for submitting this issue. For now, please resort to using `C-w` instead.

**Comment by pale3** [comment]
latest release 3.16 fixes it

**Comment by timss** [comment]
Thanks for checking, @pale3. Closing.
