### ISSUE TITLE
Incompatibility with Tab Center

### ISSUE THREAD

**Issue by brortao** [vimperator/vimperator-labs#659]
##### Issue type:
- Bug report

##### Version:
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0

##### Description:
There's an addon called [Tab Center](https://testpilot.firefox.com/experiments/tab-center) from the Firefox Test Pilot programme that arranges your tabs vertically at the left of the window. When using this addon, it covers the Vimperator bar at the bottom of the page so you can't see what you're typing. (Unless you're typing something very long).

##### Expected behavior:
The Vimperator bar should move its left edge such that it's not covered by Tab Center.

##### Steps to reproduce:
Install Tab Center and Vimperator, then try executing any Vimperator command - you won't be able to see what you're typing.

I also submitted this as an issue to Tab Center [here](https://github.com/bwinton/TabCenter/issues/857).

**Comment by IsaacKhor** [comment]
Dublicate of #509

**Comment by timss** [comment]
Thanks for submitting this issue. Closing in favor of #509 (thanks @IsaacKhor).
