### ISSUE TITLE
ignorekeys -except doesn't unignore key combinations or capital letters

### ISSUE THREAD

**Issue by nslo** [vimperator/vimperator-labs#66]
nmap J `<C-PageDown>`
nmap K `<C-PageUp>`
nmap d `<C-w>`
ignorekeys add -except=J,K,`<S-t>`,d /international\.nytimes\.com/

d will be processed by vimperator, but the others will be ignored.

**Comment by binarious** [comment]
Same here. Any workarounds?

**Comment by ainola** [comment]
On the latest 3.9 version I'm unable to get J,K, or any shift combination to work either.

**Comment by maxauthority** [comment]
One might try the nightly which had some changes for keymappings (
https://github.com/vimperator/vimperator-labs/commit/662933c028aafc584aa4bf840b34cba9f551d84b
). Does it also happen there?

**Comment by nslo** [comment]
Yes, the problem is still there using the nightly from here: http://vimperator.mine02c4.nagoya/

**Comment by twouters** [comment]
It doesn't seem to be possible to exclude "t" for tabopen either?
Same issue or not?

**Comment by Sheile** [comment]
`nmap` convert key from one to another one.
When you press `J` key, `nmap J <C-PageDown>` configuration convert it to `<C-PageDown>`.
But, `<C-PageDown>` DOESN'T except in configuration.

Follow configuration work on me.
```
ignorekeys add -except=J,K,<C-PageDown>,<C-PageUp>,<S-t>,d /international.nytimes.com/
```

**Comment by nslo** [comment]
Yes, that works!  Thank you!
