### ISSUE TITLE
sanitize! doesn't work

### ISSUE THREAD

**Issue by JossMarley** [vimperator/vimperator-labs#666]
##### Issue type:

- Feature request

##### Version:

```
Vimperator: 3.15.0
```

##### Description:

In the directory `.vimperator/info/default/` is collected many personal information. I use `sanitize` command to clean all that stuff, but it doesn't work as expected. `sanitize!` is supposed to clean everything in `sanitizeitems`, but neither `history-command` nor `history-search` files (and probably it happens with other files too) are not cleaned at all!

**Comment by JossMarley** [comment]
I am not able to use `autocmd` with `sanitize` too!
`:autocmd VimperatorLeave :sanitize!` doesn't do anything!

**Comment by timss** [comment]
Some old, but possible still relevant info can be found in old issues mentioning the 'sanitize' function:

https://github.com/vimperator/vimperator-labs/issues?utf8=✓&q=is:issue%20sanitize

**Comment by JossMarley** [comment]
@timss actually is not the same case. In my case it shows no error, it simply doesn't work as expected, without printing any useful information about what happened.

**Comment by Ghosy** [comment]
Have you tried the command `:sanitize! -timespan 0`? I'm running 3.16.0, and `sanitizer.js` hasn't seen any changes between versions, and am having no issues with sanitzing `history-command` and `history-search`. I believe the default value for timespan is 1, which is will only clear things in the past hour.
