### ISSUE TITLE
FF51.0 breaks d (or :q) to close tab

### ISSUE THREAD

**Issue by rlue** [vimperator/vimperator-labs#670]
##### Issue type:

- Bug report

##### Version:

```
3.15.0
```

(on Mac OS 10.11 El Capitan)

##### Description:

After upgrading to FF51.0, `d` no longer closes tabs. `:q` also broken.

**Comment by 0x-gg** [comment]
I can confirm. Getting -
ReferenceError: tabs is not defined.

Even gt gT doesn't work for me.

**Comment by SammysHP** [comment]
Duplicate of #568.

**Comment by rlue** [comment]
Whoops, thanks
