### ISSUE TITLE
FF51.0 breaks :tabopen

### ISSUE THREAD

**Issue by suhrawardi** [vimperator/vimperator-labs#671]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### Description:

:tabopen is not working anymore.
Pressing `t` triggers `:tabopen`, but when pressing enter it fails with:
`Not a vimperator command: tabopen`

Thanks for looking into this!

##### Expected behavior:

I expected to open up a new tab... 😃 

##### Steps to reproduce:

Press the `t` key followed by an `Enter`

**Comment by suhrawardi** [comment]
Looks like a duplicate of #568

**Comment by rickr** [comment]
Came here via SO post http://superuser.com/questions/1171164/vimperator-tabopen-not-a-vimperator-command.

Version:
```
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0
```
E10s are disabled by plugin

I've noticed the following items are also not working after my upgrade to 51.

* `d` to close a tab
* `f` to follow hints

Please let me know if you would like separate tickets for them.

**Comment by fwonce** [comment]
Another broken feature: 'newtab' option

**Comment by nthorne** [comment]
Can confirm same issues as @rickr , running Firefox 51.0, vimperator 3.15.0 on NixOS 16.09.

f flashes a 'tabs is not defined' error message.

**Comment by Jamongkad** [comment]
Thank goodness I thought I was the only one. Same bugs running Firefox 51.0, Vimperator 3.15.0 and macOS Sierra 10.12.3

**Comment by woshilapin** [comment]
Same on Linux here.
Firefox 51.0
Vimperator 3.15.0
Debian 8 (Jessie)

**Comment by MoSal** [comment]
What @rickr mentioned. Plus related items `D`, `R`, `F`, extended hints, other items like `gt`, `gT`.

Time to move to ESR, I guess.

**Comment by anhari** [comment]
I have come to rely on vimperator after only a few weeks of usage.  Thank you all for the work you do on this project.

Same issues as listed above on:

Firefox 51.0
Vimperator 3.15.0
macOS Sierra 10.12.2

**Comment by lassiewoof** [comment]
Same issues (pressing d, f or t not working) on Linux.
Firefox 51.0
Vimperator 3.15.0
Fedora 24

**Comment by nvkrishna77** [comment]
Same issue on Mac (10.12.2) Intel. 

f, gn, t, gt, gT, F, d.. tabs + hints. 

I was quite worried till I saw this page. I restarted my firefox a few times and was about to kill my all old settings. 

Firefox version: 51.0.1 (64-bit)
Vimperator: 3.15.0

This is URGENT. I feel handicapped with vimperator support.

Thanks a lot of such a cool extension -- one of the very few I use in my browser.

**Comment by suhrawardi** [comment]
Btw, this fixes the `:tabopen` issue:
https://github.com/vimperator/vimperator-labs/issues/568#issuecomment-275075302
But other issues still exist, like the `f` and `F` not working.
Had a look at it, but looks like the work will only save us for the next 2 months or so, pls see:
https://github.com/vimperator/vimperator-labs/issues/211#issuecomment-249181301

VimFx has a similar issue:
https://github.com/akhodakivskiy/VimFx/issues/860

Quite unfortunate. It looks like a lot of development time is needed to make Vimperator and VimFX compatible with future versions of FF. And so far, not all API endpoints needed are available yet, see also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1215061

**Comment by DarkPrinceFrost** [comment]
@suhrawardi see my latest comment on https://github.com/vimperator/vimperator-labs/issues/568#issuecomment-275075302 to resolve the `f` and `F` functionality issues.

**Comment by FrankEular** [comment]
I confirm this bug for Firefox 51.0 (64-bit) and vimperator 3.15.0; Debian Linux, Jessie.

**Comment by ivotron** [comment]
An alternative is to downgrade to the last known good version ([50.1.0](http://ftp.mozilla.org/pub/firefox/releases/50.1.0/))

**Comment by samrocketman** [comment]
@suhrawardi said
> Looks like a duplicate of #568

Why not close this issue so all of the information and communication is in the original report?

**Comment by SammysHP** [comment]
Please stop commenting on both issues. We know what is broken and are working on a fix. All comments produce additional work. Time that we cannot spend on development of Vimperator! Also important new information might be missed due to the high amount of comments that don't help. If you want to say that you are affected too you can use the up-vote feature of GitHub.

**Comment by GuillaumeSeren** [comment]
Same problem here, on gentoo,
I am so used to vimperator, than without it I can barely use firefox if at all.

I know than this issue is probably adding some pressure on the project,
and I don't want to add more but is there any chance to have a fixed release soon ? 🍺

**Comment by suhrawardi** [comment]
Closing this issue, as it's a duplicate of #568. Please add important information etc to that issue.
Thx

**Comment by rr-** [comment]
I'm tired of everything breaking every single time Mozilla rolls out an update. These days we can't even install git version without some insane workarounds.

I hope vimperator becomes a browser on its own some day, without needing to rely on software that tramples on BC.

**Comment by oyearunpal** [comment]
Same here , :(

**Comment by nachoparker** [comment]
same here

**Comment by gkatsev** [comment]
Saying "same here" doesn't help. If you look at #568, you can see that it's been fixed and we're just waiting to be approved and released on AMO
