### ISSUE TITLE
[FF51] Search partially broken

### ISSUE THREAD

**Issue by SammysHP** [vimperator/vimperator-labs#676]
##### Issue type:

- Bug report

##### Version:

Latest version including the patch from @ma8ma

##### Description:

Search for a string. The first press of <kbd>Enter</kbd> highlights a match, but the search prompt stays active. Pressing <kbd>Enter</kbd> a second time fails with following error:

```
TypeError: findbar._setHighlightTimeout is not a function
```

##### Expected behavior:

Prompt closes, no error.

##### Steps to reproduce:

1. <kbd>/</kbd><kbd>a</kbd><kbd>Enter</kbd>
1. <kbd>Enter</kbd>

**Comment by marza91** [comment]
I also have this issue, Firefox 51.0.1 on linux. It might not be obvious, but the search actually works on the second enter key-press (although the error message shows up). Pressing 'n' starts browsing through matches as normal.

**Comment by SammysHP** [comment]
I don't want to open a PR yet because I'm not sure if this is enough and is backward compatible.

**Comment by ma8ma** [comment]
@SammysHP b266c23 works highlighting on 45.7.0 ESR, but state of *"Highlight All"* toggle button (it's in findbar) doesn't change turn on, and if continue searching another word in the state of off, highlighting doesn't remove from previous words.

**Comment by llinfeng** [comment]
@gkatsev How to apply the fix? I don't find an update through the `Extensions` page in my Firefox. The current version is updated on February 18; is there a place to download the latest `*.xpi` file? Thank you for the fix!

**Comment by SammysHP** [comment]
We do not provide nightly builds (yet) and there was no release after the fix.

**Comment by llinfeng** [comment]
@SammysHP Oh, then, are there instructions on how to build the `*.xpi` file on the user's end? I would like to give it a try if it is not too complicated. Or, should I be underestimating the effort it takes to build an add-on for Firefox, I will happily wait for the new release. Is the fix scheduled at any chance? Thanks a lot!

**Comment by SammysHP** [comment]
Since a few weeks ago it is not possible anymore to sign new addon. So you would have to build an unsigned addon and an unbranded version of Firefox (developer build won't work as well because XUL addon support will be disabled in a few weeks).

**Comment by SammysHP** [comment]
All instructions are in the README btw.

**Comment by llinfeng** [comment]
@SammysHP Thank you for clarifying! The README is super clear. Another note to add: once one have __signed__ his own build, he can get the new `*.xpi` file through the following steps:
1. Go to the page https://addons.mozilla.org/en-US/developers/addon/ and sign-in
2. Click on the `Manage Status & Versions` tab;
3. Find such file, with a lengthy name. Mine is `	
vimperator-3.16.0.20170321092026-fx.xpi`

Clicking on the *file* will get the "update" running!

**Comment by limansky** [comment]
@SammysHP Do you have any expectations for the fixed release date?

**Comment by SammysHP** [comment]
Once @maxauthority or @gkatsev decides to make a new release it will take approximately two weeks for Mozilla to review the addon and sign it.

@maxauthority, @gkatsev: What do you think? There were some fixes since the last release.

**Comment by tooxie** [comment]
👍

Please consider releasing this fix asap. Thanks!

**Comment by limansky** [comment]
Any news on this issue? Is vimperator still alive?

**Comment by llinfeng** [comment]
@limansky I am not part of the development team, but I have strong faith in their continuous effort. If there is something specific that is bothering you, please try to build the latest version yourself. The README file is super clear. [Hope this helps.]

**Comment by limansky** [comment]
@llinfeng Thanks for your reply.

Even though the readme is super clear, I think that it's not a such a big deal to make a new release instead of suggesting to build signed plug-in to all users (because one of the core features is broken).

**Comment by llinfeng** [comment]
@limansky As a "free-rider" myself, I would suspect that the it may become extremely hard to push new releases onto the Mozilla "market". If you try to build it yourself, you will see how intricate things are when it comes to crafting those "certified" plug-ins. I would think that building our own version is a good temporary solution. 

(Also, I am thankful that the vimperator project is not abandoned at all. For example, `Pentadactyl` has been long dead, and I was extremely disheartened when I learned about it.)
