### ISSUE TITLE
Does not work with FF51

### ISSUE THREAD

**Issue by odins-raven** [vimperator/vimperator-labs#681]
##### Issue type:

- Bug report

##### Version:

```
<!-- (Paste the output of `:version` here) -->
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### Description:

Vimperator 3.15.0 does not work with Firefox 51 anymore. The plugin loads, however, if I press f to follow links, the links are no longer annotated with numbers I can press. It used to work with Firefox 50.

##### Expected behavior:

Pressing f should show a number for each link that I could press to follow the link.

##### Steps to reproduce:

Update to the above versions (I'm running Lubuntu Linux). Press f to follow a link.

**Comment by IronhandedLayman** [comment]
I can concur with this. Exact same version as above only Mac not Ubuntu. Plugin also loaded with me too, but pressing f to follow links does not work, and pressing t no longer opens a new tab. 

After rolling back to 
```
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0
```
both issues work as expected.

**Comment by ma8ma** [comment]
It solved in #675 and updated [version 3.16.0](https://github.com/vimperator/vimperator-labs/releases/tag/vimperator-3.16.0) in repository. Now, we are waiting approval by AMO for updated version addon. Or you can build own version, see comments for [@timss](https://github.com/vimperator/vimperator-labs/pull/675#issuecomment-276303232), [@chocolateboy](https://github.com/vimperator/vimperator-labs/issues/568#issuecomment-275891186).

**Comment by timss** [comment]
@ma8ma is correct, but thanks for reporting this issue anyway :)

**Comment by timss** [comment]
Oh and btw @IronhandedLayman, operating system doesn't matter with regards to Vimperator as long as we're just talking Firefox internals :) It can matter however for clipboards and other such things.

**Comment by user471** [comment]
@timss 
Is there any use for unsigned vimperator-3.16.0.xpi here https://github.com/vimperator/vimperator-labs/releases? 
Wouldn't it be better to put some signed version instead?

**Comment by timss** [comment]
@user471 Some use yes, if you use an [unbranded](https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds) release of Firefox (which allows `xpinstall.signatures.required=false`). Generally AMO is the intended mainstream source though.
