### ISSUE TITLE
Multiple keys are not working (d,:q)

### ISSUE THREAD

**Issue by mayanksuman** [vimperator/vimperator-labs#683]
##### Issue type:

- Bug report

##### Version: 

```
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### Description:
Some key like d (for closing tab) and :q is not working. :q command produce a error "Reference Error: tabs is not defined"
May be this issue is linked to a recent change in [Firefox 51](https://arstechnica.com/information-technology/2016/12/firefox-takes-the-next-step-towards-rolling-out-multi-process-to-everyone/).

##### Expected behavior:
These commands should close the active tabs.

##### Steps to reproduce:
In Firefox 51 issue either of d or :q to reproduce it.

**Comment by SammysHP** [comment]
This was fixed with the latest release 3.16.0.
