### ISSUE TITLE
Share history between :tabopen and :open

### ISSUE THREAD

**Issue by jonhoo** [vimperator/vimperator-labs#69]
Say I use `:tabopen` to do a Google search. Then I want to edit the search. A simple way of doing so would be to press `:o ` followed by arrow up, edit the search, and then press enter. Unfortunately, `:to` and `:o` currently use different histories, making this impossible. I'd have to open the modified search in a new tab, which is not ideal.

**Comment by gkatsev** [comment]
Going to close this as it'll be unlikely to happen.
