### ISSUE TITLE
Question: signed vs unsigned

### ISSUE THREAD

**Issue by samrocketman** [vimperator/vimperator-labs#695]
##### Issue type:

- Question

##### Version:

Pertains to all official project GitHub releases.

##### Question

Why not upload a signed version to GitHub releases?  I tend to sign my own software releases as an author.

> Note: I am not familiar with the AMO release process.

**Comment by pale3** [comment]
@samrocketman good question, I'm also wondering why this is not yet included into release process, while contrary it should be!

**Comment by gkatsev** [comment]
I could be wrong, but I'm not sure other users would be able to use a self-signed version, so, I think it's as useless as uploading an unsigned version.

**Comment by samrocketman** [comment]
Does mozilla independently sign the copy which is published on AMO?  i.e. the "official signed copy" is out of the vimperator team's control?

**Comment by gkatsev** [comment]
Yeah, basically the official release is gated on being approved on AMO.

**Comment by samrocketman** [comment]
I think that answers my question then.  The signing isn't controlled by the vimperator team but instead Mozilla.

**Comment by samrocketman** [comment]
https://github.com/vimperator/vimperator-labs/pull/694#issuecomment-277645280

@SammysHP Your response seems to indicate you as a developer can sign an add-on for Firefox.  Why not upload signed builds to the releases on GitHub?

**Comment by SammysHP** [comment]
Because you must sign it yourself. Only unlisted addons can be signed automatically. It might be possible to sign an addon for GitHub independently, but it won't be compatible with the official release (you'd have to uninstall the official version). And I don't know if the automatic signing might be suspended if there are too many installs in the wild.

**Comment by samrocketman** [comment]
> I don't know if the automatic signing might be suspended if there are too many installs in the wild.

Something I can ask Mozilla I guess.  Thanks for your insight.
