### ISSUE TITLE
Tabopen has stopped working

### ISSUE THREAD

**Issue by Mehradzie** [vimperator/vimperator-labs#701]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### Description:

The *tabopen* command has stopped working. when I press **T** or **t** rather than the full list I get the following,

> No Completions
> ▶tabopen

and when I press enter, 

> Not a vimperator command: tabopen

##### Expected behavior:

tabopen used to bring up *search keyword* and *smart completion* list and even if I didn't choose anything and pressed enter, it would open a new tab. 

At the moment *opentab* command and "o" are working exactly how they should.

##### Steps to reproduce:

1. Press "t" 
2. Hit Enter

**Comment by Mehradzie** [comment]
I just noticed. The same issue with the **tabclose** command

> Not a vimperator command: tabclose

and pressing <d> or <D> does absolutely nothing.

**Comment by PipocaQuemada** [comment]
This is a known issue.  See e.g. #699, #568.  The latest release, 3.16 fixes this and was published a week ago; I believe that we're just waiting on Mozilla to approve it and release it on their end.

**Comment by SammysHP** [comment]
Closing as this is a duplicate. The issue was already fixed and the new release is in the review queue already for a few days.

**Comment by Mehradzie** [comment]
Thanks guys. glad to see the community is on top of the issues already.
By the way, what's wrong with the website?
[http://www.vimperator.org/](http://www.vimperator.org/ )

Getting **Server not found**

**Comment by gkatsev** [comment]
Must've been a glitch in the matrix. The simulation has restarted successfully and everything should be all set now.
