### ISSUE TITLE
Invisible or non-working statusline

### ISSUE THREAD

**Issue by marza91** [vimperator/vimperator-labs#704]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.16.0.20170207083324 (created: 2017/02/07 08:33:24)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### Description:

Not sure if this is a known issue or not, or just me not knowing what I'm doing;
The statusline/bar seems to be invisible/not working for me any more. I updated to 3.16 yesterday by building manually, but this has been an issue since about the time the Tab control functionality stopped working earlier (which is working great again now, thanks!). I've tried setting 'statuslinevisibility' and 'status' to different things, but it seems like I can't make anything show up at the bottom. The only thing in my rc file is "set gui=none" but removing that doesn't change anything. I've also tried messing around a bit with the statusline styling, but the issue seems to be that there isn't any text in the statusline at all(?)

Am I missing a setting, or has the line stopped working generally? Couldn't find any similar issues here. I can try and look into this myself later today if it's a (unknown) bug.

##### Expected behavior:

See the current page I'm on, get feedback when using 'yy' or searching with '/' & 'n'

##### Steps to reproduce:

Do anything that should give feedback on the statusline.

**Comment by marza91** [comment]
Finally found the problem, I had apparently turned off the "Liberator Statusline Toolbar" by right-clicking the GUI. Didn't even know that was a setting. Isn't it possible to turn this on/off using command mode?

**Comment by timss** [comment]
Vimperator does have an option to trigger the statusline using e.g. `:set statuslinevisibility=hidden`, but this is done differently than hiding it as a toolbar entirely. 

In cases like these, it's better to just use the regular toolbar menu, or customize feature of Firefox because of the way toolbars (such as the liberator statusline) is set up.
