### ISSUE TITLE
:q not working

### ISSUE THREAD

**Issue by noughtmare** [vimperator/vimperator-labs#706]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### Description:

Pressing `:q` (or `:quit`) and then enter gives me this error: "ReferenceError: tabs is not defined".

##### Expected behavior:

The current tab should close.

##### Steps to reproduce:

Press `:q` and then enter.

**Comment by apheleia** [comment]
Thanks for the report @noughtmare.

This is a known issue and has been fixed on the `master` branch. Everyone is waiting for Firefox to approve the new version 3.16.0 of Vimperator, which will be compatible with Firefox 51.

See also, among others, #699 and #701

**Comment by noughtmare** [comment]
Ah, I tried searching but I couldn't find any open issues. Thanks.

**Comment by ddnomad** [comment]
Damn I've just installed this cool addon only to find out that it doesn't support FF51 :(
