### ISSUE TITLE
Typo in common/content/statusline.js ?

### ISSUE THREAD

**Issue by cmcaine** [vimperator/vimperator-labs#707]
https://github.com/vimperator/vimperator-labs/blob/master/common/content/statusline.js#L48

s/libeator/liberator

?

**Comment by gkatsev** [comment]
Looks like it. Nice catch. Care to submit a PR?

**Comment by cmcaine** [comment]
https://github.com/vimperator/vimperator-labs/pull/708

I don't know what the code does, so didn't want to submit a PR immediately. Probably should have anyway. Pretty unlikely they meant to always return 10, or whatever this does :)

**Comment by timss** [comment]
Fixed and merged in #708.
