### ISSUE TITLE
[FF51] Just updated to FF51, can't open new tabs and other missing functionality?

### ISSUE THREAD

**Issue by Griffinhart** [vimperator/vimperator-labs#709]
##### Issue type:

- Bug report

##### Version:

```
Vimperator: 3.15.0 (created: 2016/10/05 01:11:26)
Firefox:    Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### Description:

Updated and restarted Firefox. On starting, I got an error message from Vimperator, "Unknown option: tabnumbers".

Tried to open a new tab via `t` - "Not a vimperator command: tabopen". Can't close tabs either, as "Not a vimperator command: tabclose".

e: Other missing commands: `tabprevious`, `tabnext` - actually, *everything* that has to do with tabs, except for `tabgroups`.

e: Also, the Vimperator command line doesn't expand upwards whenever I enter the leader character, like how it used to.

![untitled](https://cloud.githubusercontent.com/assets/3744055/22809740/352e9b4a-eee9-11e6-8da3-f9c49e749e9b.png)

##### Expected behavior:

Was expecting to be able to use Vimperator the way it used to work - `t` as a shortcut for `:tabopen`, for example.

**Comment by Griffinhart** [comment]
Tried reverting to Vimperator 3.14.0; did not solve the issue.

Reverted to Firefox 50.1.0 (using Vimperator 3.15.0), and that fixed the missing commands problem (command line is still being weird, though).

**Comment by bigeast** [comment]
Same problem.
It seems Vimperator 3.16.0 fix the problem for FF51, but it can not be installed through the offical way.
I build the 3.16.0 version but Firefox warned me that the add-on is not verified thus can not be installed.
I googled a bit and in the about:config page, I changed the value of **xpinstall.signatures.required** into false, but that not help!
Can someone show me how to install the newest version of Vimperator?

**Comment by apheleia** [comment]
You cannot simply install Vimperator 3.16 until it is available as an official Firefox add-on. You have to have a signed version.

`xpinstall.signatures.required` only works with the development build of Firefox.

**Comment by trss** [comment]
Any idea when it is expected to be available? Such as avg/min/max time taken to be available in the past?

**Comment by Griffinhart** [comment]
Oh, I'm dumb. This is a duplicate of e.g. #701. Closing as duplicate.

**Comment by trss** [comment]
These are all duplicates of #568 but since that's locked asked here, thanks to your report!

**Comment by gkatsev** [comment]
The reason t was locked is because the discussion there started going down a bad avenue. It would be nice if people didn't keep opening new issues relating to that.

**Comment by trss** [comment]
That's right.

Would still like to know if anyone has any idea what kind of timeline to expect. It's been more than a week now but feels like more than a month!

Does it normally take days/weeks/months? Has it ever taken a year?!

Won't bother again. Let's just hope it happens soon. Do chip in with inputs in the meanwhile.

**Comment by tigren** [comment]
It has been several days since version 3.16.0 tagged, but at Firefox add-on page there is still no new version. I guess I have to register a developer account and sign it by myself.

**Comment by apnof** [comment]
@tigren when i try to sign it in the [Mozilla Add-on Developer Hub](https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted), i get the following message:
> Your add-on failed validation with 1 error.
> Duplicate add-on ID found.

I was using the file "vimperator-3.16.0.xpi" from here [here](https://github.com/vimperator/vimperator-labs/releases/tag/vimperator-3.16.0)

**Comment by tigren** [comment]
@apnof Please check the introduction here https://github.com/vimperator/vimperator-labs/issues/568#issuecomment-275891186

**Comment by trss** [comment]
https://blog.mozilla.org/addons/2017/02/14/add-ons-update-92/

### The Review Queues

In the past month, **1,670** listed add-on submissions were reviewed:

- **1148** (69%) were reviewed in **fewer than 5 days**.
- **106** (6%) were reviewed **between 5 and 10 days**.
- **416** (25%) were reviewed **after more than 10 days**.

There are **467 listed add-ons** awaiting review.

**Comment by lordtoniok** [comment]
> Jorge Villalobos wrote on February 15, 2017 at 9:27 am :
> 
>  It’s near the top of the queue, but due to its complexity it probably needs an admin reviewer to give it a look. Currently, their plate is fairly full, so it might take a while.

**Comment by trss** [comment]
Just in case there are folks who're subscribed to this and didn't see https://github.com/vimperator/vimperator-labs/issues/568#issuecomment-280786520.

>Vimperator 3.16.0 has been officially approved. They did note two things that need to be looked at for an upcoming release. I'll open a new issue for those.

>Also, thanks to everyone who made this release possible!
