### ISSUE TITLE
Audio/Visual bell when following hints

### ISSUE THREAD

**Issue by vpetro** [vimperator/vimperator-labs#718]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.16.0.20170217123651 (created: 2017/02/17 12:36:51)
Firefox:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### Description:

Error bell triggered when following hints. The hint action doesn't make a difference. Following regular hints (type `f` and then type the number) or extended hints with `;ANYTHING` results in either visual or audible error bell (depending on configuration value). 

##### Expected behavior:

I expect the error bell not to be invoked when following valid hints.

##### Steps to reproduce:

- go to any page that has links
- press `f`
- type the any hint number
- observe audible or visual bell

**Comment by SammysHP** [comment]
I'm not able to reproduce this.

**Comment by harciga** [comment]
Ahh, this is killing me too. And to think it's going to take weeks for Mozilla to approve any updates...

**Comment by jstetten** [comment]
Looks like @jspam submitted a patch.

@harciga and anyone else, the bell can be temporarily silenced with `:set visualbell=true`.

**Comment by vpetro** [comment]
The PR has been approved. I am not sure who is responsible for merging it. 

Another solution is to build a version of vimperator that includes the patch. 

I also would like to say "thank you" to @jspam for the code and @SammysHP for reviewing it.
