### ISSUE TITLE
Mozilla dropping support as of Firefox 57, alternative roadmap needed. 

### ISSUE THREAD

**Issue by tecfu** [vimperator/vimperator-labs#721]
Mozilla is dropping support for extensions that do not use the WebExtensions API as of version 57 (see https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/). 

Further - as an everyday Vimperator user, I've been continuously downgrading my Firefox version in order to maintain compatibility with Vimperator. Eventually this tactic will be untenable. 

Today I discovered palemoon - https://www.palemoon.org/ and have been unsuccessfully trying to install Vimperator on it. That experience has caused me to raise the issue of Vimperator's future. 

Can we use this thread to create a roadmap for Vimperator once Firefox no longer supports it?

**Comment by Nefari0uss** [comment]
See #705.

**Comment by tecfu** [comment]
Thanks.
