### ISSUE TITLE
Use ctrl + I to edit text areas on Mac

### ISSUE THREAD

**Issue by llinfeng** [vimperator/vimperator-labs#726]
##### Issue type:

- Bug report

##### Version:

````
Vimperator:	3.16.0 (created: 2017/02/01 00:55:15)
Firefox:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0
````

##### Description:

I am not able to use Ctrl + I on mac. The error is saying that: "Command not found: gvim".

##### Expected behavior:

I would expect an external/temporary Vim editor shall pop up. On Windows machine, GVim should be started; and on Mac, MacVim should be started. (For better graphical rendering.)

##### Steps to reproduce:

Press <kbd>Ctrl</kbd> key and <kbd>I</kbd> at the same time, on a Mac machine.

**Comment by klas-genestack** [comment]
The problem is that on frigging mAcoS (or how should it be capitalized nowadays) it's really hard to get an application in $PATH for installed applications (not for shell in a terminals).  Try this:
```vim
set "editor=/usr/local/bin/gvim -f"
```

**Comment by llinfeng** [comment]
This works! Thank you!

**Comment by 3xp10it** [comment]
When I tried set "editor=/usr/local/bin/gvim -f",it doesn't work for me,my os is macOS sierra,can you help me?

**Comment by llinfeng** [comment]
Hi @3xp10it, did you drop the line to the `~/.vimperatorrc`? If so, what do you get when you run `which gvim` from the Terminal? Your gvim may have been stored somewhere else. Let me know if this solves your problem.

**Comment by 3xp10it** [comment]
`which gvim`
output:gvim not found
when I try `brew install gvim`,brew hints:No similarly named formulae found.

**Comment by 3xp10it** [comment]
Hi @llinfeng ,below is what I've tried:
`which gvim`
output:gvim not found
when I try `brew install gvim`,brew hints:No similarly named formulae found.

**Comment by llinfeng** [comment]
Maybe you want to install MacVIM through "home brew"? This may create an alias as "going".

All the best,

-Linfeng

**Comment by klas-genestack** [comment]
@3xp10it, it's a bit surprising that you want to use vim given that you haven't installed it.

`brew install macvim` then.

**Comment by 3xp10it** [comment]
Hi, @klas-genestack ,I have installed macvim,and I posted this issue to macvim to,see this,<a href="https://github.com/macvim-dev/macvim/issues/473">link</a>

**Comment by klas-genestack** [comment]
@3xp10it
I'm not sure why it doesn't work for you, MacVim quits just fine for me here.
