### ISSUE TITLE
Some default shortcuts missing, random small bugs

### ISSUE THREAD

**Issue by iDoMeteor** [vimperator/vimperator-labs#730]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### Description:

On Fedora 24 now 25, I have many Firefox profiles (200+) with Vimperator installed on most of them.  The several default shortcuts no longer work - in any of them.  For instance, neither :t or :tabnew work.  Driving me insane.  There are other minor things off here and there, there is just something overall amiss.  How can I investigate this issue further?

##### Expected behavior:

I expect default shortcuts to work and they do not, :b often does not work as well.

##### Steps to reproduce:

Not sure, but it did seem to occur around the time I did a distro level upgrade with dnf.

**Comment by gkatsev** [comment]
It looks like you need to update to vimperator 3.16.0

**Comment by iDoMeteor** [comment]
I always install via Firefox Addons page, the version there is 3.15.0

**Comment by iDoMeteor** [comment]
Also, t for tabopen.. says 'not a vimperator command tabopen <param>'

**Comment by iDoMeteor** [comment]
That fixed it, thanks!
