### ISSUE TITLE
TypeError On Invoking Find in Page If Matching Patterns Found

### ISSUE THREAD

**Issue by femnad** [vimperator/vimperator-labs#731]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.16.0 (created: 2017/03/03 22:36:22)
Firefox:	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
```

##### Description:

Invoking find on page with `/` creates a non-fatal transient error message on its first run if a matching pattern is found. The message is as follows:

`TypeError: findbar._setHighlightTimeout is not a function`

##### Expected behavior:

No messages except for `Found pattern ...`.

##### Steps to reproduce:

Open a page and search for a string should could be located in the page.

**Comment by SammysHP** [comment]
Fixed by #737.
