### ISSUE TITLE
Status line incorrect (frozen)

### ISSUE THREAD

**Issue by axel-angel** [vimperator/vimperator-labs#735]
##### Issue type:

- Bug report

##### Version:

Starting with commit 06987920f65ef7ed91e7fe2987fabf395c32648e
    Fix misspelled words (#686)

```
Version Information
Vimperator:	3.16.0 (created: 2017/03/06 11:08:35)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
```

##### Description:

Go to any page, status line is correct
:open any other page, status line is frozen to last page, doesn't update

##### Expected behavior:

go to any page, and status line shows current page url

##### Steps to reproduce:

clone repo, checkout 06987920f65ef7ed91e7fe2987fabf395c32648e, make, start browser, install ext, restart browser, :open vimperator intro page, open a github page.

**Comment by SammysHP** [comment]
Duplicate of #724.

**Comment by axel-angel** [comment]
@SammysHP Thank you for the lightning fast answer and excuse me for the duplicate :+1:
