### ISSUE TITLE
Does vimperator support macOS keyboard?

### ISSUE THREAD

**Issue by 3xp10it** [vimperator/vimperator-labs#739]
Does it support macOS's keyboard for special key like `command`,`option`..?
Can I map hot key bind with macOS's special key like `command`,`option`?

**Comment by timss** [comment]
Yes, you should be able to. From the help pages (`:h map`):

>Most keyboards have some modifiers such as the control, alt or meta keys. In
>order to create a mapping that uses these keys the correct prefix must be used
>within the angle brackets.

    <C-x>: The control or ctrl key.
    <A-x>: The alt key.
    <M-x>: The meta key, windows key, or command key
    <S-x>: The shift key.
