### ISSUE TITLE
Updating the HACKING file

### ISSUE THREAD

**Issue by gkatsev** [vimperator/vimperator-labs#74]
Currently, the hacking file recommends a code style that uses some mozilla-specific extensions to the language. I think it is time to update this to remove all mozilla-specific uses. There are several reasons for this. First, if a developer is unfamiliar with the mozilla-specific extensions they will be confused by the code and be less likely to produce working code or they will be less likely to contribute. Second, with EcmaScript 6, several features are being added such as `let`. The mozilla-specific versions of let, which is what the hacking file currently asks for will no longer be valid once proper implementations of ES6's `let` semantics are implemented. We've already been bit by this (see #40).
@maxauthority thoughts?

**Comment by timss** [comment]
#398 Relevant.

**Comment by timss** [comment]
Closed as of #451. Also see #168 for further discussion.
