### ISSUE TITLE
a hint problem, please help me 

### ISSUE THREAD

**Issue by wangding** [vimperator/vimperator-labs#748]
##### Issue type:
- Bug report

##### Version:
- OS: CentOS 7
- Desktop: gnome
- firefox: 52
- vimperator: 3.16

##### Description:

![hint](https://cloud.githubusercontent.com/assets/1182720/24574037/852c85dc-16bf-11e7-9e19-19d7a0a6f1d6.png)

##### Expected behavior:

open the hint 27

##### Steps to reproduce:

0. open the url;
1. press f;
2. the hint number appear; 
3. press 27, 27 show in bottom bar, but hint 27 can not open the url

**Comment by laurentbardin** [comment]
Working as expected here (Mac OS 10.12.4, FF 52.0.2, vimperator 3.16.0).

The odd thing is, when typing numbers to follow a hint, the `Follow hint` prompt should **not** echo them, and the hints should start filtering as soon as you press the first number. My guess is what you're typing is interpreted as plain text, for some reason, and not as a hint number.

The issue could be with the input method implementaion you're using. I don't know how Gnome behaves when using Chinese input methods, but could try some other one if available, to see if it fixes the problem? Also, could you test on another Desktop Environment, like KDE or Xfce?

**Comment by wangding** [comment]
Thank you. I'll try it.

**Comment by wangding** [comment]
The problem is Chinese input method. Thank you!
