### ISSUE TITLE
Vimperator breaks Shortcuts in jupyter notebook

### ISSUE THREAD

**Issue by Moneysac90** [vimperator/vimperator-labs#749]
##### Issue type:
- Bug report

##### Version:

```
Vimperator:	3.16.0 (created: 2017/04/02 14:00:59)
Firefox:	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
```

##### Description:

Anaconda (see https://www.continuum.io/downloads) provides jupyter notebooks for python development and easy embedded documentation. With "TAB + Enter" you normally execute the selected cell. However this does only work for code cells but not for markdown cells anymore. 

##### Expected behavior:

The shortcut "TAB + Enter" should execute markdown cells as usual. 

##### Steps to reproduce:

Install Anaconda (see https://www.continuum.io/downloads for installation instructions). Start Anaconda and launch a jupyter notebook. Try executing a markdown cell with "TAB + Enter".

**Comment by timss** [comment]
It's not so much as vimperator breaking the shortcuts as it's incompatible with certain custom keypresses to be captured by JS run on sites such as Jupyter notebooks. An optimal solution would be something like what is outlined in #70 or related issues, but this probably won't be coming anytime soon unless anyone commits a PR.

For now, use normal ignore (<kbd>Insert</kbd> etc) for challenging sites.
