### ISSUE TITLE
Thunderbird main window: "ReferenceError: statusline is not defined"

### ISSUE THREAD

**Issue by clange** [vimperator/vimperator-labs#752]
##### Issue type:

- Version compatibility

##### Version:

:version isn't working. It's 1.4, latest source built with `make xpi` from https://github.com/vimperator/vimperator-labs/commit/eabb291f1bd074fe460aa7c0fb53b8995842f986.

##### Description:

In the Thunderbird main window the status/input line is not working. It displays a red error message
> ReferenceError: statusline is not defined
and accepts no input; e.g. `:` has no effect.

##### Expected behavior:

Status line should be working

##### Steps to reproduce:

Just install Muttator and start Thunderbird (main window)

**Comment by sebastianst** [comment]
I can confirm this problem with Thunderbird 52.0 on Arch Linux and latest muttator from git (rev 5215 commit d3c61fa6).
As a consequence, many commands stopped working, like `s` for moving mail to a folder or `o` for opening a folder.

**Comment by jmechler** [comment]
I can also confirm this problem with Thunderbird 52.0 on Windows 10 and latest muttator from git (commit d3c61fa)

My primary use cases for vimperator are to quickly save to or navigate between folders and compose messages. none of that works.

**Comment by willsALMANJ** [comment]
This is unfortunate. I see this as well on Arch Linux. None of the key mappings seem to work and some of the commands are missing, though the command line still works with the commands that it has. Looking at the error console, I see lots of this warning:

```
Warning: ‘nsIOService::NewChannelFromURI()’ deprecated, please use ‘nsIOService::NewChannelFromURI2()’
```

which is probably okay for now, and I see this error:

```
ReferenceError: tabs is not defined
```
for [line 395 of statusline.js](https://github.com/vimperator/vimperator-labs/blob/master/common/content/statusline.js#L395).

I guess for now I'll go back to my old setup of Nostalgy and KeyConfig which still seems to work.

**Comment by Mo-M** [comment]
I can confirm this problem with Thunderbird 52.0 and 52.1.
Version 45.8.0 is the last working version.

**Comment by sebastianst** [comment]
Weirdly, the _older_ revision no. 5196, commit eabb291f, works for me with TB 52.1.0. Can anyone confirm this?

**Comment by majutsushi** [comment]
Yes, I can confirm that checking out that revision makes it work for me again.

**Comment by macrobl** [comment]
Git Bisect shows that it stops working with commit 8bec0af5 (Fix #677: SSL indicator broken in FF51)

**Comment by sebastianst** [comment]
A quick guess is that the `if (services.get("vc").compare(VERSION, "51") >= 0)` checks in commit 8bec0af don't work for 52

**Comment by demokritos** [comment]
I am not using Thunderbird and muttator, so this is the first try.

First, I have error message: `TypeError: services.get(...).defaultServer is null`, and next `ReferenceError: statusline is not defined`. Even if I comment out the lines including `if (services.get("vc").compare(VERSION, "51") >= 0)`, the first TypeError is not gone and another error comes: `TypeError: gDBView is null`.

I think that Thunderbird has a big change in version 52.

**Comment by caisui** [comment]
```diff
diff --git a/common/content/statusline.js b/common/content/statusline.js
index 71ee0fde..6ba238a5 100644
--- a/common/content/statusline.js
+++ b/common/content/statusline.js
@@ -77,7 +77,7 @@ const StatusLine = Module("statusline", {
         // In case of insecure login forms, connection icon is updated after page load.
         const VERSION = Services.appinfo.platformVersion;
         if (services.get("vc").compare(VERSION, "51") >= 0) {
-            gBrowser.addEventListener("InsecureLoginFormsStateChange",
+            config.browser.addEventListener("InsecureLoginFormsStateChange",
                                       function () {
                                           statusline.updateField('ssl', null);
                                       });
```

**Comment by demokritos** [comment]
@caisui Thank you. You're right. `gBrowser` seems defined in Firefox only. `ReferenceError: statusline is not defined` is caused by this.
`TypeError: services.get(...).defaultServer is null` and `TypeError: gDBView is null` disappeared after I set up an email account.

**Comment by jmechler** [comment]
The one line change from @caisui worked for me as well. I now have a fully functioning vimperator on latest thunderbird, both windows and linux. Has anyone submitted a pull request for this change? Or are the primary developers already planning to include it?

**Comment by vlcinsky** [comment]
@jmechler you mean muttator (not vimperator).

**Comment by jmechler** [comment]
Yes, muttator. Sorry about that.

**Comment by nbarrientos** [comment]
Same here, the patch above gets Muttator to work again (Thunderbird 52.2.1). Is there a PR for it?

**Comment by kchr** [comment]
Running Thunderbird 52.5.0, I get the following error when opening a calendar tab:
```
TypeError: config.browser is null
```

Am I the only one having problems with this? It seems to break the buffer list as well, aborting with the same error as referenced above.

**Comment by vlcinsky** [comment]
Having the same TB version I can confirm the same behaviour:
- `TypeError: config.browser is null` on opening the calendar tab
- after the calendar tab becomes one of open tabs, the buffer list blinks and does not show any entry
- after I close the calendar tab, the buffer list (`:b`) is working again.

Fortunately, I do not use calendar tab in TB, so it does not affect myself.
