### ISSUE TITLE
Popup dialogs not accessible

### ISSUE THREAD

**Issue by SammysHP** [vimperator/vimperator-labs#755]
##### Version:

```
Vimperator:	3.16.0.20170426105746 (created: 2017/04/26 10:57:46)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0
```

##### Description:

Firefox 53 changed the way popup dialogs (e.g. confirmation to install addon) are handled. With `gui=none` (or without the navigation bar in general) these popups are either completely invisible or flickering.

##### Expected behavior:

Popups visible and interaction possible.

##### Steps to reproduce:

- Set `gui=none`
- Install vimperator from XPI and try to confirm message.

**Comment by SammysHP** [comment]
I tried to fix this but the main problem is a race in the popup visibility callback somewhere in Firefox. There are several bug reports regarding popups that were fixed with FF53 and that introduced this (search for autohide, Linux, minimize, autofocus).

Vimperator just calls a (probably legacy) function to hide the toolbar or directly sets the collapsed attribute as a fallback. So this is a bug in Firefox, but one that cannot happen in the normal configuration because it is not possible to hide the navigation bar.

The current situation is even worse because the flickering popup prevents all key events to be processed by Vimperator. To fix this you could restart Firefox or press Alt to open the menu, then open the browser toolbox and change the collapsed attribute manually.

**Comment by Atlantic777** [comment]
For me it helps if I temporarily enable navigation bar just to accept or dismiss the pop-up. When the pop-up appears and flickering starts, I can still type in `:set guI=navigation` which open the navigation bar. When the navigation bar is present, flickering stops and I can interact with it normally.

**Comment by SammysHP** [comment]
@Atlantic777 
Yes, this worked for me most of the times. But at least once no input was possible and I had to kill Firefox.

**Comment by LonFas** [comment]
@Atlantic777 i do something similar before read this tread
cat ~/.vimperatorrc
```
map km :set gui=navigation <Enter>                                                                                                                                                          
map kM :set gui=none <Enter>
```
And i use :set gui=none with "i3-no-borders"

**Comment by SammysHP** [comment]
Since Firefox 56 this works again. I'll close this as "won't fix", let's call this a Firefox bug.
