### ISSUE TITLE
Is there a way to display or copy the current URL literally?

### ISSUE THREAD

**Issue by Kodiologist** [vimperator/vimperator-labs#763]
Vimperator:	3.16.0 (created: 2017/02/01 00:55:15)
    Firefox:	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0

The URL display in the status bar decodes percent-encoded ASCII characters and doesn't visually distinguish them from the corresponding literal characters. For example, if I go to:

    http://example.com/x%3Fx?x

then the status bar displays:

    http://example.com/x?x?x

which is a different URL, and not the one I'm visiting. It's also what gets copied to the clipboard with the `y` command. If I actually go to that URL, it's displayed literally (and hence indistinguishable from the first one).

This is all pretty confusing. Is there some some sort of option to prevent percent-encoded ASCII characters from being decoded?

**Comment by SammysHP** [comment]
The URLs in your example are identical, just differently encoded. There is no difference for the requested website.

You can change the behavior of <kbd>y</kbd> with `:set yankencodeurl`. If the option is enabled, the copied URL will be encoded.

**Comment by Kodiologist** [comment]
> The URLs in your example are identical

I disagree. For example, try clicking on each of:

- [one](http://en.wikipedia.org/wiki/?)
- [two](http://en.wikipedia.org/wiki/%3F)

The first link takes you to Wikipedia's main page. The second takes you to the article about question marks.

> You can change the behavior of `y` with `:set yankencodeurl`

Thanks, this works. The documentation is incorrect, though: it only mentions the space and non-ASCII characters, whereas if you have the option on, then `http://example.com/x%3Fx?x` will indeed be yanked that way, with the first question mark escaped and the second not.

**Comment by SammysHP** [comment]
Oh, I haven't seen that your example contains both `%3F` and `?`, which is a reserved character.

RFC 3986 says:

> Characters that are allowed in a URI but do not have a reserved   purpose are called unreserved.  These include uppercase and lowercase   letters, decimal digits, hyphen, period, underscore, and tilde.
>
>      unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
>
> **URIs that differ in the replacement of an unreserved character with   its corresponding percent-encoded US-ASCII octet are equivalent: they   identify the same resource.  However, URI comparison implementations   do not always perform normalization prior to comparison** (see Section   6).  For consistency, percent-encoded octets in the ranges of ALPHA   (%41-%5A and %61-%7A), DIGIT (%30-%39), hyphen (%2D), period (%2E),   underscore (%5F), or tilde (%7E) should not be created by URI   producers and, when found in a URI, should be decoded to their   corresponding unreserved characters by URI normalizers.

Try these two URLs:

```
https://en.wikipedia.org/wiki/Question_mark
https://en.wikipedia.org/wiki/Question_mar%6B
```

They are equivalent and will produce the same content.

It is true, that the decoded URL in the statusbar might be ambiguous, but this is only a minor cosmetic issue. IMHO yankencodeurl should be enabled by default because otherwise URLs might be invalid or not equivalent. See #25.

**Comment by Kodiologist** [comment]
Yeah, I tend to agree. Unfortunately, `yankencodeurl` also renders non-ASCII characters as percent-escaped bytes of UTF-8, as documented, so

https://ru.wikipedia.org/wiki/Анализ_(раздел_математики)

becomes the unreadable

https://ru.wikipedia.org/wiki/%D0%90%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7_(%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB_%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B8)
