### ISSUE TITLE
Smooth scrolling with j and k

### ISSUE THREAD

**Issue by sweenu** [vimperator/vimperator-labs#775]
##### Issue type:

- Feature request

##### Version:

```
Version Information
Vimperator:	3.16.0 (created: 2017/02/01 00:55:15)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0
```

##### Description:

It would be nice to have an option to have a smoother scrolling using j and k. By smoother I mean, like it would do with the mouse. As an exemple, it's would be the same type of scrolling that is enabled by default on chrome's Vimium extension.

##### Expected behavior:

A smooth scrolling using j and k (if enabled)

**Comment by skfarhat** [comment]
This has been bugging me since switching from Chrome Vimium. My current temp solution is to place: 

nnoremap j <down>
nnoremap k <up> 

in my ~/.vimperatorrc

**Comment by AhmedAA** [comment]
Smooziee plugin?

https://github.com/vimpr/vimperator-plugins/blob/master/_smooziee.js

**Comment by Sweenu** [comment]
It's not the exact same but it's close enough, I will use it, thank you! 👍

**Comment by JinhaoPro** [comment]
nnoremap j <down>
