### ISSUE TITLE
FF 56: Command suggestions background is transparent

### ISSUE THREAD

**Issue by ogkloo** [vimperator/vimperator-labs#777]
##### Issue type:
- Bug report

##### Version:
```
3.16.0
```
```
Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0
```

##### Description:
Whenever I go to input a command, the background of the suggestions pop-up is transparent, and features images. When used with a stylish theme that styles it, it refuses to change it's text color from the default black-ish color.

##### Expected behavior:
An opaque, text-only pop-up.

**Comment by ogkloo** [comment]
Screenshot for an example:
![2017-08-09-232027_3840x1080_scrot](https://user-images.githubusercontent.com/8551013/29156991-8286cde6-7d59-11e7-87ab-f6b0625ca8ce.png)

**Comment by wdbw** [comment]
Firefox version information is missing.

Also, do you get some error message when starting Firefox?

**Comment by ogkloo** [comment]
Added the Firefox version information.

I didn't get any sort of error on startup. Nothing really changed in my config from the boot where everything worked to when it didn't.

I did have to set a few things to off in about:config to prevent e10s from breaking everything, but those have been set to that for quite some time now.

**Comment by wdbw** [comment]
Thanks.

It looks like there are some new compatibility issues when using vimperator with Firefox 56 (Beta).

I suggest adding the Firefox version to the issue title.

**Comment by ogkloo** [comment]
Done. There was an update last night around the time these issues started popping up. Build ID was 20170808170225, I don't know if that's important. 

Several other addons also broke this morning for me.

**Comment by schlueter** [comment]
I'm seeing this with Firefox version 56.0b4  (64-bit) from the http://ppa.launchpad.net/mozillateam/firefox-next/ubuntu ppa with vimperator 3.16.0 installed from github.

**Comment by llorllale** [comment]
+1

Ubuntu 16.04.3 LTS
FF 56.0 64bits
Vimperator 3.16.0

**Comment by crashmaster** [comment]
+1

% cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

:version
Version Information
Vimperator:	3.16.0 (created: 2017/02/01 00:55:15)
Firefox:	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by tmsanrinsha** [comment]
When I execute following command
```
:hi CmdLine              color: #D0CFD0; background: #333333;
```
then output is
```
[Exception... "Component returned failure code: 0x804b0012 (NS_ERROR_UNKNOWN_PROTOCOL) [nsIStyleSheetService.loadAndRegisterSheet]" nsresult: "0x804b0012 (NS_ERROR_UNKNOWN_PROTOCOL)" location: "JS frame :: chrome://liberator/content/style.js :: Styles/this.registerSheet :: line 540" data: n
```
So highlight command is not work.

This is the lines around the error.
https://github.com/vimperator/vimperator-labs/blob/ae0df8040bc2821d6d0ce39a9c2f3b8feda4a3e4/common/content/style.js#L538-L540

I inserted
```
liberator.log(uri);
```
before line 538 and 540 and checked log using browser console.
The log is url encoded, these are decoded output.

```
vimperator: chrome-data:text/css,@namespace html "http://www.w3.org/1999/xhtml";
@namespace xul "http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul";
@namespace liberator "http://vimperator.org/namespaces/liberator";
/* Liberator style #176 */ @-moz-document url-prefix("chrome://liberator/"), url-prefix("liberator:"), url-prefix("file://"), url("chrome://browser/content/browser.xul"){
[liberator|highlight~=CmdLine] { color: #D0CFD0!important; background: #333333!important; }
}
```
```
vimperator: [xpconnect wrapped nsIURI]::
asciiHost: ""
asciiHostPort: ]]>
asciiSpec: "chrome-data:text/css,@namespace html "http://www.w3.org/1999/xhtml";
@namespace xul "http://www.mozilla.org%2..."
clone: function clone() { ... }
cloneIgnoringRef: function cloneIgnoringRef() { ... }
cloneWithNewRef: function cloneWithNewRef() { ... }
displayHost: ]]>
displayHostPort: ]]>
displaySpec: "chrome-data:text/css,@namespace html "http://www.w3.org/1999/xhtml";
@namespace xul "http://www.mozilla.org%2..."
equals: function equals() { ... }
equalsExceptRef: function equalsExceptRef() { ... }
filePath: "text/css,@namespace html "http://www.w3.org/1999/xhtml";
@namespace xul "http://www.mozilla.org/keymaster%2..."
hasRef: false
host: ]]>
hostPort: ]]>
originCharset: ""
password: ]]>
path: "text/css,@namespace html "http://www.w3.org/1999/xhtml";
@namespace xul "http://www.mozilla.org/keymaster%2..."
port: ]]>
prePath: "chrome-data:"
query: ""
QueryInterface: function QueryInterface() { ... }
ref: ""
resolve: function resolve() { ... }
scheme: "chrome-data"
schemeIs: function schemeIs() { ... }
setHostAndPort: function setHostAndPort() { ... }
spec: "chrome-data:text/css,@namespace html "http://www.w3.org/1999/xhtml";
@namespace xul "http://www.mozilla.org%2..."
specIgnoringRef: "chrome-data:text/css,@namespace html "http://www.w3.org/1999/xhtml";
@namespace xul "http://www.mozilla.org%2..."
username: ]]>
userPass: ]]>
```
First output contains css. So I executed `:colorscheme <my colorsheme>` and exetracted css from log, then wrote css in common/skin/liberator.css.
This is commit.
https://github.com/tmsanrinsha/vimperator-labs/commit/dd89ff10855da709cf1a20398e5914c8270ebf8f

Using stylesheet in common directory is not good because this is bug of firefox and some style is still collapsed but almost all style is fixed.

 I put xpi in https://github.com/tmsanrinsha/vimperator-labs/releases/tag/vimperator-3.16.0.20171002234644

**Comment by GuillaumeLeclerc** [comment]
Will it be released or do we have to install the xpi manually ?

**Comment by disconsis** [comment]
@tmsanrinsha 
The xpi does solve issue (as far as I could see), but the error message is still popping up

**Comment by tmsanrinsha** [comment]
@GuillaumeLeclerc My xpi is not official one. You have to install it.

**Comment by tmsanrinsha** [comment]
@disconsis Yes. It doesn't fix highlight command.

**Comment by pierg75** [comment]
I have the same transparency problem on Firefox 56 on Fedora 26, but on Fedora 27 Beta (Firefox still 56) vimperator doesn't work at all (no bar at the bottom).
I compile vimperator directly from the git repo (updated today).

**Comment by tigren** [comment]
@tmsanrinsha thanks for your xpi, it works. The dark transparent background looks super cool.

**Comment by tsaber** [comment]
thank you very much. I didn't know installing the fix was this easy.

**Comment by ogkloo** [comment]
Thank you @tmsanrinsha for the workaround. I don't know if I'm going to keep using vimperator just due to it not being compatible with FF57, but since you managed to fix it for some people, should I change the thread title to reflect that there's a workaround?

**Comment by SammysHP** [comment]
Included in #796.

**Comment by disconsis** [comment]
While this is a workaround of the reported problem, the issue is deeper than this and is not fixed by the xpi. The error that causes this problem still keeps popping up and some functionality (like highlight) is broken

**Comment by tmsanrinsha** [comment]
@ogkloo Yes.
And I found it is not necessary to build xpi to fix css.
I copied common/skin/liberator.css and add css of colorscheme to the file
and `source /path/to/your.css` in .vimperatorrc like this
https://github.com/tmsanrinsha/dotfiles/blob/master/home/.vimperator/colors/liberator.css
https://github.com/tmsanrinsha/dotfiles/blob/857ceb4d92f5bf7af2b49bbf7d3d527e6d674892/home/.vimperatorrc#L278

And I fixed style of CmdLine, it should be written with url-prefix(chrome://)
