### ISSUE TITLE
Some fn's seem broken in Debian 9 w/ Firefox 52

### ISSUE THREAD

**Issue by koreymacdougall** [vimperator/vimperator-labs#780]
Issue Type:
- Bug report

##### Version:

```
Vimperator: 3.14.0
Mozilla 5.0 (X11, Linux i686, rv 52.0, Gecko 20100101, Firefox/52.0)
Debian 9
```

##### Description:

Some vimperator functions seem broken in Debian (but working in Arch, w/ Vimperator 3.16)

Specifically - 
'f' - follow links - links do not appear
'd' - close tab - broken
't' - tab open - throws "not a vimperator command: tabopen"

P.S. - <3 vimperator ; thx to team

**Comment by SammysHP** [comment]
Yeah, because of `Vimperator: 3.14.0`. ;) Just update your Vimperator and it will work.

**Comment by SammysHP** [comment]
PS: 3.16.0 might not be shown as compatible, we really need a new release! @maxauthority, @gkatsev
