### ISSUE TITLE
Unable to open a new window using vimperator, must use default GUI.

### ISSUE THREAD

**Issue by R030t1** [vimperator/vimperator-labs#783]
##### Issue type:

- Bug report

##### Version:

```
Version Information
Vimperator: 3.16.1 (created: 2017/02/01 00:55:15)
Firefox: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0
```

Issue also happens on a fresh installation of Kubuntu 17.04. That is, I installed Vimperator and set up `.vimperatorrc`:
```
set gui=none,tabs
set hintchars="asdfjkl;"

noremap j 3j
noremap k 3k
```

##### Description:

`winopen [-private]` does not open a new window.

##### Expected behavior:

That a new [private] window be opened.

##### Steps to reproduce:

Hit w, hit enter; or type the command in its long form.

**Comment by laurentbardin** [comment]
Already fixed apparently. See #781.

**Comment by R030t1** [comment]
Thank you, I apologize for the duplicate report. It would be helpful if the referenced fix could be included in a release.
