### ISSUE TITLE
Open link hotkey not showing matches

### ISSUE THREAD

**Issue by Spunge** [vimperator/vimperator-labs#786]
Vimperator:	3.16.0 (created: 2017/02/01 00:55:15)
Firefox:	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

Please note that i'm using Firefox 56.0b9 (64-bit)

There used to be an overlay numbering every link that matched the search string when using the 'F'/'f' key to follow a link. The functionality is still there, but the overlay is not showing anymore.

In the screenshot below, i'm using the 'f' key to follow the computing link. When i continue typing, it will still follow the link, but no overlay is showing:

![computing](https://user-images.githubusercontent.com/1842108/30169633-4270dbac-93ed-11e7-87e1-d3bd5c815281.png)

**Comment by pchaitat** [comment]
T_T

**Comment by SammysHP** [comment]
Included in #796.
