### ISSUE TITLE
How to use a shortkey to select whole text of the page when it contains a text file?

### ISSUE THREAD

**Issue by c02y** [vimperator/vimperator-labs#787]
##### Issue type:

- Feature request

##### Version:

```
Vimperator:	3.16.0 (created: 2017/02/01 00:55:15)
Firefox:	Mozilla/5.0 (X11; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0
```

##### Description:
When a page contains only a text file and I want to select whole text of it (for example, the raw text of a source file in one project on github.com), how can I do that? 

I want to use `Ctrl-a` to select it all like Firefox without Vimperator plugin since the default `Ctrl-a` which is bound to "Increments the last number in URL" according to help page is rarely used by me.

**Comment by Koushien** [comment]
Adding `nnoremap <C-a> i<C-a>` to your .vimperatorrc should be sufficient.

NB Under default keymaps you can hit `i` to enter Ignore Mode and `Shift+Esc` or `Insert` to Ignore All Keys until you press either combo again.

**Comment by lbkvu** [comment]
Press i to enter Ignore mode, then Ctrl+A to select all.

**Comment by c02y** [comment]
Oh, right, I forgot `Ignore` key, thanks.
