### ISSUE TITLE
Unable to unmap A

### ISSUE THREAD

**Issue by hahuang65** [vimperator/vimperator-labs#788]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.16.0 (created: 2017/02/01 00:55:15)
Firefox:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0
```

##### Description:

Trying to do an 
```
unmap A
```
in the configuration file results in 
```
No such mapping: A
```
when clearly `A` does something.

On a related note
```
unmap a
```
does not work either.

##### Expected behavior:

Would like to unmap the A key. I end up with a bunch of unwanted bookmarks because I accidentally press `a` or `A`.

**Comment by SammysHP** [comment]
`a` is <kbd>A</kbd> and `A` is <kbd>Shift</kbd>+<kbd>A</kbd> (`<S-a>`). The reason that you cannot `unmap` the mapping is because it is a built-in mapping. But you can overwrite it with `:nmap <S-a> <Nop>`.

**Comment by hahuang65** [comment]
Thank you!
