### ISSUE TITLE
hintmode does not work correctly in multiple-tab window

### ISSUE THREAD

**Issue by c02y** [vimperator/vimperator-labs#789]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.16.0 (created: 2017/02/01 00:55:15)
Firefox:	Mozilla/5.0 (X11; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0
```

##### Description:

When I use hintmode (f/F) in one tab inside multiple-tab window, it does not work correctly. But if I move the same tab into a new window and use hintmode (f/F) in one-tab window, it works correctly. 

Check the gifs i recorded.  I use hintmode to open the hint of 40.

Besides, I don't have to hit `Enter` key after typing hint number in one-tab window. But I have to hit `Enter` key in multiple-tab window to go to that page which is the wrong page in the end.

##### Expected behavior:

`followhints` (`f/F`) will work correctly in multiple-tab window.

---------------------

In multiple-tab window, hintmode goes to the wrong page, and have to hit `Enter` key:

![recorded-mul](https://user-images.githubusercontent.com/2135996/30675010-8cefe254-9eb0-11e7-845f-f70bbce344b7.gif)

I move the same page into a new window, hintmode goes to the right page without hitting `Enter` key:

![recorded](https://user-images.githubusercontent.com/2135996/30675008-8cbd3ba6-9eb0-11e7-9aae-9c417685cd03.gif)

**Comment by SammysHP** [comment]
Can you please update your Firefox and try again?

**Comment by c02y** [comment]
@SammysHP My OS is CentOS 6.5 32-bit which is decided by my working environment, it is old but I cannot upgraded it (newer version is not able to run because it requires newer version of libraries), and Firefox 45.0 is the newest version I can use in this OS. Sorry about that.

Is this bug gone in newer version of Firefox?

**Comment by SammysHP** [comment]
Yes. FF 45 is just too old, even ESR is 52 already.

**Comment by c02y** [comment]
I tried it in another Linux distribution which supports the latest version of Firefox, the problem is gone, but I'm not sure if this is fixed by Firefox itself since these are two different environments and the new Firefox is completely clean and contains only vimperator plugin. But I already have been using the old Firefox for years.

Please keep this issue open, if any new info came up I'll post it here.

**Comment by SammysHP** [comment]
Firefox 45 was released at 8th March 2016 and the ESR version of it had its EOL at 7th March 2017 – this version is ancient and shouldn't be used (security!). There were some major changes in Firefox. These were adapted by Vimperater which made it incompatible with older versions of Firefox.

Sorry, but the only solution is to stick to an old version of Vimperator or (better!) update to the latest version of Firefox.
