### ISSUE TITLE
muttator: add "Show remote content in this message" for Message mode

### ISSUE THREAD

**Issue by vlcinsky** [vimperator/vimperator-labs#790]
##### Issue type:

- Feature request

##### Expected behavior:

Today when I open a message using remote content (images), it does not show them (and this is correct).

In some cases I need to do [Preferences] -> [Show remote content in this message].

As this is rather common use case for me, I would like to do that using some muttator command.

**Comment by Kerruba** [comment]
Can't you map the behavior to a key sequence? For example I've set up these:
```
nnoremap v :setlocal remotecontent<CR> # Show remote content for the current message
nnoremap <S-v> :setlocal noremotecontent<CR> # Disable remote content for currentmessage
```

**Comment by vlcinsky** [comment]
Yes, this works. I wonder, where could I find the information about `remotecontent` being variable, which can be set.

I will have to resolve the problem what key to map it to as `v` jumps somewhere (and at the same time allows showing remote content of the message).

Anyway, I guess, your answer resolves the issue.

Thanks.

**Comment by Kerruba** [comment]
Sometimes happens also to me. Try to set the remapping inside thunderbird directly...usually this solve the problem for me.
