### ISSUE TITLE
Are there any plan for firefox quantum?

### ISSUE THREAD

**Issue by mu-yu** [vimperator/vimperator-labs#791]
##### Issue type:

- Version compatibility

##### Version:

```
3.16.0
```

##### Description:
This extension is so cooooooooooooooooool!. But firefox quantum is coming, and firefox quantum is as cool as this extension.

So, are there any plan for firefox quantum?

**Comment by fukuang** [comment]
I'm happily using Firefox Quantum beta, with my sad mouse ...

**Comment by aspel** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1215061

**Comment by SammysHP** [comment]
See #705.

**Comment by mu-yu** [comment]
Sorry for the duplicate issue. I searched 'firefox quantum' but found nothing useful before created this issue.

What a pity!:(
