### ISSUE TITLE
Command Line went crazy on my old Thinkpad X230T machine (Windows 10 Pro)

### ISSUE THREAD

**Issue by llinfeng** [vimperator/vimperator-labs#803]
##### Issue type:
- Bug report / Version compatibility

##### Version:
I built the `*.xpi` file in late September myself.
```
Version Information
Vimperator:	3.16.0.20170928091306 (created: 2017/09/28 09:13:06)
Firefox:	Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
```

##### Description:
I am using exactly the same `_vimperatorrc` across three Windows machines, and a MacBook Air; and it is only on my Thinkpad X230T machine (built in 2013) that I see the following horrible scene. All the fonts are fine, but the icons are superbly large.
![commandline_maze](https://user-images.githubusercontent.com/5890407/31591894-2a8b34ce-b1f2-11e7-95bc-451b91d7a35b.png)
 
##### Expected behavior:
If I am using the same `_vimperatorrc`, I would at least expect the icons are displayed correctly (in normal size); and that the background of the command line shall be of darker color. I don't really recall whether I have done anything fancy to this X230T machine. 

##### Failed fixing attempts

I have tried to:
* Uninstall/Reinstall Firefox
* Especially, when uninstalling, I deleted every local folder that gets involved with `Mozilla` or `Firefox`.
* Setting the following command directly through Firefox "commandline": `highlight Normal background-color: black; color: white`. Here goes the error message that I get (including some "exception")
![banner_of_warning](https://user-images.githubusercontent.com/5890407/31592502-ca01bfe2-b1f6-11e7-921b-c468a4e92330.png)

**Comment by cyb1ove** [comment]
Yes, I have such errors.

**Comment by llinfeng** [comment]
@cyb1ove What particular hardware/software environment are you having? And, have you had specification for `highlight` settings? Here goes my set of colorization attempts (hopefully done correctly for the command line).

````
highlight Normal background-color: black; color: white
highlight CmdLine background: #191919; color: #afafaf; font-size: 9pt;
highlight CmdLine -append font-size:16px
highlight PromptText background-color: black; color: white
highlight InfoMsg background-color: black; color: white

highlight CompItem[selected] background-color: white; color: black

highlight Hint background-color: white; color: black; border: 1px solid #000000
highlight HintActive background-color: white; color: black; border: 1px solid #000000
highlight HintElem background-color: white; color: black; border: 1px solid #000000
````
These are from quite a while ago, but it is give me
![properlook](https://user-images.githubusercontent.com/5890407/31611883-db1e28d8-b24b-11e7-87ce-d0806c5d0c8d.png)
 this look on all other machines

**Comment by mistakeSF** [comment]
Ubuntu16.04  && firefox 54.0(64 bits)
met the same problem.

**Comment by llinfeng** [comment]
**Update**:
I figured out that switching to Firefox 55.0.3 64-bit version solves the problem on my 4-year old Thinkpad machine. Here goes all the relevant versions info:
* Firefox: 55.0.3 64-bit
* Vimpeartor: 3.16.0.20170928091306 

@mistakeSF, maybe switching to Firefox 55.0.3 may help you. ( @cyb1ove, maybe this also applies to your case.)

**Comment by FireyFly** [comment]
Duplicate of #777, see that issue for an xpi built with a workaround and see also #796 for a proper solution.

**Comment by llinfeng** [comment]
Thank you, @FireyFly
