### ISSUE TITLE
Hide scrollbars stopped working on Firefox 56

### ISSUE THREAD

**Issue by jstetten** [vimperator/vimperator-labs#807]
##### Issue type:
- Bug report

##### Version:
Vimperator:	3.16.0 (created: 2017/02/01 00:55:15)
Firefox:	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

##### Description:
I used to keep all scrollbars hidden. ":set scrollbars" stopped working for me when I upgraded to Firefox 56. The command has no effect anymore, whether set to true or false. No errors pop up in the console.

Has anyone else had this problem? Any workarounds?

**Comment by SammysHP** [comment]
Actually this is working but requires a refresh of all sites (stylesheet is not loaded dynamically). Working with the ff56-fixes branch only, of course.
