### ISSUE TITLE
vim vixen is good for ff-57+

### ISSUE THREAD

**Issue by transtone** [vimperator/vimperator-labs#811]
as it not mentioned in readme.

**Comment by SammysHP** [comment]
Can you submit a pull request?

**Comment by jklai** [comment]
I went ahead and created a PR for Vim Vixen as well as an update to the status of Tridactyl. Hopefully Mozilla allows for a more viable alternative to Vimperator soon. And thanks to the developers of Vimperator for all these years of work.

**Comment by nachoparker** [comment]
aggree, I am very happy with it

**Comment by SammysHP** [comment]
This was fixed by #813.
