### ISSUE TITLE
FF 60

### ISSUE THREAD

**Issue by aspel** [vimperator/vimperator-labs#822]
Moz devs added a new features 
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands/update

Any chances for reborn?

**Comment by bovine3dom** [comment]
@aspel, those have been in Firefox for a while, and only support single keys + modifiers: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands#Key_combinations

Even if it did, the core of Vimperator would have to be rewritten massively - see #705.

---

Are you aware of the new Vim-style Web Extension addons? There's a whole bunch to pick from:

- Tridactyl
- Surfingkeys
- Saka-key
- Vim-Vixen
- Vimium-FF

Tridactyl is already reasonably close to Vimperator in my usage, although I am somewhat biased as I have implemented the things that I wanted first :)

**Comment by aspel** [comment]
Thank you. :)

**Comment by SammysHP** [comment]
> Tridactyl is already reasonably close to Vimperator in my usage, although I am somewhat biased as I have implemented the things that I wanted first :)

I still miss the status bar. I'd like to remove the navigation bar and tab bar completely as I did with Vimperator.
