### ISSUE TITLE
:dialog import does not work

### ISSUE THREAD

**Issue by gurucubano** [vimperator/vimperator-labs#83]
:dialog import (to import for example bookmarks) only brings up a window saying:

"No programs that contain bookmarks, history or password data could be found"

This is with Firefox 33.0 and vimperator 3.8.2 on FreeBSD 11-CURRENT

**Comment by gkatsev** [comment]
I've just tried it locally and it is working for me with latest firefox and vimperator. Closing.
Please try again and report back whether it's fixed for you.
