### ISSUE TITLE
startup Firefox without going into insert mode

### ISSUE THREAD

**Issue by fohrums** [vimperator/vimperator-labs#88]
pentadactyl does this by default; but for Vimperator, how can I specify to have FF startup without going into insert mode @awesomebar?

WORKAROUND
=

- use the vimperator's help-page `liberator://help/intro`

**Comment by mrozekma** [comment]
Even when you disable the navigation bar (which is how I've always had things), the bar is still there, it's just hidden. So when you make a new window, your focus starts in the hidden navbar, and you start in insert mode. You can even start typing and see the auto-complete menu pop-up below an invisible navbar. Haven't found a solution yet

**Comment by c0ffeeartc** [comment]
I have `normal <esc>` in .vimperatorrc . Insert mode blinks but works as expected afterwards.

**Comment by fohrums** [comment]
@c0ffeeartc 
I actually ended up just using the local help-page as my homepage `liberator://help/intro`

**Comment by c0ffeeartc** [comment]
Hmm, I've just updated/restarted firefox and don't see insert mode anymore at startup. Hope it's permanent.

Vimperator: 3.9 (created: 2015/03/04 05:47:57)

Firefox 37.0.1: Mozilla/5.0 (X11; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by jflorian** [comment]
@c0ffeeartc Many thanks!  Your suggestion for `normal <esc>` is the only solution that's worked for me so far.  I should have thought to try something like that but I forget (or just don't realize) how vimmy the vimperator is.

**Comment by gkatsev** [comment]
I believe it's been fixed or no longer an issue, so, going to close this. If it's still an issue, holler and we can re-open.
