### ISSUE TITLE
Facebook comment boxes.

### ISSUE THREAD

**Issue by hundovir** [vimperator/vimperator-labs#90]
Apologies in advance if this is not the way to do it - I'm new to bug reporting. When inserting text in a Facebook comment, the box seems to be full of invisible code. I discovered this by using the Ctl-i external editor option. Vim opens and is full of html. Note: this applies to Facebook comment boxes on already posted "staus updates". Posting an original comment has no problems.

Symptoms: when entering text in the box, random characters go missing, or are repeated. Pressing delete does not always delete visible characters, presumable because invisible ones are being deleted first.

When vimperator is disabled, comments can be entered normally. When I removed and reinstalled Vimperator the problem recurred.

Firefox 33.0.2
Vimperator 3.8.3
Slackware 14.1 (32-bit) 

Start of sample invisible contents of comment box (too much to insert all of it):

```
<body style="" class="_4lh timelineLayout _51x9 noFooter fbx _5p3y gecko x1 Locale_en_GB" dir="ltr"><div class="_li"><div id="pagelet_bluebar"><div id="blueBarDOMInspector" class="_21mm"><div id="blueBarNAXAnchor" class="_4f7n _xxp fixed_elem"><div class="_uaw clearfix _uaw __wu" role="banner"><div class="_59g8"><a class="accessible_elem skipto" href="#newsFeedHeading" target="newsFeedHeading" id="u_0_1">Skip to News Feed</a><h1 class="_5lus" id="u_0_e"><a data-gt="{&quot;chrome_nav_item&quot;:&quot;logo_chrome&quot;}" href="https://www.facebook.com/?ref=logo"><i class="img sp_1QaCiH7tc-p sx_e9b23c">
```

**Comment by agush22** [comment]
+1

**Comment by gkatsev** [comment]
I've tracked the issue down to stopping the propagation of events [here](https://github.com/vimperator/vimperator-labs/blob/ccdaab6c10b8e4df07cbfd2a0a49bedea923341f/common/content/events.js#L1085-L1089). Unsure what the correct fix is yet. Never calling `stopPropagation` there does make facebook work as it should but it messes up with some other things.

**Comment by gkatsev** [comment]
I figured it out!

**Comment by gkatsev** [comment]
I made a new XPI release with the fix: https://github.com/vimperator/vimperator-labs/releases/tag/3.8.3-a5

**Comment by tom-marshall** [comment]
Just installed and and yeah, seems to do the trick.  Man, that was driving me freakin insane!

**Comment by gkatsev** [comment]
@tom-marshall thanks for the confirmation!

**Comment by lpil** [comment]
Awesome, thank you :D

**Comment by Figuera** [comment]
I will test this when I get home, but thanks in advance by the effort
Em 17/01/2015 21:24, "Louis Pilfold" <notifications@github.com> escreveu:

**Comment by Takemikazuchi** [comment]
+1 Gary

**Comment by jdevelop** [comment]
Works here with FF 35! Hooray (so annoyed with Chrome and vimium, U saved me years of life)

**Comment by andrewshadura** [comment]
Maybe I'm doing something wrong, but this new version doesn't (yet) fix the issue completely for me. I'll test more and report.

**Comment by Figuera** [comment]
Here worked more than fine, it also solve some strange typing bug that occurred previously. BUT for some reason I have to reinstall it every day, which is annoying.

So you may try to reinstall it.

**Comment by andrewshadura** [comment]
Indeed, after reinstalling it works again. @gkatsev, do you have any ideas on what's going on here? :)

**Comment by andrewshadura** [comment]
@gkatsev, or, maybe, it's finally the time to build an official release?

**Comment by gkatsev** [comment]
Nope, no idea why. Maybe it still had a previous version cached or something?

**Comment by maxauthority** [comment]
Yeah, we'll release a new, official 3.8.4 version after Gary figures out
some remaining help issues, and I am back from vacation.

Having Facebook fixed is certainly very important for many people.

--
Martin

**Comment by bioe007** [comment]
I noticed the bug, then used @gkatsev build and it seemed to work.

Just now FF crashed and it seems to be back to the old crazy behavior.

**Comment by bgiesing** [comment]
I seem to be having a similar issue with Google+... Any ideas?[^1]

```html
<body style="" tabindex="-1" class="Td lj Mb"><input name="hist_state" id="hist_state" style="display:none;" type="text"><iframe id="hist_frame" name="hist_frame2092328818" class="ss" tabindex="-1"></iframe><script>window['OZ_wizstart'] && window['OZ_wizstart']()</script><script>

            function ozIpStart() {

              OZ_start && OZ_start();

            }
```

[^1]: This was only a short snippet, the pages go on and on!
